### ISSUE TITLE
Delay when looping videos

### ISSUE THREAD

**Issue by holmesal** [TheWidlarzGroup/react-native-video#1002]
Hey there! I noticed that when looping videos, there is a short delay between each loop.

If the video has a cover image, it is displayed until the video starts playing.

If the video doesn't have a cover image, the video disappears and then reappears when it starts playing.

We're trying to play some perfectly looping videos. The video files are on the device, not remote. Any ideas on how to go about fixing this?

**Comment by axredstudio** [comment]
I have the same issue here, I want to have a perfect loop for my videos but it keeps lagging in between loops.

**Comment by Informateur** [comment]
The same thing. Only Android. iOS is working fine.

**Comment by yanush** [comment]
I'm trying to use this module to play sounds in my game and I also need seamless gapless looping. is it possible at all?
It works perfectly on Android but not on the iOS simulator

**Comment by JPWallhorn** [comment]
@holmesal We had the same issue but this is not a video player issue actually. A lot of times the audio track that's within the video file is slightly longer than the video itself. Therefore, there is a little lag.

You can either remove the audio track completely and make sure it's the same exact length. This is a tool that makes it both the same length: https://github.com/fluthaus/NHBAVAssetTrimming 

Because even using the native Looper didn't work. Once we fixed the audio track, our loop was perfect.
