### ISSUE TITLE
Updating paused state does nothing.

### ISSUE THREAD

**Issue by jeremyfrancis** [TheWidlarzGroup/react-native-video#1010]
I do this.setState({paused:false}) in my onLoad function. The video remains paused. I need it to play.

<Video source={{uri:''}} paused={this.state.paused} ref={ref=>this.videoRef=ref} onLoad={this.handleLoad.bind(this)} />

This needs to be fixed. Or am I doing something wrong?

**Comment by Winglonelion** [comment]
In my case, some times video continue to play after set paused: true. Android only, Ios work fine 😂

**Comment by tiendn** [comment]
@Winglonelion  me too, when I change `source` and `pause=true`, it still plays.

**Comment by cobarx** [comment]
@jeremyfrancis Which platforms are you seeing this on? Does it work properly on any of them?

**Comment by Winglonelion** [comment]
@cobarx i met it wide in many release of Android from 5.0 to 7.0. But it not happen in common case. Some times, it came unexpected and persist until you kill and restart Application.

**Comment by punksta** [comment]
I have this issue too. android

**Comment by cobarx** [comment]
Wha happens if you start with paused set to false rather than waiting until onLoad?

I will take a look and see if I can reproduce this, sounds like a race condition.

**Comment by laurent22** [comment]
Was this bug fixed in this PR? https://github.com/react-native-community/react-native-video/pull/801

**Comment by mikeyamato** [comment]
Same issue. My setup works perfectly on iOS so I'm not sure why Android is having issues with the pause functionality.

I have several moving parts when it comes to state. Updates happen anytime the user swipes the video contained in a carousel. The `repeat` prop is `false` but updates to `true` after the video plays through once. The `paused` prop is set to `false` while playing video but updates to `true` when swiping to another video. 

For arguments sake let's say I have 2 videos. Once video1 plays through 1x, it stops at the end (because the `repeat` prop is set as `false`). Then when I swipe to video2 and back to video1, video1 plays plays again from the beginning. And again, once it plays through it stops. This setup works for iOS but not Android.

**Comment by harshit-prog** [comment]
My setup works perfectly on iOS but not working in android.

I have several videos in flatlist and on the basis of the condition I manged the paused functionality but once I pause a video and play again then video restart/replay from start again.

  <Video
        repeat={false}
         source={{ uri: url }}
        resizeMode='contain'
        paused={index==this.state.index?false:true}
        ref={(ref) => {
          this.player = ref
        }}      
        style={styles.backgroundVideo} 
      />

Please let me know if there is any solution.

**Comment by harshit-prog** [comment]
> Same issue. My setup works perfectly on iOS so I'm not sure why Android is having issues with the pause functionality.
> 
> I have several moving parts when it comes to state. Updates happen anytime the user swipes the video contained in a carousel. The `repeat` prop is `false` but updates to `true` after the video plays through once. The `paused` prop is set to `false` while playing video but updates to `true` when swiping to another video.
> 
> For arguments sake let's say I have 2 videos. Once video1 plays through 1x, it stops at the end (because the `repeat` prop is set as `false`). Then when I swipe to video2 and back to video1, video1 plays plays again from the beginning. And again, once it plays through it stops. This setup works for iOS but not Android.

i got the answer just put "removeClippedSubviews={false}" in your flatlist.
