### ISSUE TITLE
Trying to get captions working on Android from feature/captions branch

### ISSUE THREAD

**Issue by fdiep** [TheWidlarzGroup/react-native-video#1041]
Hi @cobarx I am trying to use your `feature/captions` branch in order to get captions showing on Android. This is more of a proof of concept and testing current implementation.

I am using the following HLS stream
`http://sample.vodobox.com/planete_interdite/planete_interdite_alternate.m3u8`

You can test it out here and enable the english captions
`http://bitmovin.com/demos/stream-test`

The video loads and plays on Android but none of the captions are visible.

Any help is greatly appreciated

**Comment by cobarx** [comment]
@fdiep I went through and used your sample to get it working. I had forgotten to push some of my changes, plus I was using the default caption on iOS which doesn't work when there are multiple captions to choose from (like in your video).

That branch was one I built for our app where we only have one captions track, so it won't be well suited to your video if you need to be able to select between all 3. You can select the particular subtitle you want by modifying the code.

ExoPlayer:
https://github.com/react-native-community/react-native-video/blob/feature/captions/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L657
Change the first 0 to the track you want. Note that ExoPlayer sees 4 tracks where track 0 is a CEA track that doesn't work as far as I can tell.

iOS:
https://github.com/react-native-community/react-native-video/blob/feature/captions/ios/RCTVideo.m#L645
Change 0 to the track you want.

We are long overdue for robust subtitle support, so I'm going to see if I can whip up a more complete implementation in the next few days. If it's alright, I'd like to use your video for testing since all my videos only have 1 track.

**Comment by fdiep** [comment]
Thanks for the explanation @cobarx 

I pulled latest from `features/captions` and am now getting this error

```
.../node_modules/react-native-video/android-exoplayer/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java:657: 
error: package FixedTrackSelection does not exist
   = new MappingTrackSelector.SelectionOverride(new FixedTrackSelection.Factory(), 0, 0);
```

Thanks again for the help!

**Comment by cobarx** [comment]
Crap, was copying changes by hand and didn't get all of them. I pushed code that has the import.

**Comment by fdiep** [comment]
I was able to build for android with no issues but I still do not see the captions. I have changed the mentioned line to this `new MappingTrackSelector.SelectionOverride(new FixedTrackSelection.Factory(), 1, 0);` in `exoplayer/ReactExoplayerView.java`

I have also tried indexes 0, 2, and 3 but none of them bring up the captions.

**Comment by cobarx** [comment]
Are you using ExoPlayer? By default rnv uses the default Android media player which I haven't added subtitle support to.

You can change it by editing `settings.gradle` from:
`project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')`
to:
`project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')`

**Comment by cobarx** [comment]
I've got a much more complete branch with subtitle support ready now. Check out #1049 and let me know if it works for you.
