### ISSUE TITLE
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file

### ISSUE THREAD

**Issue by sesam** [TheWidlarzGroup/react-native-video#1084]
### Current behavior
With newest Android-Studio we get multi-line warning outputs:

> 
> > Configure project :react-native-video
> WARNING: Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.
> It will be removed at the end of 2018
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
> It will be removed at the end of 2018
> WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.0.
> Android SDK Build Tools 27.0.3 will be used.
> To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
> 

### Reproduction steps
Build project (gradle)

### Expected behavior
No warnings

### Platform
All platforms

**Comment by cobarx** [comment]
Thanks for the heads up. I tested and both `compileOnly` and `implementation` are only supported on the Gradle 3 plugin. Facebook has yet to even switch React Native over to the Gradle 3 plugin, so I think we need to wait until they switch over plus a couple extra months before requiring it ourselves.

I have a PR open to use build-tools 27.0.3 and will include that in the next release so that warning will go away.
