### ISSUE TITLE
Possible rejection because of private API usage

### ISSUE THREAD

**Issue by badeleux** [TheWidlarzGroup/react-native-video#1091]
### Current behavior
Describe what happens when you encounter this issue.

It hasn't happened for me yet ;)

### Reproduction steps

Send iOS app to review

### Expected behavior

iOS app should pass review

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
Any

Recently added support for request headers for iOS uses private API. `AVURLAssetHTTPHeaderFieldsKey` used here: https://github.com/react-native-community/react-native-video/blob/master/ios/RCTVideo.m#L338 is not officialy documented, therefore some apps might be rejected because of it.

**Comment by c-goettert** [comment]
Why cant you use documented [setValue](https://developer.apple.com/documentation/foundation/nsmutableurlrequest/1408793-setvalue) function so set header values? I am not a iOS specialist, but it would be nice if someone could check if it could be used instead of the private API call.

For instance, [here](https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/Libraries/Network/RCTNetworking.mm#L287-L291) you find an example from react-native, which sets `Content-Length` header.

**Comment by kesha-antonov** [comment]
@c-goettert Did you have success on this?

**Comment by skantus** [comment]
@c-goettert any update on this?
