### ISSUE TITLE
IOS presentFullscreenPlayer screen appear a while and become blank, while sound still on going

### ISSUE THREAD

**Issue by hslavax** [TheWidlarzGroup/react-native-video#1141]
### Current behavior
when the screen go into fullscreen mode, after 1 second become blank screen while the sound still can be heard

### Reproduction steps
call the presentFullscreenPlayer function

### Expected behavior
full screen mode should show the screen

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
https://cdn.filestackcontent.com/LtfjlQXQnZkRN7rr3gyw

**Comment by cobarx** [comment]
This issue has been there as long as I've been working on the project and is a pretty big problem. When I tested it today, I got the black screen and when I put the video in fullscreen after it's already playing, it plays for a few seconds and then gets stuck.

I've started looking at the code and don't know what's going on yet. If you have experience with iOS / Objective C, it would be great to have another pair of eyes on this.

Since it's a serious problem, I'll put this at the top of the list. As a workaround, I've had fairly good luck with setting the width & height to match the screen dimensions & adding my own controls rather than putting it in fullscreen mode.

**Comment by cdeust** [comment]
I've found how to fix the problem when opening the player in fullscreen.
I'd like to open a pull request for this.

**Comment by cobarx** [comment]
@cdeust That's amazing! This has been a **huge** issue for people. I'll take a look at your PR later today.

**Comment by inlinecoder** [comment]
Any progress here?

**Comment by minhphung210** [comment]
same issues , my video play in 3second and stop while sound still going.
