### ISSUE TITLE
Starting streaming on mobile data and switching to wifi keeps using mobile data.

### ISSUE THREAD

**Issue by itsmeWaqar** [TheWidlarzGroup/react-native-video#1159]
### Current behavior
Playing audio/video over a stream from mobile data and later on connecting to wifi, the streaming continues over mobile data instead of switching to wifi. Turning off mobile data then later stops the streaming when the buffer is finished.

### Expected behavior
Seamless and gapless switching between networks. So if one moves from one network to other it must switch the streaming to the other network without interruptions.

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

**Comment by cobarx** [comment]
Currently, there's nothing in the code to handle network switching. That's something that will need to get added and I don't even know what's involved. Ideally, it would seamlessly transition from mobile to WiFi. However if you're going in the opposite direction, it has to be configurable or emit an event so that developers can choose whether to use mobile data for streaming video.

It will be awhile before I can get to this, if you need it you will need to submit a PR.

**Comment by itsmeWaqar** [comment]
@cobarx may be you could hint me a bit about how it can be implemented and I can try to do it myself and submit a PR.

**Comment by cobarx** [comment]
A good starting point would be to setup notification listeners to detect when a network switch happens and when playback fails. Once you can detect when both situations are happening, you can tell the player to resume if possible or recreate the stream (called `playerItemForSource` in iOS and `initializePlayer` in ExoPlayer) if necessary. If you get stuck, chime in with where you're at and I'll do my best to help.

Btw, have you looked at something like react-native-track-player to see if it supports the features you need? Your other bug mentioned you are doing audio only, so it may be a fit and they may already support this.

Also, are you sure it's continuing to use mobile data when you switch to WiFi? What I would expect would happen is the device will automatically switch to WiFi since it is the better network connection. With audio, there is not that much data to buffer, so the whole file may be getting loaded and then there wouldn't be any further data needed, so you wouldn't see any WiFi activity.

**Comment by cobarx** [comment]
Here is an example for iOS:
https://stackoverflow.com/questions/19438095/avplayer-how-to-handle-network-interruptions
Also look at Reachability for the network change notifications.

I can't find anything for ExoPlayer except some suggestions that you listen for network change events.
