### ISSUE TITLE
Video on iPad not showing fullscreen

### ISSUE THREAD

**Issue by sxiongg** [TheWidlarzGroup/react-native-video#1161]
### Current behavior
The app is currently set up to load the video when the component mounts however it is hidden (it's position) until the user clicks an image. Then the video position within the screen and is automatically fullscreen. On iOS iPads (I've tried most version included with Xcode) it does not show however I can hear the audio playing. 

### Reproduction steps
Component mounts, user presses an image, the video appears fullscreen. Works fine on iPhones, Android phones, and Android tablets.

### Expected behavior
Video should become visible in fullscreen mode.

### Platform
iOs iPads

**Comment by ashnfb** [comment]
@cobarx I believe this is a issue related to the props being sent in different orders
I was debugging this and found that _player is not set in time for setFullscreen, and that's because _player is in a dispatch_after call in setSrc.   _player is put in the dispatch_after because textTracks/selectedTextTrack may not be set by props in time.  Is there a way to force the order of props being set?

**Comment by cobarx** [comment]
@ashnfb Nice detective work. Unfortunately, there's no way to control the order. Awhile ago, I asked the old maintainer, Brent Vatne, how he'd recommend we tackle this and he said:
> You can’t actually explicitly set the order, and you don’t want to depend on any incidental order, so you have two options (as far as I know):
> 1. use batchDidComplete (https://github.com/facebook/react-native/blob/ca898f4367083e0943603521a41c48dec403e6c9/React/Base/RCTBridgeModule.h#L300-L303)
> 2. expose the props separately but have them actually map to one native prop behind the scenes. this is also potentially helpful because it forces you to think about possibly invalid states since you’re setting them all at once

I don't fully understand how option 2 would work, since you can't compute the native prop until all the props are set.

The way the app handles it currently is with the applyModifiers function. Each time a prop is set, it reapplies all of the other ones to ensure they get applied. 

The fullscreen code is totally wonky and I have no idea why it was implemented with methods rather than a fullscreen prop. I've wanted to do a refactor to switch it over but haven't had time. The way it should work is the module should have two values: fullscreenRequested and isFullscreen. When you set the prop, it sets fullscreenRequested and then once the player can go fullscreen because _player is ready or onLoad fires or whatever, it then applies fullscreen and sets isFullscreen. If you set the prop after it's ready, it goes straight to fullscreen.

If you want to implement this, it would be awesome! I super appreciate all the time you've put in, it helps me and the project out so much. We do need to keep the methods around so it doesn't break existing apps, but they can be deprecated and removed from the docs.
