### ISSUE TITLE
react-native-video - ExoPlayer keep on buffering in android when we drag seek bar

### ISSUE THREAD

**Issue by yaramvenki** [TheWidlarzGroup/react-native-video#1173]
### Current behavior
I am using ExoPlayer and added one seek bar to show progress. When i drag seek bar bit forward keep on buffering. But it is working fine in Ios.

### Reproduction steps
1) When you play video it is playing fine.
2) Drag seek bar bit forward
3) Not it is keep on buffering, not playing video

### Expected behavior
When i drag seek bar, it should play video from that position.

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

**Comment by NaoyaRuike** [comment]
I got a similar problem and tested as below.

**Current behavior**
Video hangs up after seeking to the unbuffered position.

**Reproduction steps**
Make seek bar and call seek method on Video according to the seek bar position.

**Expected behavior**
Video does not hang up and seekable.

**Platforms**
Exoplayer and MediaPlayer
react-native 0.56 and 0.55.3
react-native-video 3.2.0 and 2.0.0


The problem seems to happen if OS is Android 5 or over and file format is m3u8.
The problem does not happen if OS is  Android 4.4.4 or file format is mp4.

Console log after seek (m3u8)
09-05 15:50:31.578 27599-27599/com.videotest D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=buffering

Console log after seek (mp4)
09-05 15:56:22.307 27599-27599/com.videotest D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=ready

The m3u8 used for my test is playable and seekable on Exoplayer 2.8.2 demo application.
https://github.com/google/ExoPlayer/tree/r2.8.2/demos/main

**Comment by anukuljha** [comment]
hey @yaramvenki  did you find any solution for this?

**Comment by yaramvenki** [comment]
> hey @yaramvenki did you find any solution for this?

Hi @anukuljha , yes it is resolved. For that you need to update exoplayer version means take latest release of exoplayer.
Happy coding

**Comment by ShaubertIlya** [comment]
Hello and good day. May be useful. I've found, that if you're using react-native-progress bar component it works slower. Especially when you use a seek function. I removed react-native-progress and replaced it with native ProgressViewIOS and ProgressBarAndroid. It works fine, no more infinite buffering

**Comment by androidparth90** [comment]
I have the same issue. Can someone please explain how to update the version of exoplayer. React native video is using an old version. the new version of exoplayer is changed now (https://github.com/google/ExoPlayer).  BTW,  I am using latest version of react-native-video
