### ISSUE TITLE
[tvOS] App crashes when going into fullscreen 'Can't add self as subview'

### ISSUE THREAD

**Issue by mxmtsk** [TheWidlarzGroup/react-native-video#1193]
### Current behavior
When entering fullscreen the app is crashing (screen turns black with loading indicator showing)

### Reproduction steps
This is the sample code that I used:

```JSX
    <Video
        ref={player => this.player = player}
        style={{ flex: 1 }}
        resizeMode="contain"
        paused={this.state.paused}
        onLoad={() => {
          // this.player.presentFullscreenPlayer();

          setTimeout(() => {
            this.player.presentFullscreenPlayer();
          }, 5000)
        }}
        source={require('./videotest.mp4')}
    />
```

### Platform
tvOS, react-native@0.55.4

### Video sample
I have tried multiple sources but feel free to use this:
https://s.wahlswiper.de/bundestagswahl-2017/01-grundeinkommen/index.m3u8

**Comment by inlinecoder** [comment]
@mxmtsk I've had a similar issue.

Try to invoke `this.player.presentFullscreenPlayer` with `onReadyForDisplay` instead of `onLoad`. Leave a `setTimeout` there. If it doesn't help right away, try to nest `<Video>` deeper in your tree. It might help. 

Also, pls take a look at https://github.com/react-native-community/react-native-video/pull/1165 <= without this PR you won't get a proper video playback on tvOS. Well, at least for now.
