### ISSUE TITLE
HLS naturalSize provided no information.

### ISSUE THREAD

**Issue by b1acKr0se** [TheWidlarzGroup/react-native-video#1194]
### Current behavior
naturalSize from `onLoad` does not return any information for HLS video.

```
naturalSize {
    height: "undefined"
    orientation: "undefined"
    width: "undefined"
}
```

### Reproduction steps
Play whatever HLS url and set an `onLoad` handler.

### Expected behavior
Return appropriate width, height and orientation of video (maybe getting from manifest?)

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer

### Video sample
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

**Comment by smartinsantos** [comment]
same problem here, any word on this?

**Comment by jaylecn** [comment]
same problem

**Comment by ntnahn** [comment]
I have same problem. Is it solved?

**Comment by kic83** [comment]
Any progress?

**Comment by ram95krishh** [comment]
![image](https://user-images.githubusercontent.com/45874777/64966357-3ff54280-d8bc-11e9-9e8f-41313af32fef.png)
Same issue. Any updates or workaround on this?

**Comment by ming436534** [comment]
I fixed this issue and created a merge request.

**Comment by dylanjha** [comment]
@ming436534 I just noticed this too. Thanks for including the patch in #1933. I hope to see that get merged.

Two things I'm trying to work through, perhaps someone here could shed some light:

1. I'm wondering, what happens when there is a rendition change. The `naturalSize` of the video source would change, would you expect the `onLoad` callback to fire on every rendition change? Or would you get the new `naturalSize` through another method?
1. Is there a way to get the width and height of the player?

The reason I'm asking about (2) is to calculate upscale/downscale metrics. I would like to get the player `width`/`height` and compare that to the source `width`/`height`. And be able to calculate this dynamically through rendition changes.

Any help in the right direction would be appreciated.

**Comment by erikpena** [comment]
Hey @dylanjha,
I'm not sure about 1).  It would seem to me that `onLoad` only gets called on first load (someone please check me on this).  I poked around and cannot find an event for when renditions change (along with any details we can get like dimensions).  **This would be helpful though** so that things can be reflected in the UI and app logic.

For 2), you should be able to use the `onLayout` event (https://reactnative.dev/docs/view#onlayout).
