### ISSUE TITLE
i am using React Navigation and Video still playing while navigate to another screen so previous video is still playing.

### ISSUE THREAD

**Issue by 07kushal** [TheWidlarzGroup/react-native-video#1223]
### Current behavior
i am using React Navigation and Video still playing while navigate to another screen so previous video is still playing.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer
* Android MediaPlayer

**Comment by otaro808** [comment]
**Presumes**
1. We have 02 screens: TopScreen and LoginScreen.
2. Use the simple case with creatStackNavigator() for both screens. Apply this navigator to App.js as below:
```javascript
import React, { Component } from 'react'
import { createStackNavigator } from 'react-navigation'

const Route = createStackNavigator({
  TopScreen,
  LoginScreen
})

export default class App extends Component {
  render() {
    return <Route />
  }
}
```

3. The video is playing in the TopScreen and we want it to stop when navigating to LoginScreen and want it to resume when navigating back.

**Solution**
It's simple. In TopScreen, use withNavigationFocus() and getDerivedStateFromProps() as below:
```javascript
import React, { Component } from 'react'
import { Button } from 'react-native'
import Video from 'react-native-video'
import { withNavigationFocus } from 'react-navigation'

class TopScreen extends Component {
state = {
  videoPaused: false
}

render(){
  <Video source={require('../some/video.mp4'} repeat paused={this.state.videoPaused}/>
  <Button onPress={()=>this.props.navigation.navigate('LoginScreen')} />
}

// Here !!!
static getDerivedStateFromProps(nextProps, prevState) {
  return {
    ...prevState,
    videoPaused: !nextProps.navigation.isFocused()
  }
}

}

// Here more !!!
export default withNavigationFocus(TopScreen)
```

_Good luck!!!_

**Comment by cerberusv2px** [comment]
this does solve the issue but next time you return to that `TopScreen` it will still pause the video and the video wont play even on clicking

**Comment by bohan0** [comment]
`<NavigationEvents
            onDidFocus={payload => {
              this.setState({ videoPaused: false });
            }}
            onWillBlur={payload => {
              this.setState({ videoPaused: true });
            }}
/>`

**Comment by jannikbuschke** [comment]
thanks @otaro808 
Only solution that worked for me so far!

**Comment by CyxouD** [comment]
thank you @otaro808 ! I tried to solve different issue: after unmounting video still played. 

**New solution**: real issue is I updated `react-native-screens` library to second version, when guide states to use `react-native-screens@^1.0.0-alpha.23` (https://reactnavigation.org/docs/en/getting-started.html#installing-dependencies-into-a-bare-react-native-project)

**Old solution**: Figured out that this solution doesn't work on iOS **when you make back swipe**, because `willBlur`, `didBlur` are not triggered in this case. I tried these workarounds:
1. Call `videoRef.forceUpdate` during unmount. It didn't help me.
2. Call `ref.seek(100500)` (any large value to scroll to the end of video). It will hep for cases when `repeat` is not set as `Video` prop, but that's not my case
3. Rely on `willFocus` of previous screen and tell that current screen's video should be paused (with redux for example). However, it is triggered after `componentWillUnmount` of current screen is called
4. Try to receive callback about swiping action (https://stackoverflow.com/a/50166493/12163490).
You should put callback in `params` of your current screen's parent. Then you can get it from `state.params`. I use redux, so I call callback which updates store. In this case you should leave my and  @otaro808 's solution, because I could get cases where it didn't work on iOS.
 This how it looks like: 
```
/**
 * Intercept actions occuring in the screen stack.
 */
const getStateForActionStackNavigator = StackNavigator.router.getStateForAction;
StackNavigator.router = {
  ...StackNavigator.router,
  getStateForAction(
    action: NavigationStackAction,
    state: NavigationStackState
  ) {
    if (state && state.params && state.params.setIsMainGoingBack) {
      // iOS fix for video not stopping after unmounting it's parent (https://github.com/react-native-community/react-native-video/issues/1223)
      state.params.setIsMainGoingBack(action.type === 'Navigation/BACK');
    }

    return getStateForActionStackNavigator(action, state);
  },
};

export default StackNavigator;
```

As a result, this can be solved with `ref.seek(100500)` if prop `repeat` isn't set or with callback about swiping action

My configuration: 
```
react-native: "0.61"
react-navigation: "4.0.10"
react-native-video: "5.1.0-alpha1" (bug happened in 5.0.2 also)
```

**Comment by mikeRChambers610** [comment]
Is there any update on this issue? It has been opened since 2018 and I think this is a very common use case to have video inside of your navigation...

**Comment by Abdullah1428** [comment]
> `<NavigationEvents onDidFocus={payload => { this.setState({ videoPaused: false }); }} onWillBlur={payload => { this.setState({ videoPaused: true }); }} />`

This works like a charm. Thank you @bohan0

**Comment by mikeRChambers610** [comment]
After working with different solutions, in my opinion, this below would be the best way to handle this issue until the react-native and or the expo team can fix the issue.

//In componentDidMount change the state if screen is rendered or not by utilizing the didFocus and willBlur listeners.
//Then using state, you can tell whether a video should play or not.

componentDidMount() {

    this._navListener = this.props.navigation.addListener('didFocus', () => {
       
      this.setState({
        isMountedVideo: true
      })
  
      });
  
    this._navListenerBlur = this.props.navigation.addListener('willBlur', () => {
    
      this.setState({
        isMountedVideo: false
      })
  
    })

}

componentWillUnmount() {

  this._navListener.remove();
  this._navListenerBlur.remove()

}



//check if screen is mounted. If so, display video component.

 {this.state.isMountedVideo ? 
(<Video...> ) : null }
