### ISSUE TITLE
More documentation about seek()?

### ISSUE THREAD

**Issue by AlexandruVoica** [TheWidlarzGroup/react-native-video#1250]
I believe the necessity for a better documentation for seek() is highly undervalued. 

Some questions that I ran into while developing using react-native-video: 
- Is seek() an async function?
- How does seek() affect the props of `<Video>`?

**Comment by n1ru4l** [comment]
Take a look at this code:

https://github.com/react-native-community/react-native-video/blob/2e3ded763a9df2acdbae36450d392345554a678d/Video.js#L53

It is not an async function, however the seek is not immediate because the javascript thread and the corresponding ios/java thread are not in sync.

You can learn more about the bridge between javascript and native code here: https://hackernoon.com/understanding-react-native-bridge-concept-e9526066ddb8

Could you please be more specific with the question: `How does seek() affect the props of ?`

**Comment by AlexandruVoica** [comment]
Thank you for your response and thank you for recommending that article! I will definitely read it for my future sanity. :) 

The reason I'm asking how does seek() affect the props of `<Video>` is because I've recently run into a bug which gave me the impression that calling seek() might somehow alter the props of `<Video>`. 

I've had a function be called when a touch gesture was initiated. Calling setState({ paused: true }) before or after seek() seem to have had no way of pausing the video. It continued to play, no matter what. I checked the `<Video>` component with react-devtools and it clearly showed that paused = true, yet the video was clearly playing. 

The workaround I found was this: 
```
this.setState({ paused: true });

setTimeout(() => this.player.seek(value), 0);
```

**Comment by n1ru4l** [comment]
This seems like a possible bug! Could you please provide information about the platform (android/ios or both) or even a repository that showcases this behaviour?

**Comment by AlexandruVoica** [comment]
Very sorry for the very late reply on my part.

I was trying on a Samsung SM-A510F running Android 7.0

Unfortunately, I cannot supply a repo as well as of right now, but might be able to do that in a very near future, since I'll probably make it public. If it's absolutely necessary, I'll try to do it quicker.

**Comment by cobarx** [comment]
Which platform are you seeing this issue on? I believe there is an open PR for iOS to handle an issue like this.

If you can paste in a snippet for just the Video related code, I can test that PR and see about getting this fixed.
