### ISSUE TITLE
Feature request: True FullScreen mode for Android with ExoPlayer

### ISSUE THREAD

**Issue by ionut-movila** [TheWidlarzGroup/react-native-video#1251]
### Current behavior
The lib. does not support a full screen mode for Android at this moment. Only disabling status bar and buttons bar, with method ReactExoplayerView.setFullscreen but that is far from what a full functional full screen.

### Expected behavior

Full screen mode should work in a similar way with what we have on iOS. The Video element should be re-parented to a new native view that will cover existing app content, like a full screen modal. This should also include all common controls: video scrubbing, volume controls, change aspect ratio + exit full screen.

This should work for Android ExoPlayer together with or without option `useTextureView`.

A good starting point I have found is this answer https://stackoverflow.com/a/48511657.
I say approach no. 1 would work ok, even if it has some compromises for Android < 6 (API 23).
And also using SimpleExoPlayerView (or new PlayerView) for a full screen transition I guess is a good option.

Not to say that we really do need this feature in our app, but I would like to hear other opinions, and why not volunteers to implement it.

**Comment by xstable** [comment]
You might have a look at my repo.
 [I fork and upgraded react-native-video-player](https://github.com/xstable/react-native-video-player) so that it now support react-native-video 4.4.0. Feel free to give it a try.

Because [here](https://github.com/react-native-community/react-native-video/pull/1414), @IbrahimSulai is working on a build-in Fullscreen functionality, you can take my solution as temporary workaround

**Comment by IbrahimSulai** [comment]
Opened a PR (#1730) for full-screen support in Android Exoplayer.

**Comment by petrosmm** [comment]
@ionut-movila I would just like to add the use of PlayerView, is how I was able to get video supported from android 4.4 and up in my native android application. If you guys added this feature, it would add 4.4 compatibility for sure.

**Comment by nickarora** [comment]
The problem with @IbrahimSulai 's implementation is that full screen relies on absolute positioning to display the full screen video.  This means that full-screen will not work if the video player's parent is not top-level.  If the video player is rendered in a nested component (like a card or in <Section /> component), you are out of luck.  It's also unfortunate that the background color of the full screen view is hardcoded to white for some reason...

All in all, I don't think we've resolved the issue here.  If we don't want to reparent the video in a native view, then we should at least consider using ReactNative Modals so that full-screen is not contingent on where in the DOM tree the video player has been inserted

**Comment by huynextlevel** [comment]
Hi @IbrahimSulai,
I also added fullscreen={true} for android exoplayer, but It's still not working as expected (Don't see full screen in the control bar)
<img width="727" alt="Screen Shot 2021-07-22 at 13 54 35" src="https://user-images.githubusercontent.com/73922436/126600219-c51bc6a7-0371-44d6-b554-8f566fb2e45a.png">
![Screen Shot 2021-07-22 at 13 55 43](https://user-images.githubusercontent.com/73922436/126600349-908b29c9-ee36-48f0-9d1d-9c78f4a4f86a.png)
