### ISSUE TITLE
iOS - seek property - JSON Value '5' of type NSNumber cannot be converted to NSDictionary

### ISSUE THREAD

**Issue by ruimfernandes** [TheWidlarzGroup/react-native-video#1270]
### Current behavior
The app crashes even before starts with this error.
![file](https://user-images.githubusercontent.com/18558899/46627137-68fc4780-cb31-11e8-9570-f66eea489ab9.jpg)

### Reproduction steps
```js
<Video
        source={{
          uri: 'http://techslides.com/demos/sample-videos/small.mp4'
        }}
        resizeMode="contain"
        resizeMethod="resize"
        style={styles.videoItem}
        seek={5}
        paused
/>
```

### Expected behavior
The video should be stopped at frame related to 5th second.

### Platform
Which player are you experiencing the problem on:
* iOS
react-native: 0.57.0
react-native-video: 3.1.0

**Comment by adamnbowen** [comment]
@cobarx Just ran into this, as I'm trying to figure out a legitimate way to start a video at a particular time---since there doesn't seem to be a "startTime" property (we want to let users continue where they left off on a video), where would you recommend we call (for example) `this.player.seek(10)`?
