### ISSUE TITLE
IOS Video isn't displaying in release mode [v3.2.1]

### ISSUE THREAD

**Issue by martinfrouin** [TheWidlarzGroup/react-native-video#1272]
It's working well on my iOS simulator (debug & release) and on my iPad (debug)
but not on my iPad (Release)
Do you have a solution ?

_Originally posted by @tinmar33 in https://github.com/react-native-community/react-native-video/issues/1150#issuecomment-428221800_

**Comment by cobarx** [comment]
@ashnfb I think this is the issue you fixed in the orientation PR. Do you want to put together a new PR with this fix and send me an example of how to setup the environment so I can test it.

**Comment by ashnfb** [comment]
@tinmar33 can you provide a description / reproduction steps of what you are trying to display (is it a local file?). Can you ensure that the file asset is being included in your release build?  (Create the archive, go into it, and verify the file is in the archive)

@cobarx the fix was that any filePath that already is prefixed with "file:///" can be returned as a NSURL directly.  If no "file:///" prefix is provided, the code searches the /Documents/ folder for a matching file.  

Two test cases:
1. a file that is included with .ipa (pre-packaged)
2. a file that is saved by the app.  iOS says we cannot guarantee the path of the /Documents/ directory, hence the need to normalize the file request to the device's /Document directory 

This use-case is NOT implemented
3. a file that is cached should be stored in the Library/caches. (this folder can be emptied anytime and it's the responsibility of the code to recache if required).

Use cases 1 and 2 were merged with the fullscreenOrientation PR.  I'm not sure I understand what a second PR would look like .. since there's no code changes?

**Comment by martinfrouin** [comment]
Hmm it seems that it was my fault because it's working now without having modified anything.. Sorry for that
