### ISSUE TITLE
duration is wrong

### ISSUE THREAD

**Issue by s0s0s0** [TheWidlarzGroup/react-native-video#1301]
### Current behavior
```
10-24 09:24:52.008  6684  6752 D ReactNativeJS: [ 'data',
10-24 09:24:52.008  6684  6752 D ReactNativeJS:   { canStepForward: true,
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     duration: -9223372036854776,
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     canPlaySlowReverse: true,
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     naturalSize: { orientation: 'portrait', height: 0, width: 0 },
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     textTracks: [],
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     canPlayFastForward: true,
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     canPlaySlowForward: true,
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     currentTime: 0,
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     audioTracks: [ { language: '', title: '0', type: 'audio/mp4a-latm', index: 0 } ],
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     canPlayReverse: true,
10-24 09:24:52.008  6684  6752 D ReactNativeJS:     canStepBackward: true } ]
```
duration is `-9223372036854776`

### Reproduction steps
Download mp4a-latm and see.

### Expected behavior
duration should be positive integer

### Platform
Which player are you experiencing the problem on:
* Android MediaPlayer (latest)
iOS is fine. (latest)

iOS/Android works fine on (package version 2.x.x). I am trying to upgrade to latest 4.x

### Video sample
see comments.

**Comment by s0s0s0** [comment]
[test.zip](https://github.com/react-native-community/react-native-video/files/2511368/test.zip)
you need to unzip and rename this file. (PS: only audio no video)

**Comment by Happytrio** [comment]
I have the same problem. iOS is fine。but android：  duration: -9223372036854776,

**Comment by s0s0s0** [comment]
@cobarx there is a confusion. This error is shown in 4.x, but not reproducible in 2.x. I believe there is a bug in the latest version. Please reopen this issue.

**Comment by uncledent** [comment]
Same problem on all 4* versions. When wile uploaded from ios and trying to download on android - "data":{"canStepBackward":true,"canPlayReverse":true,"canPlaySlowReverse":true,"canPlaySlowForward":true,"textTracks":[],"audioTracks":[{"language":"","type":"audio/mp4a-latm","title":"0","index":0}],"canStepForward":true,"canPlayFastForward":true,"naturalSize":{"orientation":"portrait","height":0,"width":0},"currentTime":0,"duration":-9223372036854776}

**Comment by GrinchakAndrew** [comment]
I have got same issue on Android for type "audio/mp4a-latm", pls., re-open the issue.

**Comment by CptFabulouso** [comment]
Happens to me with mp3 files

**Comment by joepake** [comment]
Same issue on iOS for type (audio/mp4; codecs="mp4a.40.2") seem player duration in onLoad = 2 x real-audio-duration

**Comment by anshul-kai** [comment]
This is definitely happening on iOS when using a URL for a vbr MP3. Here's a sample file. It's exactly 10 minutes long.

https://bnirvana-tmp.s3-us-west-2.amazonaws.com/duration-test.mp3

**Comment by ALashchotka** [comment]
Any solutions?

**Comment by ccksfh** [comment]
Any solutions?

**Comment by Javimtib92** [comment]
I'm having the same problem, is there any workaround?

**Comment by Javimtib92** [comment]
There's a related issue where I also commented and I found something that might be interesting

https://github.com/react-native-community/react-native-video/issues/1812

**Comment by MinhNguyenWre** [comment]
Any solutions now? still get this bug.

**Comment by SpQuyt** [comment]
Any solutions please? I still get this bug.

**Comment by SpQuyt** [comment]
In my case, the video from remote URL worked fine. But when I downloaded it, react-native-video could not get exact duration. It returned -9223372036854776
Since this library has this bug on Android, you can use some tricks by using this repo to get duration instead.
https://github.com/mybigday/react-native-media-meta

I tested and worked for my case.

**Comment by SpQuyt** [comment]
Sorry everyone, my trick can only be used to show duration. I cannot seek the video because the real duration from react-native-video is invalid. 
So I still need help on this problem

**Comment by Younext19** [comment]
Still happening on 6.3.0

**Comment by freeboub** [comment]
> Still happening on 6.3.0
> 

This issue is too old, please open a new one

**Comment by hasnainadam7** [comment]
🐞 Bug: Video duration returns negative value for a specific video (Android)
Description
On Android, the video duration is returned as a negative value for one specific video. Other videos work correctly, but this particular video always returns a negative duration, which breaks progress and timing logic.

Environment

Platform: Android only

React Native: 0.xx.x

Library version: x.y.z

Device: Real device

Android version: xx

Steps to Reproduce

Load the specific video (same file every time)

Read duration from the library API

Duration is always negative for this video

Actual Behavior

duration is a negative number (e.g. -1, -0.x) for this video

Expected Behavior

duration should be a valid non-negative number

Video metadata should be parsed correctly regardless of the file

Notes

Reproducible 100% of the time with this video

Issue does not occur with other videos

Possibly related to how this video’s metadata is encoded or parsed on Android
