### ISSUE TITLE
What do i have to do to enable VTT Subtitles Support

### ISSUE THREAD

**Issue by cvaldezscse** [TheWidlarzGroup/react-native-video#1393]
### Current behavior
I am trying to setup the subtitles into react native video based player but when trying to make it run on iOS is not working. Does anybody knows how to run it.

### Reproduction steps
Run In iOS with another react native component called [AFVideoPlayer](https://github.com/abbasfreestyle/react-native-af-video-player) and adding to the control bar a toggle Subtitles button is not working

### Expected behavior
Hide and show the Selected subtitles (selectedTextTrack) clicking a button to change the state from { type: 'title', value: 'English'} to {type: 'disabled', value: ''}

### Platform
Which player are you experiencing the problem on:
* iOS

### Video sample
[Link to see the issue in action](https://media.giphy.com/media/SG5vNjeDXdgGYhWwHm/giphy.gif)

**Comment by cobarx** [comment]
AFVideoPlayer is using react-native-video 2.0.0 so it's possible we fixed some bugs or added additional support for subtitles since then. Also, if you're using a set of controls on top of RNV, you'll need to work with them to get the bugs worked out.

I would create an example that uses RNV directly, make sure the subtitles work then fix the bug in AFVideoPlayer and submit a PR to them or add more info here if it's a bug in RNV.
