### ISSUE TITLE
Change source uri dynamically

### ISSUE THREAD

**Issue by EnriquezAndoni** [TheWidlarzGroup/react-native-video#1394]
### Current behavior
I am trying to change the video uri dynamically, but it doesn't reload the video when you change it. Does anybody know how to run it?

### Reproduction steps
Change the video uri dynamically.

### Expected behavior
Automatically reload the video component when the uri change. 

### Platform
Which player are you experiencing the problem on:
* iOS

**Comment by supritshah1289** [comment]
@EnriquezAndoni I have develop an app which dynamically passes url to video component and movie starts buffering. It works perfectly fine I had to add some delay while passing the url to the video component. Also, I am using the older version 3.2.1 because the latest version does not support the video url I am passing to Video component.
