### ISSUE TITLE
Video Scrubbing 

### ISSUE THREAD

**Issue by mattsidjohn** [TheWidlarzGroup/react-native-video#1396]
### Current behavior
Trying to create a video review app that allows scrubbing back and forth on finger drag ( slow, and fast) behavior works as expected going forwards using the .seek() exact function however when moving backwards it stalls and jumps multiple seek frames. I would pay someone who has developed or maintains this plugin to help me get this resolved as this is a very important and high profile project. Please advise.

https://www.dropbox.com/s/mvz9x0nnwc9ejd5/Example.mov?dl=0

**Comment by calebmcelroy** [comment]
Any updates on this? Did you figure something out? I need this as well.

I found this article (https://developer.apple.com/library/archive/qa/qa1820/_index.html) and I implemented the concept in javascript, but it didn't really help.

**Comment by manuelbieh** [comment]
Currently running into the same issue as described. I need fine grained control (forwards and backwards) and while forward works mostly fine, backwards is super slow and laggy.

**Comment by Navipro70** [comment]
If we are talking about simple video player slider, I advice you to write own slider with react-native-reanimated. Some tips and it will works as expected at 99%. But you shouldn't call seek when sliding, just control it with second variable that takes control over onProgress when you sliding.

 If we are talking about controls (such as 15sec back and forward). I faced with onProgress asynchronization (only android, IOS works well), because after seeking, seek doesn't call onProgress, and we should synchronize state manually, but it hard)

**Comment by freeboub** [comment]
@hueniverse i think you should keep this issue open. This is a real feature which make sens to support. On my custom branch, i implement it with a custom manifest parser on an old exoplayer, i think last exoplayer version supports it natively.

**Comment by hueniverse** [comment]
@freeboub not sure if this is a bug or feature request? When you say the latest version supports it does it mean this issue will be fixed as soon as we upgrade or will need more work?
