### ISSUE TITLE
Displaying controls on Android (play, pause, progress bar)

### ISSUE THREAD

**Issue by supritshah1289** [TheWidlarzGroup/react-native-video#1404]
### Current behavior
Controls are hidden when video starts on Android

### Expected behavior
When video starts on Android platform, I want to show controls like play, pause and progress bar of the video. 

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Video sample
<img width="715" alt="screen shot 2018-12-30 at 11 22 27 am" src="https://user-images.githubusercontent.com/5491337/50549326-deefe680-0c28-11e9-9eb0-5b6dcf1c0fad.png">

plaform: Android
react - 16.56.6
rn - 0.57.8
react-native-vide - 3.2.1 ( latest version does not work for my url type)

Below is the video component for rendering url

<Video
source={{uri: this.props.navigation.state.params.watchUrl}}
ref={(ref) => {
this.player = ref
}} // Store reference
onBuffer={this.onBuffer} // Callback when remote video is buffering
onError={this.videoError} // Callback when video cannot be loaded
style={styles.backgroundVideo}

fullscreen={true}
controls={true}
/>

Thank you and Appreciate for your time.

**Comment by cobarx** [comment]
At this time, we don't provide controls on Android because the system doesn't provide them. You should use a React Native package that provides controls or build your own. I've updated the README with this info.

At some point in the future, we may offer controls.

**Comment by sunilzalavadiya** [comment]
@cobarx glad to know that this will available soon..

**Comment by aylacullen** [comment]
@cobarx - one of the developers I contracted with to develop an app for us (it's designed for the deaf in mind) cited this issue in where controls weren't available.  The issue at hand is we want the video to be able to provide subtitles while also providing controls.  Since your library does not support controls, would you be able to recommend an alternate React Native library that supports both?  I know those aren't within your scope, but I thought I'd give it a shot in asking.

**Comment by xstable** [comment]
@cobarx can you give a hint, how to build own controls?
What's with this PR: https://github.com/react-native-community/react-native-video/pull/1414
Could you check and merge it... that should solve the Request?
