### ISSUE TITLE
pause playback on incoming calls

### ISSUE THREAD

**Issue by mojtaba-hajishah** [TheWidlarzGroup/react-native-video#1434]
### Current behavior
I'm using this lib to play audio files. on incoming calls, the playback does not pause and continues playing in the background.

### Expected behavior
playback getting paused on incoming calls.

**How can I achieve this?**

### Platform
Android

Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by pengcao1** [comment]
This caused by the audio focus issue

**Comment by mojtaba-hajishah** [comment]
any updates on this?

**Comment by Assisneto** [comment]
any updates on this?

**Comment by marcmoo** [comment]
any update on this issue? same thing here, backgrounded app playback does not pause when receives call from Viber/Whatsapp messenger, iOS when receiving phone calls

**Comment by scottg489-tw** [comment]
I'm experience this as well.

@pengcao1 I'm not familiar with the audio focus issue. Would you have more information on this? Thanks!

**Comment by scottg489-tw** [comment]
Out of curiosity, what was the PR/commit that fixed this?

**Comment by hueniverse** [comment]
Closed due to being stale and lack of resources to resolve it at this time. We won't be able to get back on track with 1000+ open issues. I expect many of the closed issues to be reported again once the new version is released, but that way will give us fresh info and hopefully many will be resolved.
