### ISSUE TITLE
Save cached video to local storage

### ISSUE THREAD

**Issue by eddyjusufi** [TheWidlarzGroup/react-native-video#1473]
If i provide a URL link as source to the video, after it has loaded, is it possible to save the video locally, using SQLite storage for example, and be able to play it offline if needed?

**Comment by hakkikonu** [comment]
actually storing video in a sql db is very bad idea. Instead store videos on phone memory or external memory card and store videos’ local address on a database.

Storing blob data on a sql db is
not efficent. Especially mobile device limitations are great walls.

**Comment by eddyjusufi** [comment]
@hakkikonu SQLite is a database which stores data locally on the device. (https://aboutreact.com/example-of-sqlite-database-in-react-native/) 

This issue is all about requesting a feature for this library to store cached videos onto a **local database** (not Photo Library).

**Comment by hakkikonu** [comment]
@EddieEJ i know sqlite a local database. I mean you shouldn’t store video’s raw data on your sqlite.

Just reference to it with your sql db

**Comment by eddyjusufi** [comment]
@hakkikonu It would be great if you could provide an example of your suggestion. 

As far as I am aware, there isn't a way to obtain the raw data of the video, which you could then store locally in order to allow the users to view the video offline next time without the need to re-download it again, is there?

**Comment by muhammadmisbah** [comment]
@EddieEJ  @hakkikonu 
Did you find any solution??
I want to save video in application storage not in CameraRoll or Gallery.
as we can see the feature VLC player providing. it doesn't save video in CameraRoll, specially in iOS.

**What I'm doing here is**: Capturing Video with `react-native-camera` and uploading it. if i'm offline it won't upload but will wait for network, when it'll be available the video will be uploaded.
but the problem is, if user kills the application before the video done uploading so the uploader won't find the video on the same path. so i need to save video in the application storage for a while.
