### ISSUE TITLE
I am facing issue of black screen on android .My link is https and i have tested it on several mobiles,sometimes video play the other time its just black screen

### ISSUE THREAD

**Issue by ShrutiGarg019** [TheWidlarzGroup/react-native-video#1547]
### Current behavior
Describe what happens when you encounter this issue.

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.

### Expected behavior
Describe what you wanted to happen

### Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by 1152295219** [comment]
I also faced this problem with android

**Comment by gsunsnackv** [comment]
I used to run into stucked black screen all the time. The most strange one I experience is https://github.com/react-native-community/react-native-video/issues/1538

My feeling is this project manage the native video player instances very poorly (especially on Android). The project frequently mess things up when you have multiple native video player instances. In our project, we had to do a lot of difficult and hard things to ensure that we only have one instance of a screen that have the <Video> tag, thus only one native video player instance, then it won't stuck.

**Comment by CHaNGeTe** [comment]
Please test with 4.4.4.
If still not works I will reopen the issue

**Comment by cms24us** [comment]
i have the same issue using 4.4.4. playing two or three videos on androdi and screen go black. seems stuck on buffering. if i close the app completly and run againg, the video works fine again. 

on ios works fine, no matter how many videos i play.

any idea or indication on how to fix it?

**Comment by CHaNGeTe** [comment]
An example repo will help, I reopen the issue

**Comment by cms24us** [comment]
i just create a new app to have the repo to share, but seems to work fine this new app. i just play mora than 20 videos without problem. 

my main app still stuck. i have no idea why. right now i just see the exemple is using react.native 60.4 and the main app is using react-native version 59.9. do you thing this may be the issue?

i try to update the main app to 60.4 but i have a few issue. i will keep investigating in order to find the bug or be able to reproduce it on a new and sharable repo. 

UPDATE: 
i create a new app using version 0.59.9 and react-native-video 4.4.4. after testing with 30 video plays, no issue found on android device. Sometimes show a black screen for 1 or 2 seconds but start playing after no problem. 

seems like is working fine. something weird is on my code that make the black screen stuck. i'll keep looking.

UPDATE:
seems like when i press the back button on android, the video keep playing, even when the component get the unmount. so, when i try to load a new instance of that componente, the initial video is still playing and that's when i get the black screen. 
i have to do the back button a few times to get the video stuck.  

FINAL UPDATE:

i find out what's the problem. som how i use a bad router structure, i use a stacknavigator inside another stacknavigator and that makes some strange routing that make the video don't stop playing even when i go back or get outside the app. the video still playing. 

i just create a bottomTabBarNavigator and set this inside a StackNavigator in order to use some modal screens. 

thanks @CHaNGeTe for you time. for me you can close the issue. turns out is not with react-native-video, for me the issue was with react-navigation i how i set up things. 
if anyone has this issue, i suggest create a new project and test it along. this way i discover the issue was with the navigation.

**Comment by ReneMarquez** [comment]
> i just create a new app to have the repo to share, but seems to work fine this new app. i just play mora than 20 videos without problem.
> 
> my main app still stuck. i have no idea why. right now i just see the exemple is using react.native 60.4 and the main app is using react-native version 59.9. do you thing this may be the issue?
> 
> i try to update the main app to 60.4 but i have a few issue. i will keep investigating in order to find the bug or be able to reproduce it on a new and sharable repo.
> 
> UPDATE:
> i create a new app using version 0.59.9 and react-native-video 4.4.4. after testing with 30 video plays, no issue found on android device. Sometimes show a black screen for 1 or 2 seconds but start playing after no problem.
> 
> seems like is working fine. something weird is on my code that make the black screen stuck. i'll keep looking.
> 
> UPDATE:
> seems like when i press the back button on android, the video keep playing, even when the component get the unmount. so, when i try to load a new instance of that componente, the initial video is still playing and that's when i get the black screen.
> i have to do the back button a few times to get the video stuck.
> 
> FINAL UPDATE:
> 
> i find out what's the problem. som how i use a bad router structure, i use a stacknavigator inside another stacknavigator and that makes some strange routing that make the video don't stop playing even when i go back or get outside the app. the video still playing.
> 
> i just create a bottomTabBarNavigator and set this inside a StackNavigator in order to use some modal screens.
> 
> thanks @CHaNGeTe for you time. for me you can close the issue. turns out is not with react-native-video, for me the issue was with react-navigation i how i set up things.
> if anyone has this issue, i suggest create a new project and test it along. this way i discover the issue was with the navigation.

Hello, can you give an example of your react navigation structure? I'm facing the same black screen issue on android and I'm using react navigation with one StackNavigator atm, thanks!

**Comment by cms24us** [comment]
Sure @ReneMarquez 
my initial router was like 

```
const model1StackNavigation = createStackNavigator(
  {
   main1screen,
   model1 (video play here)
model2:
  },
);

const model2StackNavigation = createStackNavigator(
  {
   main2screen,
   model3
  },
);

const MainStackNavigation = createStackNavigator(
  {
model1StackNavigation,
model2StackNavigation,
main2screen,
  },
);
export default createAppContainer(MainStackNavigation);

```



my final router was like 

```javascript
const BaseStackNAvigation = createBottomTabNavigator(
  {
    Main1,
    Main2,
    Main3,
  },
  {
    headerMode: "none"
  }
);

const GeneralStackNavigation = createStackNavigator(
  {
    Base: { screen: BaseStackNAvigation },
    modal1, (video play here)
    modal2, 
    modal3,
  },
  {
    headerMode: "none",
    mode: "modal"
  }
);

export default createAppContainer(GeneralStackNavigation);
```

i hope this help you ;)

**Comment by paddy57** [comment]
I have flat list , where after each 10th video, i'm adding another 10th video, and i'm getting black screen on them, while audio is playing

I'm using react-native-video@3.0.0 and android player 
Can anyone guilde me through this.
Thank you.

**Comment by CHaNGeTe** [comment]
any reason not to update react-native-video?

**Comment by paddy57** [comment]
> any reason not to update react-native-video?

My react-native version is 0.55.4 and on react-native-video docs it says 3.0 is compatible with RN  >= 0.40.0, thats why.
Are you suggesting me to update,In that case to which version of react-native and do i need to upgrade my RN too?

**Comment by paddy57** [comment]
I have upgraded to 3.2.1 but still the black screen is there and audio plays in background

**Comment by gouravrc** [comment]
> ```js
>     modal1, (video play here)
> ```

@cms24us  
1. I replaced my stack navigation and directly ran the video component in App.js. 
2. I exported only one screen and maintained only one stack navigator. 

For both cases, the black thing appeared.  Do you still feel it is because of the navigation?

**Comment by cms24us** [comment]
absolulty @geekygaurav, for me the issue was de navigation. 

I see you try to replace the stack-navigation. for me the key was to create a new app from scratch. add the video player and check if works. then add the navigation and check again. in that point was when i realize that the navigation was the issue for me.

**Comment by gouravrc** [comment]
@cms24us 
Okay, I think maybe this is not just an actual fix. Because if the problem would have really lied in the navigation, then for iOS also it would have occurred. But for me, the iOS running absolutely fine as expected. 
I explored and still exploring, I think there is some issue with exoplayer in android. And also people are saying it is sporadic and depends on the device. Let's hope the community comes up with a concrete solution.

**Comment by brerdem** [comment]
I have the same problem here. I'm using StackNavigators inside a BottomTabNavigator and when I change tab to that one with the video, the video starts with a black screen. That takes only couple milliseconds but it's visible anyway

**Comment by waheedakhtar694** [comment]
my video is always show a blank screen with audio is playing.

**Comment by gouravrc** [comment]
@appify-waheed  check your settings.gradle
did you mention exoplayer?
`include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
`

**Comment by waheedakhtar694** [comment]
@geekygaurav yes it's been mention there.

**Comment by IamMasterWayne** [comment]
"react-native": "0.61.5"
  "react-native-video": "^5.0.2"

React Native Android Black Screen For Android

**Comment by GilHogan** [comment]
same issue
"react-native": "0.60.5"
"react-native-video": "^5.0.0"

use Android ExoPlayer
android version: 4.1.1

**Comment by waheedakhtar694** [comment]
I was having this issue because of `hardwareAccelerated = false` in `AndroidManifest.xml` file

**Comment by GilHogan** [comment]
Solve the problem by changing the video encoding format：
https://github.com/react-native-community/react-native-video/issues/1731#issuecomment-551616563

**Comment by nikodem-wrona** [comment]
:+1

**Comment by Lemaro86** [comment]
I resolved the same issue on android with **s** at the end of protocol. 
Maybe it can help and you. Use for android only **https** link for video. If you use **http** you have got black screen.
I think it's exoplayer bug or feature.

**Comment by younusmahmood** [comment]
I'm running into the same issues with the black screen. Also, docs for android installation aren't up to date with the latest create react native app. Has there been any update for anyone? I tried everything on the internet, nothing works. My video is hosted under my assets folders so it's part of the project too. Works perfect with iOS but on Android, it gives me a black screen. If I change to remove exoplayer, it shows me a white screen.

**Comment by manhhoan76** [comment]
thanks @waheedakhtar694

**Comment by pankajinfowind** [comment]
> I was having this issue because of `hardwareAccelerated = false` in `AndroidManifest.xml` file

You saved my day!!! Thanks you very much

**Comment by ZhminkoRoman** [comment]
If you use http protocol of video, please, add android:usesCleartextTraffic="true" to your AndroidManifest.xml

**Comment by neilanthonyte** [comment]
> I was having this issue because of `hardwareAccelerated = false` in `AndroidManifest.xml` file

This is what's causing my issue too . . all good now after switching it to true or just remove it
