### ISSUE TITLE
Video is coming to begin in write file operation.

### ISSUE THREAD

**Issue by vncsms** [TheWidlarzGroup/react-native-video#1624]
# Bug

I'm loading videos from 9gag api, and every video i'm saving the video in local storage (via rnf-fetch-blob) and then load the video from local storage. But the app does this multiples videos in the same time. When i play a video (From local storage), the video is pausing and back to begin every time another video is saving into local storage, like if every write operation set the video to begin. And i don't know how to solve this. This is normal to happens, or i have to check the rn-fetch-blob. 

## Environment info

"react-native-video": "^4.4.1",

Android: Android 5.1

Model Number: Moto G

## Steps To Reproduce

- Save a lot of video in the same storage where are you loading the video.

**Comment by ghost** [comment]
@vncsms Nothing in Android or RNVideo's source code is supposed to roll the video back to the start when you access the filesystem, especially on another file.
You should ask this on [StackOverflow](https://stackoverflow.com/) since the issue is most likely caused by your code at this point.

Be sure to include enough of your code so people can help you with it.

**Comment by danielmarino24i** [comment]
I am not sure at all, but have you checked if you are changing some prop that is causing a full re-render? (updating source object prop, or sth like this)
I agree also to post the question on StackOverflow.
