### ISSUE TITLE
onLoadStart's arg.isNetwork reports true even when playing file from device storage

### ISSUE THREAD

**Issue by tomprogers** [TheWidlarzGroup/react-native-video#164]
I'm recording a video using react-native-camera, and then immediately playing it back using this module.

When the `<Video>` renders, it fires `onLoadStart` with information about the source, like so:

```
onLoadStart = (source) => {
    /*
    source == 
    {
        "src": {
            "uri": "file:///var/mobile/Containers/Data/Application/5B575E25-FBE0-443E-8828-0CB31F3B8A3C/Documents/A2BF3409-15B7-46EE-B8D7-0F4990C99787.mov",
            "type": "mp4",
            "isNetwork": true
        },
        "target": 85
    }
     */
};
```

If a video that lives inside the application's own private storage counts as `isNetwork:true`, then I don't think there could be any scenario that would register as `isNetwork:false`.

This suggests to me that either the current behavior is a bug, or that `isNetwork` is not the best name for whatever it reflects.

Currently using react-native-video v `0.7.1`.

**Comment by facetious** [comment]
I suspect you're on iOS. This is happening because of this entry in the response dictionary (from RCTVideo.m): `@"isNetwork": [NSNumber numberWithBool:(bool)[source objectForKey:@"isNetwork"]]},`. This cast to a `bool` will always result in a positive when the object exists, regardless of its value. The correct obj-c way to do this is with the `boolValue` selector, or to keep in line with the other casts in RN, `[RCTConvert BOOL:[source objectForKey:@"isNetwork"]]`. In fact, you can see the correct usage in `playerItemForSource:` in the same file.
