### ISSUE TITLE
error setting property src of RCTVideo

### ISSUE THREAD

**Issue by eduedix** [TheWidlarzGroup/react-native-video#17]
I get the following error while loading a page with <Video /> . Seems to be broken after an update today.

[tid:com.apple.main-thread][RCTVideoManager.m:35] Error setting property 'src' of RCTVideo with tag #67: RCTVideo does not have setter for `src` property
![ekran resmi 2015-04-09 23 23 03](https://cloud.githubusercontent.com/assets/2974524/7076060/672bacdc-df0f-11e4-9160-4d464cef4fb8.png)

**Comment by brentvatne** [comment]
@eduedix - what version of `react-native` are you using? I updated this for `0.3.10` today, which is required

**Comment by brentvatne** [comment]
@eduedix - also, the newest update requires that you do

`<Video source={{uri: "name-here"}} />`

**Comment by eduedix** [comment]
OK it is fixed

**Comment by brentvatne** [comment]
:smile: great!

**Comment by ghost** [comment]
I was seeing the same problem earlier running the included _VideoPlayer_ example. To get the example working I cloned from `master` instead of the `0.3.5` tagged branch -- which was giving me a hard time.

Here are the steps I followed to run the example locally:

``` sh
git clone git@github.com:brentvatne/react-native-video.git
cd react-native-video/Examples/VideoPlayer
npm install
open VideoPlayer.xcodeproj
```

Then `Cmd+R` to start the React Packager, build and run the project in the simulator.

**Comment by brentvatne** [comment]
@jhabdas - can you add those steps to the README?

**Comment by ghost** [comment]
@brentvatne added steps in #35
