### ISSUE TITLE
Unable to play video in android, using remote video address

### ISSUE THREAD

**Issue by hinet** [TheWidlarzGroup/react-native-video#174]
`<Video ref='myVideo' source={{uri: "http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8"}}
                           style={styles.fullScreen}
                           rate={this.state.rate}
                           paused={this.state.paused}
                           volume={this.state.volume}
                           muted={this.state.muted}
                           resizeMode={this.state.resizeMode}
                           onLoad={this.onLoad}
                           onProgress={this.onProgress}
                           onEnd={() => { this.refs.myVideo.refs.node.seek(0) }}
                           repeat={true} />
                </TouchableOpacity>`
Mp4 format can not play

**Comment by hinet** [comment]
**My running environment：**
android studio,react-native 0.22
my code:

**settings.gradle**
`
rootProject.name = 'shanxiang'
include ':app'
include ':RCTVideo'
project(':RCTVideo').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
`

**app/build.gradle**
`
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
   ** compile project(':RCTVideo')**
}
`
**MainActivity.java**
`
package com.shanxiang;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
**import com.brentvatne.react.ReactVideoPackage;**

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

```
/**
 * Returns the name of the main component registered from JavaScript.
 * This is used to schedule rendering of the component.
 */
@Override
protected String getMainComponentName() {

    return "shanxiang";
}

/**
 * Returns whether dev mode should be enabled.
 * This enables e.g. the dev menu.
 */
@Override
protected boolean getUseDeveloperSupport() {
    return BuildConfig.DEBUG;
}

/**
 * A list of packages used by the app. If the app uses additional views
 * or modules besides the default ones, add more packages here.
 */
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new ReactVideoPackage()
    );
}
```

}

`

Where did I have the wrong configuration？

**Comment by dojiboy9** [comment]
Hi, I was recently able to get it working for myself using a similar setup (react-native 0.22, android).
For me, I thought it wasn't working, but it turned out it was just taking a while (like 10 seconds) to load the video.

One thing you can try for debugging:

add an `onLoadStart` prop that console.warns that loading is starting
modify the `onLoad` prop to console.warn that the loading is completed

e.g.

`<Video ref='myVideo' source={{uri: "http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8"}} style={styles.fullScreen} rate={this.state.rate} paused={this.state.paused} volume={this.state.volume} muted={this.state.muted} resizeMode={this.state.resizeMode} onLoadStart={() => {console.warn("loading started");}} onLoad={() => {console.warn("loading done");}} onProgress={this.onProgress} onEnd={() => { this.refs.myVideo.refs.node.seek(0) }} repeat={true} />`

Make sure you see these two debug statements (again, it may take a few seconds for the loading to complete). Usually after that, the video loads.

If you don't see the two statements, something else might be wrong. If you do see the statements, but don't see the video play once "loading done" appears, then your video might just be styled incorrectly..? Also, check to make sure that the `this.state.paused == true`

Hope this helps.

**Comment by hinet** [comment]
Thanks, but I do not know why, the video can be played again, but now can not play

**Comment by qxqxqxqx** [comment]
@dojiboy9 I did exactly like your code,the uri is the same.And 'loading done' appears,but still no video played.

**Comment by ghost** [comment]
Stale
