### ISSUE TITLE
Video freeze for very short amount of time when loaded to player 

### ISSUE THREAD

**Issue by paddy57** [TheWidlarzGroup/react-native-video#1751]
# Bug

  I have list which includes mp4 remote links to videos, when i loads another video url to player, you can notice there is freeze after 1 sec and then video starts normally.
Following is the link to Demo 
https://streamable.com

Library version: x.x.x

    "react-native-video": "^3.0.0",
    "react-native": "0.55.4",
    "react": "16.3.1",

## Steps To Reproduce

1)Change video link to another
2)Notce the small freeze after 1 sec 

Describe what you expected to happen:

1.Video to play smoothly when loads into player 

Code:
   <Video
                        repeat
                      
                        resizeMode='cover'
                  
                
                        source={{ uri: this.state.videos[this.state.videoNumber] }}
                        ref={ref => {
                            this.player = ref;
                        }}
          
                        onError={this.handleError}
                        style={{
                            width: 400,
                            height: 600
                        }}

                     onLoad={() => console.log("loaded player")}
                    />

**Comment by paddy57** [comment]
I found that, when my video length is greater than 10 sec, i'm getting this freeze momemt, if video length is below 10 sec, its not freezing, can anyone guild me through this?

**Comment by aryo** [comment]
Happens to us as well, just on iOS.. seems like the reason is the load gets dispatched to the main queue despite being async (per https://github.com/react-native-community/react-native-video/blob/master/ios/Video/RCTVideo.m#L350).

We've tried dispatching to the global queue instead and the problem goes away. However, we're only using RNVideo to stream audio without controls, so not sure of the impact of doing that for videos w/ controls or if it's even possible.

**Comment by paddy57** [comment]
thank you @aryo for your response, i updated my react-native-video to latest version and the bug was gone, but i still want to know what was the issue with 3.0
