### ISSUE TITLE
iOS: HLS video not playing if square bracket in the file name

### ISSUE THREAD

**Issue by j3ski-passion** [TheWidlarzGroup/react-native-video#1772]
# Bug
I am getting a `NSURLErrorDomain` error when trying to play this file:
https://d1gqj3imblax0x.cloudfront.net/uploads/embeddable/asset/218990/transcoded/index.m3u8
where this one is fine:
https://d1gqj3imblax0x.cloudfront.net/uploads/embeddable/asset/219004/transcoded/index.m3u8
This is the same file, the only difference is the presence of square brackets (and spaces) in the file name of the "corrupted" one.

Safari is able to play both.

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
 info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 1.06 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
```

Library version: 5.0.2

**Comment by akempe** [comment]
have you tried url encoding those values? safari is probably automatically doing this for you

**Comment by j3ski-passion** [comment]
Yes, if the file name is url encoded it works, but that means I have to check all my files on s3 and make updates there, I'd rather rn-video do the same thing Safari is doing.

**Comment by CHaNGeTe** [comment]
@j3ski-passion I am closing the issue as it is a problem for AvPlayer itself (you can check by making a simple native project)

But if it is a difficult to address problem (because you have to change gazillions of videos), I would suggest you to implement AVAssetResourceLoaderDelegate and pass to the player fake urls, for example, by setting an invented protocol (f.e: `my-video://d1gqj3imblax0x.cloudfront.net/uploads/embeddable/asset/218990/transcoded/index.m3u8`)

You can then modify parse the HLS manifest and change it on the fly.

You have an example of AVAssetResourceLoaderDelegate integration with this library here:
https://github.com/react-native-community/react-native-video/pull/1445
