### ISSUE TITLE
Incorrect Duration 

### ISSUE THREAD

**Issue by edisonlao** [TheWidlarzGroup/react-native-video#1812]
Current behavior
I'm trying to download m3u8 video merge to mp4 video and use any video player can get a correct 
 duration , and then seek success. 
when i use react-native-video to play this mp4 video normally,   but get a wrong duration like 【-9223372036854776】，it will cause seek failure.

Reproduction steps
use react-native-video play https://file.io/FucsnY

Expected behavior
get a correct duration and seek to a time and watch the play position

Platform
Which player are you experiencing the problem on:

Android9.0 
Version
React Native 0.58.5
react-native-video 4.4.0

**Comment by flexgrip** [comment]
You’re on a very old version of RNV and also ... this isn’t enough information. Your file link gives a 404. And I don’t see a question above. You are describing a behavior but without enough detail for anyone to help you.

Upgrade RNV to at least 4.4.4 and see if the behavior changes. You can always grab the duration from the onLoad callback. That’s a massive negative integer to just randomly return. So I think your problem is elsewhere.

**Comment by ccksfh** [comment]
> You’re on a very old version of RNV and also ... this isn’t enough information. Your file link gives a 404. And I don’t see a question above. You are describing a behavior but without enough detail for anyone to help you.
> 
> Upgrade RNV to at least 4.4.4 and see if the behavior changes. You can always grab the duration from the onLoad callback. That’s a massive negative integer to just randomly return. So I think your problem is elsewhere.

My RNV is 4.4.4 and nothing changed. I still got the incorretct duration same as edisonlao

**Comment by chiefchief** [comment]
@ccksfh same, any solution?

**Comment by Javimtib92** [comment]
I get the same as duration sometimes, but not always. I cannot figure out in what scenarios does reproduce. The value is -9223372036854776

**Comment by morneluckybeard** [comment]
Also getting this value -9223372036854776 at random for android only.

**Comment by Javimtib92** [comment]
I found out that this Long corresponds to Android ExoPlayer 2 TIME_UNSET constant.

public static final long TIME_UNSET = Long.MIN_VALUE + 1;

For me this issue happens only when playing audio files. I tracked this issue a little bit googling by this keywords "audio, TIME_UNSET exoplayer" and I found that it might be because we are reproducing .aac audios in our player and Exoplayer cannot get the duration of those.

A way to solve this would be to convert audios to mp3. In my case this are recorded audios that I uploaded to our server using react-native-audio package with the encoding to .aac and I check that package and Android or iOS doesn't support recording audio in mp3 directly, so the solution for us will be process the uploaded files in the server and send a websocket notification when files are done processing and we can fetch them.

I hope this helps someone, for someone without experience in native code it was a headache to find why this was happening.

Please if you find any solution simpler than this or in react-native-video package itself let us know. 

Thanks

**Comment by adgao** [comment]
I'm getting this issue on Android 13 with local mp3 audio files. The duration from onLoad is always -9223372036854776.
Duration is correct on iOS. Duration is correct on both Android and iOS with mp4 video files.

react-native 0.69.4
react-native-video 5.2.1

**Comment by rohit9625** [comment]
I'm also facing the exact same issue and get the exact number for duration for a specific video. Did anyone find a fix for this?

**Comment by sayan-avantai** [comment]
still the issue is there. 
`"react-native-video": "^6.16.1",`
