### ISSUE TITLE
Unable to load videos from Android Assets folder

### ISSUE THREAD

**Issue by Darren-Ivey** [TheWidlarzGroup/react-native-video#1826]
# Bug

I am unable to reference videos in the Android assets folder. 
I am passing through a uri object using the asset protocol i.e:

{ uri: asset:/videos/2019-06/TEST_VIDEO.mp4 }

There is no error, but the video is not loaded. 

## Platform
Android ExoPlayer

## Environment info
Using version 5.0.2 react-native-video.
Using version 0.61.1 of react-native.

React native info output:
There is no error.

Library version: 5.0.2

## Steps To Reproduce

1. Reference a mp4 file from the android assets folder.
2. Build app
3. View video

## Expected behaviour

1. The video loads and can be played.

**Comment by avet-m** [comment]
@Darren-Ivey did you solve the problem?)

**Comment by TFlexSoom** [comment]
I am looking into this myself. I know that the regex will fail within the video.js file.

**Comment by TFlexSoom** [comment]
Ok so the regex should fail... sort of... the code expects assets or resources placed in the drawable and raw directories to be named verbatim. Currently I am looking into the code's form of getting the identifiers. This would be line 322 and 328 (I am using 328 currently through the raw resource directory) within [ReactVideoView.java](https://github.com/react-native-community/react-native-video/blob/master/android/src/main/java/com/brentvatne/react/ReactVideoView.java).

The identifier returned is always erroneous, throwing a silent error and causing the eventless black screen.

Current workaround is to replace line 334 with a static format. `R.raw.name_of_asset` or `R.drawable.name_of_asset` within the code.

`setRawData(R.drawable.video.mp4)`

For example.

-- UPDATE --

If you have the asset in the raw or drawable resource directories within Android Studio, then you simply need to have the path from the raw directory to that file without the file ending in the source prop of the Video component.
`source = {{uri: "name_of_video"}}`
This will allow for a correct identifier to be returned.

It would be nice to add a case within the function setSrc that would detect the prefix "asset:/" rather than just "content://" on a successful regex within Video.js. This case could then remove the file ending and "asset:/" prefix for correct behavior according to React Native Documentation.

**Comment by HessiPard** [comment]
> # Bug
> I am unable to reference videos in the Android assets folder.
> I am passing through a uri object using the asset protocol i.e:
> 
> { uri: asset:/videos/2019-06/TEST_VIDEO.mp4 }
> 
> There is no error, but the video is not loaded.
> 
> ## Platform
> Android ExoPlayer
> 
> ## Environment info
> Using version 5.0.2 react-native-video.
> Using version 0.61.1 of react-native.
> 
> React native info output:
> There is no error.
> 
> Library version: 5.0.2
> 
> ## Steps To Reproduce
> 1. Reference a mp4 file from the android assets folder.
> 2. Build app
> 3. View video
> 
> ## Expected behaviour
> 1. The video loads and can be played.

Just Read this [comment-157237650](https://github.com/react-native-community/react-native-video/pull/103#issuecomment-157237650)
You should put videos in raw folder

**Comment by Darren-Ivey** [comment]
@TFlexSoom @HessiPard excellent thank you both! I will try adding the videos to the raw folder.
