### ISSUE TITLE
Controls property set to true causes content to jump around on load

### ISSUE THREAD

**Issue by joshallison** [TheWidlarzGroup/react-native-video#1847]
# Bug
When controls property is set to true, causes content around <Video controls={true}/> to jump around on load. If controls is set to false content around <Video /> does not jump around.

## Platform
IOS 13.2

Which player are you experiencing the problem on:
* iOS

## Environment info

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 61.57 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27
      Build Tools: 26.0.2, 27.0.3
      System Images: android-26 | Google APIs Intel x86 Atom
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.9.0 => 2.9.0 
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7

Library version: 5.0.2
## Steps To Reproduce
Reproduce by creating <Video controls={true} /> element.

## Expected behaviour
Other elements shouldn't jump around when video element loads with controls UI.

## Reproducible sample code
<Video controls={true} />

## Video sample
![jump](https://user-images.githubusercontent.com/11746893/70969183-657a2e00-20ef-11ea-8e62-96026aa5f3dd.gif)

**Comment by henrymoulton** [comment]
@joshallison I'm seeing this too, any solution?

**Comment by joshallison** [comment]
> @joshallison I'm seeing this too, any solution?
Hey, I couldn't find a solution so just disabled controls and created my own UI and used API to mute, pause etc.

**Comment by joshallison** [comment]
> @joshallison I'm seeing this too, any solution?

Hey, I couldn't find a solution so just disabled controls and created my own UI and used API to mute, pause etc.

**Comment by xstable** [comment]
Not exactly the same issue, but might be of **the same cause**:

I figured out, that enabling "controls" at IOS is the cause of a strange Issue.
I open the Video-Component in an own screen.
If I enable controls, **the late loading of controls cause the issue**, that the Screen will not shown in right way. 
Most of the time, you got an gap at the right-side, because the whole Screen (it's a StackNavigator-Screen from react-navigation) is moved to the left.

If I deactivate "controls" and use an own set of Media-Controler (e.g react-native-media-controls), this Issue dosen't appear.

I think the issue is, that the Controls does "oversize" the Screen-Container on loading time, before it adjust itself into the Video-Component-Width. After this resizing, no state-update is made... so no rerendering for the screen. 

here a Picture to show what the issue is: 
![449F78CB-08ED-45DD-A0A7-8D7208B013B0_1_105_c](https://user-images.githubusercontent.com/1778068/79547388-1c81b880-8094-11ea-9685-e08bcba1c270.jpeg)

**Comment by softmastx** [comment]
Same here.
Although setting controls prop to true after onReadyForDisplay the video still jumping!!!

`onReadyForDisplay={() => {
            this.setState({controlDisplay: true});
  }}`

Any solution please.
