### ISSUE TITLE
component 'rctvideo' re-registered bubbling event 'topvideoloadstart' as a direct event

### ISSUE THREAD

**Issue by joshuadiezmo** [TheWidlarzGroup/react-native-video#1850]
### Current behavior
error on start the app.

### Reproduction steps
install `react-native-video` install `react-native-vlcplayer` open the app

### Expected behavior
play video

### Platform
Which player are you experiencing the problem on:
* iOS

![Screen Shot 2019-12-18 at 12 34 22 AM](https://user-images.githubusercontent.com/8644115/71015422-8746d580-212e-11ea-9b72-62b3678a7322.png)

**Comment by RandunuK** [comment]
I've got the same issue after configuring **[react-native-yz-vlcplayer](https://github.com/xuyuanzhou/react-native-yz-vlcplayer)**. Have you found any solution?

**Comment by 1280103995** [comment]
same issue, only install react-native-video, version 5.0.2

**Comment by tanujttn** [comment]
Same issue, after configuring "react-native-vlc-media-player".

**Comment by himanshuf35** [comment]
The problem is that library react-native-video is using "RCTDirectEventBlock" for event blocking and react-native-vlc-media-player is using "RCTBubblingEventBlock" which cause conflict, setting same blocking type for both libraries solves the problem. 

In react-native-vlc-media-player/ios/RCTVLCPlayer/RCTVLCPlayerManager.m 

RCT_EXPORT_VIEW_PROPERTY(onVideoProgress, RCTBubblingEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoPaused, RCTBubblingEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoStopped, RCTBubblingEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoBuffering, RCTBubblingEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoPlaying, RCTBubblingEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoEnded, RCTBubblingEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoError, RCTBubblingEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoOpen, RCTBubblingEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoLoadStart, RCTBubblingEventBlock);

Change this to 

RCT_EXPORT_VIEW_PROPERTY(onVideoProgress, RCTDirectEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoPaused, RCTDirectEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoStopped, RCTDirectEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoBuffering, RCTDirectEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoPlaying, RCTDirectEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoEnded, RCTDirectEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoError, RCTDirectEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoOpen, RCTDirectEventBlock);
RCT_EXPORT_VIEW_PROPERTY(onVideoLoadStart, RCTDirectEventBlock);

This is a temporary solution since we are making changes in node_modules.

For a permanent solution either fork any of the two repo and make changes or One of those libraries have to implement this
