### ISSUE TITLE
onBuffer not working

### ISSUE THREAD

**Issue by santanu07** [TheWidlarzGroup/react-native-video#1872]
I just faced that of onBuffer doesn't work
please give me solution if any

**Comment by bigbadfatman** [comment]
[This issue](https://github.com/react-native-community/react-native-video/issues/1920) might help you.

**Comment by NeerajaaG** [comment]
same issue

**Comment by sjonchhe** [comment]
same issue

**Comment by dnizfor** [comment]
+1

**Comment by freeboub** [comment]
Please use exoplayer implementation. Not supported on mediaplayer

**Comment by yfunk** [comment]
> Please use exoplayer implementation. Not supported on mediaplayer

I feel like ExoPlayer should become the default implementation for Android with the next major release. 

Right a lot of people are probably still running the old MediaPlayer implementation without even knowing, since the instructions on how to enable ExoPlayer are hidden pretty well in the `README`. Besides the old implementation having seemingly no benefits over the new one, this also leads to multiple issues like this.
