### ISSUE TITLE
Unable to pause the media on ios

### ISSUE THREAD

**Issue by knifedge** [TheWidlarzGroup/react-native-video#1881]
Video doesn't pause on updating the state using a toggle button.

## Platform
OS: ios
OS Version : 13+
Library version:: 5.0+
RN version: 0.60+

**Comment by AurangzaibRamzan** [comment]
+1

**Comment by dblackker** [comment]
Similar... video doesn't respect pause prop after interacting with controls to pause/play.

### Repro steps
1. Video starts playing because pause={false}
2. Pause the video using the controls
3. Play the video using the controls
4. Set pause={true}

### Excepted behavior
Video pauses.

### Actual behavior
Video continues to play.

### Platform
OS: iOS 13.6
Device: iPhone 11 Simulator
React Native version: 0.61.5
Library version: 4.4.5 and 5.1.0-alpha5
