### ISSUE TITLE
Local Video is not playing in iphone in released mode

### ISSUE THREAD

**Issue by Saad9624** [TheWidlarzGroup/react-native-video#1991]
# Bug
Not getting any errors from the callbacks but the video is not playing for the first time in ios 

## Platform
ios

Which player are you experiencing the problem on:
* iOS

## Environment info
react-native 0.62.1
react-native-video:4.4.5

Library version: 4.4.5

**Comment by AtharZaib** [comment]
Same here. The problem occurs when the app loads for the very first time in debug mode, the black screen occurs and after reload the video displays. Any solution ?

**Comment by jensellfors** [comment]
Would need more details to be able to debug this. What platform is this? iOS/Android? Exo/MP? Can you share some code?

**Comment by AtharZaib** [comment]
Using RN 0.62.1 first now downgraded to 0.60.6 and React native Video version 5.0.2 as per documentation. Using Xcode 10.3 for ios,

The problem lies when the app loads for the very first time it shows no color just empty space and other components render as well. As the video component is the parent and all components are child of it so child components are rendering good but it is conflicting. On reloading the app, the video displays means there is no linking / source issue of the video in the app. 
The onLoad and onReady functions are returning the objects which displays the information of the video exactly same but the title is " " on the first time. 
Also tried forceupdate for re-rendering but fails.
Attaching the Video component

<View style={{ flex: 1, backgroundColor: 'black' }}>
        <Video
          onLoad={this.onLoad}
          progressUpdateInterval={1000}
          opacity={0.6}
          onLoadStart={this.onLoadStart}
          source={require('./../../../assets/video/final.mp4')}
          //source={require('./../../../assets/video/Footboys.mp4')}
          //source={{uri:'src_assets_video_footboys'}}
          // source={{  uri: 'final_videoo' }}
          muted={true}
          repeat={true}
          resizeMode={"cover"}
          rate={1.0}
          ignoreSilentSwitch={"obey"}               // Callback when remote video is buffering
          onError={(err) => this.videoError(err)}               // Callback when video cannot be loaded
          style={styles.backgroundVideo} />

        <Animated.View style={{ opacity: fadeAnim, flex: 1 }}>
        

        {this.renderComponent()}


            {/* <KeyboardAvoidingView
              behavior={'position'}
              keyboardVerticalOffset={keyboardVerticalOffset}
              style={{ flex: 1 }}
              contentContainerStyle={{ flex: 1 }}

            >
            
            </KeyboardAvoidingView> */}

            
          
        </Animated.View>
      </View>



this.renderComponents contains all the children components that are rendering perfectly.

**Comment by AtharZaib** [comment]
Also there is no error regarding why the video is not displayed for the very first time so it's causing more difficulties

**Comment by barakoles** [comment]
Happening here too on iphone 5

**Comment by jensellfors** [comment]
Could be that you're loading the video over the bridge. Can you try adding it to your native code ie adding it to Xcode. Eg add local.mp4 and then set `source={{ uri: 'local', type: 'mp4' }}`
