### ISSUE TITLE
How can I get a state that video stopped and starts loading?

### ISSUE THREAD

**Issue by Sheleya** [TheWidlarzGroup/react-native-video#2062]
I have to detect the event when the video starts to loading after start. I mean I successfully started playing the video, but it could stop due to bad internet connection. How can I handle this case?

**Comment by davidac0** [comment]
Also interested in this.

**Comment by NagashreeMedaMN** [comment]
+1

**Comment by guilhermefmt** [comment]
> I have to detect the event when the video starts to loading after start. I mean I successfully started playing the video, but it could stop due to bad internet connection. How can I handle this case?

The method **onLoadStart** doesn't fire after first load and neither **onBuffer**. I did a few tests with the **onProgress** method and when the video is loading after the first loading **onProgress** is called but the property **currentTime** doesn't change, so as a workaround I stored the **currentTime** into a variable called **progress** and in every event of **onProgress** I check if the progress is equal to the **currentTime**, if so I set the loading to be true otherwise I set it to false.

It works but I think this shouldn't be the right way to do it, the onLoadStart should fire whenever the video is loading.

**Comment by enentyour** [comment]
> +1

**Comment by tom-krusch** [comment]
+1

**Comment by HGGshiwo** [comment]
> > I have to detect the event when the video starts to loading after start. I mean I successfully started playing the video, but it could stop due to bad internet connection. How can I handle this case?
> 
> The method **onLoadStart** doesn't fire after first load and neither **onBuffer**. I did a few tests with the **onProgress** method and when the video is loading after the first loading **onProgress** is called but the property **currentTime** doesn't change, so as a workaround I stored the **currentTime** into a variable called **progress** and in every event of **onProgress** I check if the progress is equal to the **currentTime**, if so I set the loading to be true otherwise I set it to false.
> 
> It works but I think this shouldn't be the right way to do it, the onLoadStart should fire whenever the video is loading.

I find the onProgress not called when loading after first load - play,  it is called only when the video is playing. Can you tell me any solution pls?
