### ISSUE TITLE
Play/Pause does not work in 5.1.0-alpha8

### ISSUE THREAD

**Issue by JoaoCEAlmeida** [TheWidlarzGroup/react-native-video#2130]
# Bug
Hi everyone,
I install the latest version 5.1.0-alpha8 of react-native-video in a project, and I noticed when I pause the video and the press play the video does not play. If I repeat this process the video starts playing on the second try. I also try to use the master branch to test it and faced the same problem.

Could not test it in 5.1.0-alpha7 because I could not install it.

In version 5.0.2, this problem does not occur. But this version does not support DRM, which is a feature that I need to support.

## Platform
Android

## Player 
Android Exoplayer 

## Environment info
"react-native-video": "5.1.0-alpha8"
"react-native": "0.61.2",

**Comment by sharifhh** [comment]
+1

**Comment by itsmefreitas** [comment]
+1

**Comment by DeepRolling** [comment]
+1

**Comment by JoaoCEAlmeida** [comment]
@CHaNGeTe Can you check this?

**Comment by JoaoCEAlmeida** [comment]
in file ReactExoplayerView.java if we delete the  pausePlayback(); function this problem does not exist. But I'm not sure why this function is called here. 

![image](https://user-images.githubusercontent.com/9196047/96139645-f4fe9200-0ef6-11eb-94a3-3c735fd1abbb.png)

**Comment by cstranex** [comment]
We are having a similar issue. Pausing a locally stored mp4 will stop playback and it won't resume even after repeated unpausing and pausing.

Tested with 5.1.0-alpha4 and it seems like playback worked correctly. 5.1.0-alpha4 includes the above change. Ours may be a separate issue to the OP though.

**Comment by reinaldonetof** [comment]
@JoaoCEAlmeida 
> in file ReactExoplayerView.java if we delete the pausePlayback(); function this problem does not exist. But I'm not sure why this function is called here.
> 

Hello, Joao. Yeah, the error occurred for me, because I'm working with DASH and HLS files and need the DRM too. So, after I deleted this function worked right. But I understand that this is a workaround 👍

**Comment by ChrisCodeCole** [comment]
+1

Device: Amazon Fire TV Stick 4K
OS: First OS 6.2.7.6

I see the same issue. Not sure how the audio focus works on Android, but the audio focus state goes from **loss** to **gain** AFTER every **unpause** state. And it ONLY happens on the first video playback. And since we call pausePlayback() in the loss state, it never actually resumes.

I put logs in the startPlayback() and pausePlayback() functions, as well as audio state change listeners...

**1st Video Playback**
![image](https://user-images.githubusercontent.com/30168850/98398140-7ba61b00-202e-11eb-8d58-280538db472f.png)

**2nd Video Playback**
![image](https://user-images.githubusercontent.com/30168850/98398255-ab552300-202e-11eb-9e04-ec0722c61b52.png)
