### ISSUE TITLE
Muted prop on Android does not working

### ISSUE THREAD

**Issue by Kreshimir** [TheWidlarzGroup/react-native-video#2148]
muted={true} does not work on Android, while on IOS works as expected.
Any idea, solutions?

**Comment by zhjgstc** [comment]
check your settings.gradle file, find react-native-video if use android-exoplayer try to change android MediaPlayer. that may works.

###  find this
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

### change to this 
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')

**Comment by Curbe8** [comment]
I have the same problem!

I read in another post that this was fixed in the latest versions, but with the latest versions the plugin does not work on android for me.

Lately this idea has crossed my mind and it works in my case:

```JavaScript
<Video
    paused={bPaused == undefined ? true : bPaused}
    muted={this.state.muted}
    repeat={true}
    controls={false}
    disableFocus={false}
    key={'video_' + nId}
    resizeMode={'cover'}
    source={{ uri: sUrl, cache: { tamaño: 50, expiresIn: 3600 } }}
    style={GlobalStyles.fullImage}
    ref={(ref) => {
        this.state.player = ref
    }}
    onLoadStart={async () => {
        await this.setState({
            muted: !this.state.muted
        });
        await this.setState({
            muted: !this.state.muted
        });
    }}
/>
```

In a nutshell, I wait for it to load the component with the video and change the state variable, I do it 2 times so that the variable does not mutate its value.

I hope it will be of help to anyone looking for some kind of help on this topic.

**Comment by ToshKoevoets** [comment]
This is still an issue

**Comment by freeboub** [comment]
@ToshKoevoets can you try on last V6.0.0 beta please ?

**Comment by ToshKoevoets** [comment]
On v5, as far as I see v6 is not stable. yet?

Anyway as far as I see is setting volume to 0.0 works.

The above user suggests it's an exoplayer issue, although most of us would
prefer expoplayer.

Op di 16 apr 2024 om 12:40 schreef Olivier Bouillet <
***@***.***>:
