### ISSUE TITLE
Volume prop ignored on android (ExoPlayer)

### ISSUE THREAD

**Issue by Giosanu** [TheWidlarzGroup/react-native-video#2153]
# volume prop ignored on android

I want to control the video volume from admin via API, but the volume prop on android (I am using the exoPlayer) is ignored.

react-native-video version: 5.0.2 (I tried upgrading it to latest version (5.1 alpha) but it didn't solve my problem)
react-native version: 0.63.2

## Platform
 - Android
Which player are you experiencing the problem on:

* Android ExoPlayer

## Environment info

React native info output:

System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 18.74 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.0.2

**Comment by sayinala** [comment]
+1

@Giosanu did you find any workaround for this?

**Comment by Giosanu** [comment]
@sayinala yes, I tied the volume value to the component's state, and on componentDidMount() set the state to the given prop volume:

`
   componentDidMount() {
   this.setState({
         volumeValue: this.props.volumeValue
      })
   }
`

`
   render () {
      return <BaseVideo 
               volume={this.state.volumeValue}
         />
   }
`

**Comment by sayinala** [comment]
Thank you @Giosanu, I am giving data to video component from state only but still the initial value while rendering is not considered.

**Comment by Giosanu** [comment]
@sayinala yes.. the initial value is ignored, unless its tied to a variable in the components state.. if you setState({volume: initialValue}) in componentDidMount, still doesn't work? or are you using react hooks?

**Comment by sayinala** [comment]
@Giosanu yes it didn't work after using it from state also, I am using the react hooks.

**Comment by NishargShah** [comment]
Any solution??

**Comment by istvan-szilagyi** [comment]
I had a similar problem... I have custom controls for the player, which contains a slider to adjust the volume of the movie. The value of the slider was stored in the component's state, so it worked really well (even with useState hook). 
The thing is that I have TabNavigation in my app, and if I adjusted the player volume and switched tab then back the volume was again max. Really annoying, so I started to dig what the problem is and finally found it out...

So there is this function, which get's called anytime let's say the video gains focus (in **ReactExoplayerView.java**)
```
@Override
protected void onAttachedToWindow() {
    super.onAttachedToWindow();
    initializePlayer();
}
```

That **initializePlayer** function contains a handler (which I don't really understand why, but it doesn't really matter) either way in the end this results in calling the **applyModifiersFunction**

```
private void applyModifiers() {
    setRepeatModifier(repeat);
    setMutedModifier(muted);
}
```

So this **setMutedModifier** get's called which messes up the volume...
```
public void setMutedModifier(boolean muted) {
    this.muted = muted;
    audioVolume = muted ? 0.f : 1.f;
    if (player != null) {
        player.setVolume(audioVolume);
    }
}
```

Having my muted flag on false and my volume value on anything, when the player appears (or reappears) on the screen the volume is set back to 1. This function should not edit the **audioVolume** attribute, it should just check if muted is true set player volume to 0, like this:

```
public void setMutedModifier(boolean muted) {
    this.muted = muted;
    if (player != null) {
        player.setVolume(muted ? 0.f : audioVolume);
    }
}
```

And now that I understand, I can explain why some of the solutions mentioned above were working, and some of them not.
In a functional component the default value of the state was set before the onAttachedToWindow was called, so that resulted as it was ignored, literally it wasn't ignored only it was overwritten.
The other case with class component, and setting the state from componentDidMount worked, because all this happened after onAttachedToWindow was called.
