### ISSUE TITLE
Android ui sometime hang

### ISSUE THREAD

**Issue by InnerPeace080** [TheWidlarzGroup/react-native-video#222]
Some time react native video loading data error or slow , it block ui and app seem hang . 

How can i run video on other thread (not async task) . I don't want my app hang :(

**Comment by ghost** [comment]
@InnerPeace080 Any luck with this? Could you provide some information about the environment or stream URL you were using for testing?

**Comment by InnerPeace080** [comment]
i resolve this problem by run prepair and release function in other thread 

like this:

```
@Override
    protected void onDetachedFromWindow() {
        mVideoValid = false;
        mMediaPlayerValid = false;
        _activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);



        class Release implements Runnable {
            @Override
            public void run() {
                try {
                    mMediaPlayer.release();
                    mMediaPlayer = null;
                }
                catch(Exception ex){
                    Log.e("ReactVideoView","onDetachedFromWindow err " + ex);
                    ex.printStackTrace();
                }

            }
        }

        new Thread(new Release()).start();

        super.onDetachedFromWindow();
    }
```

**Comment by ghost** [comment]
@InnerPeace080 glad you got it working. That's great! Would you say this issue can be closed now?

**Comment by mattapperson** [comment]
@InnerPeace080 hmmm so there is perhaps a threading issue? I am not the best android dev, but it seems to me that maybe we should implement this into the module itself?

**Comment by rayshih** [comment]
We are encountering "hang" issue right now.
And I have traced down this happened while call `mMediaPlayer.reset()`
Which will spend almost 1 second on UI Thread on my device.

However, recreating a completely new media player won't cause this problem. So my current solution is removing all code that will call `reset`. like remove this:

https://github.com/react-native-community/react-native-video/blob/master/android/src/main/java/com/brentvatne/react/ReactVideoView.java#L193

Also, I removed the `onAttachWindow` callback, and I don't observe any difference.

Since I do this on my forked repo, and which already diverged from this repo, I'll create PR later, if nobody haven't. (I'm not sure when I'll have time)

some ref:
http://stackoverflow.com/questions/21631998/android-mediaplayer-reset-freezes-ui

**Comment by ghost** [comment]
Reopening since this still seems to be an issue. @rayshih Thanks for the additional info. If there's any code you can provide from your fork perhaps others would find it of value even if only a quick code dump as opposed to a PR.

**Comment by rayshih** [comment]
https://github.com/rayshih/react-native-video/commit/7d89f4b1c8e0fa23ce1cfb31c3f9821fb58479ac

My solution is instead of use `reset` I create a new `MediaPlayer` every time I need it.
The solution of @InnerPeace080 is every time when it needs to `reset` create a thread for that.

**Comment by codesinghanoop** [comment]
Declare 

> prepareAsync(this); 

at the end of setsrc function.

**Comment by rayshih** [comment]
This problem still exists in version 1.0.0

**Comment by ghost** [comment]
@rayshih it would be more useful if you provided information such as your version of React and Node JS, when commenting.

**Comment by rayshih** [comment]
```
   react: 16.0.0-alpha.6,
   react-native: 0.44.0,
```

Also, my device is: LG G4, Android 6.0

Hope this would help

**Comment by coryMcan** [comment]
ok - our company has looked into this and we've found the issue. It hangs on the .reset() function, and the reset function is called on the same thread as the UI.

The solutions above are not working due to the fact that mMediaPlayer is accessed from 2 different threads, causing lock ups and crashes. What we did is move all the actions in relation to mMediaPlayer to a separate  Handler, which seems like somebody already started to do, but never finished. So to be exact, here is our class (ReactVideoView.java)

https://gist.github.com/coryMcan/a41aaebfe7fe52c10ef2547725eaef5d

Here's a step by step:

Remove the .reset() function that is called before initializeMediaPlayerIfNeeded around line 117

Replace the initializeMediaPlayerIfNeeded method with this:

```

    private void initializeMediaPlayerIfNeeded() {

        final ReactVideoView who = this;
        videoControlHandler.post(new Runnable() {
            @Override
            public void run() {
                if (mMediaPlayer == null) {
                    mMediaPlayerValid = false;
                    mMediaPlayer = new MediaPlayer();
                    mMediaPlayer.setScreenOnWhilePlaying(true);
                    mMediaPlayer.setOnVideoSizeChangedListener(who);
                    mMediaPlayer.setOnErrorListener(who);
                    mMediaPlayer.setOnPreparedListener(who);
                    mMediaPlayer.setOnBufferingUpdateListener(who);
                    mMediaPlayer.setOnCompletionListener(who);
                    mMediaPlayer.setOnInfoListener(who);
                }
            }
        });

    }
```


Replace cleanupMediaPlayerResources with this:

```
public void cleanupMediaPlayerResources() {
        if ( mediaController != null ) {
            mediaController.hide();
        }
        videoControlHandler.post(new Runnable() {
            @Override
            public void run() {
                if ( mMediaPlayer != null ) {

                    mMediaPlayerValid = false;
              
                    mMediaPlayer.release();
                }
            }
        });

    }
```


onDetachedFromWindow:

```
@Override
    protected void onDetachedFromWindow() {

        videoControlHandler.post(new Runnable() {
            @Override
            public void run() {
                if(mMediaPlayer != null) {
             
                    mMediaPlayer.reset();

                }
            }
        });
        mMediaPlayerValid = false;
        super.onDetachedFromWindow();
    }
```

**Comment by coryMcan** [comment]
As an extra comment to this - due to the handler being on a separate thread, the onEnd event is closed already before the mMediaPlayer thread gets to it, so the onEnd event is never called. We've temporarily solved this in a hacky way by checking for the progress to be >= 1. Hope that helps anyone  ¯\_(ツ)_/¯
