### ISSUE TITLE
selectedVideoTrack support for iOS platform

### ISSUE THREAD

**Issue by arjunnikolaev** [TheWidlarzGroup/react-native-video#2306]
# Feature Request

Support switching selectedVideoTrack on iOS

## Why it is needed

Right now selectedVideoTrack prop works on Android exoplayer, resolution change is smooth, but iOS completely ignores this prop (video quality stays the same). So in iOS you have to change video source, then seek to the place you left off, which is very slow and not user friendly. Would be great to have this feature on iOS as well

**Comment by olgunkaya** [comment]
I think iOS AV Player does not support this. I read too much about it. That's why maxBitrate and minBitrate are available to maintain the user experience. I believe, Apple thought that, If we expose this, end user will select a great value even greater than user's network connection's bandwith. So the freezes will start and nothing to do after this point. That's why possible apple wanted to not to expose the videoTracks but the bandwith limits.

**Comment by siddharthkr** [comment]
> # Feature Request
> Support switching selectedVideoTrack on iOS
> 
> ## Why it is needed
> Right now selectedVideoTrack prop works on Android exoplayer, resolution change is smooth, but iOS completely ignores this prop (video quality stays the same). So in iOS you have to change video source, then seek to the place you left off, which is very slow and not user friendly. Would be great to have this feature on iOS as well

Hi can you please show me your code for react-native-video on android because in my case selectedVideoTrack Prop is not working on android too.

**Comment by tushar-singhal** [comment]
@arjunnikolaev @olgunkaya thanks guys, how do you get the available qualities on iOS? its working for Android, onload callback is giving me `videoTracks` but this is not available on iOS.

**Comment by olgunkaya** [comment]
Well it’s not possible to get bitrates in av player. There is no such api for react native video. So that you need to set maxbitrate to your enumerated values. Say it is, 1024kbps. İos av player will try to go as high as you set the bar. Tbh, this seems to be more user friendly. Cuz if you set your bitrate to something else that your network not supports then you will have a bad user experience on the device. Which eventually will lead you think negative about the device itself. 

One possible solution is to publish all of your content with same list of available bitrates and enumerate then manually and show to user. Other option is to keep the available bitrates per content in your metadata/cms services and feed the client with api. This will create a similar behaviour of android devices.

**Comment by siddharthkr** [comment]
Hey guys @tushar-singhal @olgunkaya,

I have a video on AWS s3 storage bucket, video dimensions are 1920*1080.
But when I play that video on my ANDROID device onLoad ->videoTracks prop returns just the natural size of video (1920 * 1080).
What I was expecting is that onLoad ->videoTracks should return multiple dimensions like : (480 * 360, 1080 * 720, 1920 * 1080).

Can you please tell me, what i am doing wrong ?
Thanks 🙂

**Comment by olgunkaya** [comment]
Well, tbh I don't have experience with AWS. not sure what's your playback url but it must be a proper manifest with proper resolution definitions in it.

**Comment by siddharthkr** [comment]
Thanks for replying. 🙂

Yes, actually I am trying to figure out where and how can I define "proper manifest with proper resolution definitions" for my video. Can you please tell me about it .
My AWS video URL = https://testing-video-007.s3.ap-south-1.amazonaws.com/ElephantsDream.mp4 
Dimensions of above video are 1280 * 720.

I am facing really hard time to find solution for this. 😥

**Comment by olgunkaya** [comment]
First, you are doing progressive streaming. (Still not sure if aws s3 storage does it by default for a video file, but 100% sure it's not adaptive)

Before jumping into the wild streaming world, I recommend you to understand what's happening on your side. 
Read this first : https://support.hughesnet.com/en/faq/internet/progressive-and-adaptive-streaming

Then for aws adaptive streaming, go with this. 
For adaptive video streaming
https://www.tothenew.com/blog/adaptive-bitrate-streaming-using-aws/ check this page. googled and find this. Some might of change since the article has been published. 


hope these can help you. I can not do more than this.

**Comment by siddharthkr** [comment]
> First, you are doing progressive streaming. (Still not sure if aws s3 storage does it by default for a video file, but 100% sure it's not adaptive)
> 
> Before jumping into the wild streaming world, I recommend you to understand what's happening on your side. Read this first : https://support.hughesnet.com/en/faq/internet/progressive-and-adaptive-streaming
> 
> Then for aws adaptive streaming, go with this. For adaptive video streaming https://www.tothenew.com/blog/adaptive-bitrate-streaming-using-aws/ check this page. googled and find this. Some might of change since the article has been published.
> 
> hope these can help you. I can not do more than this.

I really appreciate your help. Thanks a lot. 🙂

**Comment by tushar-singhal** [comment]
> Well it’s not possible to get bitrates in av player. There is no such api for react native video. So that you need to set maxbitrate to your enumerated values. Say it is, 1024kbps. İos av player will try to go as high as you set the bar. Tbh, this seems to be more user friendly. Cuz if you set your bitrate to something else that your network not supports then you will have a bad user experience on the device. Which eventually will lead you think negative about the device itself.
> 
> One possible solution is to publish all of your content with same list of available bitrates and enumerate then manually and show to user. Other option is to keep the available bitrates per content in your metadata/cms services and feed the client with api. This will create a similar behaviour of android devices.

Thanks @olgunkaya for your reply.
So if I understand you correctly, you are saying that I should hardcode the video qualities in the app and there is no way to get available video qualites in iOS? Please correct me if I am wrong.

Now the prob for me is that I get video content from multiple different partners and its not possible for me to have same bitrates. Also there is some old content. 

So do think there is some workaround with can help here?

**Comment by tushar-singhal** [comment]
> Hey guys @tushar-singhal @olgunkaya,
> 
> I have a video on AWS s3 storage bucket, video dimensions are 1920*1080. But when I play that video on my ANDROID device onLoad ->videoTracks prop returns just the natural size of video (1920 * 1080). What I was expecting is that onLoad ->videoTracks should return multiple dimensions like : (480 * 360, 1080 * 720, 1920 * 1080).
> 
> Can you please tell me, what i am doing wrong ? Thanks 🙂

No clue about AWS mate, but I am using HLS streams and I am getting different `videoTracks` in `onLoad` callback atleast on android

**Comment by olgunkaya** [comment]
I am fully lost on your case. But for ios you will not be able to get the tracks, cuz ios av player does not provide it. You have to implement your way of mimicing the behavior. either static enums or api to get available bitrates via an API. this is your developer skills comes into the picture. 

good luck.

**Comment by skfaisal93** [comment]
I am not even getting videoTracks in Android. @tushar-singhal can you please share your Video component so that I can check.
