### ISSUE TITLE
Laggy/inconsistent android player controls

### ISSUE THREAD

**Issue by macsj200** [TheWidlarzGroup/react-native-video#2495]
I'm encountering some strange behavior when attempting to open/dismiss the video player controls on android. I'm not using any "external" control libraries, I'm just relying on the existing `controls={true}` prop.

Specifically, there seems to be some lag/inconsistency associated with opening the player controls when I tap the video. I've found that tapping the bottom of the video seems to bring up the controls somewhat reliably but it's still not 100%.

Has anybody else encountered this behavior? Does anybody have any suggestions about what to try?

I'm using a `Fire HD 10 (11th Generation)` on `Fire OS 7.3.2.1`. I have also encountered this issue with the Pixel emulator and other android devices.

I'm using `react-native-video` `5.1.1`.

This is how I'm rendering the component:
```
      <Video
        ...
        controls={controls}
      />
```

Additional context:

This player is rendered as a child of a `<TouchableOpacity />` component. I thought that component might be "swallowing" some of the touch input events. I put an `onPress` listener on the parent component and it **does not** seem like that component's listener is being fired when I press on the video player component.

**Comment by ekremay** [comment]
@macsj200
It's a bit of an annoying solution, but I wanted to share it in case it might work for you.
Maybe you can render your own video controls instead of the default controls. If the problem persists in your own controls too, you can adapt your solution accordingly. ( `<TouchableOpacity />` part )
1) Disable default video controls.
2) Build your own video controls. For testing, only play and pause could be enough.
2) Show and hide them with conditional rendering
