### ISSUE TITLE
Cache HLS(.m3u8) video

### ISSUE THREAD

**Issue by Kuljeet-123** [TheWidlarzGroup/react-native-video#2537]
I want to make the functionality just like the reels in "Instagram".

For that I have flatlist of HLS(.m3u8) videos now I was thinking to cache these videos so that it can preload easily whenever I swipe down to the next video.

Or is there any other way i can implement this reels feature. I have implemented it using flatlist and react-native-video but while swiping down to next video or from one to another video its showing loading. That's why I want to cache these videos so that it can be pre-loaded just like in instagram.

**Comment by gustavolsilvano** [comment]
I'm facing the same problem. What I did (it's not 100%, but it kind of work on android) is the following:

1)  You have to mount the next video in advance. As you are using flatlist, you just need to set the windowSize prop to a number greater than 1;
2) On Android you have to be careful because if you mount a lot of video components, the ExoPlayer will return an exception. I'm mounting just the next video for example;
3) I'm downloading the video (works like a cache system) using react-native-fs. So I download and link the video object with the path to local storage.

These was the steps that I followed. Of course that you have a lot of trouble in the midst, but if you need any help, just ask me.

**Comment by HirenTariwala** [comment]
@gustavolsilvano as you are saying that will download 2 videos current and next so I guess that will take much more loading time the current situation for 1st video to load and start am I right correct me if I am wrong.

**Comment by gustavolsilvano** [comment]
What I do is the, if the current video is not already cached (downloaded), I'll stream it. If it's already downloaded, that just load it from the storage.

This way, when I'm streaming one video, the other is downloading. By the time I ended watching the first video, the next will already be available from storage

**Comment by HirenTariwala** [comment]
@gustavolsilvano i've notice that even if we are going to stream instead of download via rn-fetch-fs video will not play until it is not stream all frames

**Comment by gustavolsilvano** [comment]
You will stream using react-native-video and not react-native-fs. The last one will be used only to download videos

**Comment by HirenTariwala** [comment]
@gustavolsilvano yes that's true but when we start streaming using react native video it is waiting long bcoz it is wait get all frames then start do we have any solution likewise @Kuljeet-123  saying start video right after get few frames

**Comment by HirenTariwala** [comment]
@Kuljeet-123 have you found any solution for this?  i am working on same and facing same issue

**Comment by lnxct** [comment]
@hueniverse let us know if this solution is implemented on the latest release.

Thanks

**Comment by hueniverse** [comment]
@lnxct I am no longer involved in the project

**Comment by dhayaljaswantgit** [comment]
Hello, do we have any solution for the same, so far?

**Comment by alexbudin** [comment]
Some insight or a solution on here would be nice.

**Comment by nguyenvanphituoc** [comment]
I have implement cache video with HLS, that suitable with react-native-video: https://github.com/nguyenvanphituoc/react-native-cache-video#readme

**Comment by derynusaputra** [comment]
So far, have you found a solution?
