### ISSUE TITLE
[Android] Video hang and play audio only when the video size is large but not when the video is resized

### ISSUE THREAD

**Issue by zarulrahim** [TheWidlarzGroup/react-native-video#2589]
I'm developing an app that displaying multiple videos in a ScrollView. The problem I'm currently facing is kinda weird. Some of the videos can play accordingly some of it got stucked. But when I resize the stucked video to the smaller size, it can play very well. Do you guys have any ideas what is actually causing this issue? It kinda frustrated since I need to resize the video and sacrifice the quality of he video just to make sure it playable. Thanks!

**Comment by pankajinfowind** [comment]
Hey @zarulrahim , Have you found any solution ?

**Comment by sarevok89** [comment]
I have a similar problem. I display around 30 videos inside a ScrollView. They start playing for a very short time and then start lagging. They all play in a loop and even after the whole video starts playing from the beginning it keeps lagging.

It started about 2 weeks ago and what's weird is that 3 weeks ago everything was perfect and we haven't touched the app ever since. If you find a solution to this, then please share it here, and so will I.
