### ISSUE TITLE
Playing external subtitles with m3u8 link of video

### ISSUE THREAD

**Issue by talhajibrantariq** [TheWidlarzGroup/react-native-video#2590]
# Bug

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by RobertArissen** [comment]
Although your explanation is not very clear, I am currently having the same problem. I would like to play hls m3u8 subtitles

**Comment by talhajibrantariq** [comment]
> 
        selectedTextTrack={{
            type: 'language',
             value: 'en',
           }}
           textTracks={tracks}
 Hi @RobertArissen , i'm talking about these two props of react-native-video. When my source file is in m3u8 format, adding external subtitles from these props hangs the video. But if i use .mp4 video, it works perfectly fine, 
 The question i asked was if i could use these props for m3u8 link for IOS. 
Note: This mechanism is working on android side.

**Comment by iSued** [comment]
this issue is open from #1511.

[CHaNGeTe](https://github.com/CHaNGeTe) commented [on 14 Jun 2019](https://github.com/react-native-video/react-native-video/issues/1511#issuecomment-502225682):

"Currently, as stated on the doc referenced by @alanlanglois, we are not supporting sidecar textracks for HLS (m3u8)
I will leave the issue opened as I think I got an approach to make it work in the future."

This library is under-mantained.
An advice should be: Use dash format for your video. 

@CHaNGeTe

**Comment by talhajibrantariq** [comment]
> Use dash format for your video

Thankyou for the guidance. Will dash format be able to support subtitles on IOS with this package?
Also, how can i convert my m3u8 format to dash in react?
