### ISSUE TITLE
BUILD FAILED after installing react-native-video

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#2616]
hello im getting a bug when trying to install the package, im wondering what im doing wrong?

Working with react-native-cli, only installed the package without anything new

# Bug
> Task :app:mergeDebugAssets FAILED
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.yqritc:android-scalablevideoview:1.0.4

## Platform

Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer
* Windows UWP
* Windows WPF
* Windows

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by jason-vault** [comment]
Assuming you are on a later version of React Native, In `android/build.gradle` you need to add `jcenter()`, in this case best to be explicit and only include what is necessary:

```
...
allprojects {
    repositories {
       ... other repositories
        jcenter() {
            content {
                includeModule("com.yqritc", "android-scalablevideoview")
            }
        }
    }
}
```

**Comment by emil-malmgaard-rasmussen** [comment]
OP hasn't answered, but I had same issue and @jason-vault's suggestion worked 10/10!

**Comment by kosalamoon** [comment]
@jason-vault's solution worked for me too ✅

**Comment by hueniverse** [comment]
@jason-vault Thanks!

**Comment by arsimr16** [comment]
I was able to use `react-native-video 5.2.0` without using jcenter by switching to the Android ExoPlayer.  `android-scalablevideoview` is only used by the Android MediaPlayer which is being removed in version 6.x of react-native-video anyway.

1) Add the following lines to settings.gradle to use the ExoPlayer instead of the MediaPlayer:
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

2) Once I switched to the ExoPlayer, I got errors from `react-native-video/android-exoplayer/build.gradle` about `com.google.android.exoplayer:exoplayer:2.13.2` and `com.google.android.exoplayer:extension-okhttp:2.13.2` not being available.  I made a patch to change both versions to `2.13.3`, and my app built successfully after that.
