### ISSUE TITLE
App crashes on adding react-native-config

### ISSUE THREAD

**Issue by puneetkansal04** [TheWidlarzGroup/react-native-video#2636]

**Comment by IvanSantiagoUk** [comment]
same here

**Comment by hueniverse** [comment]
First - please don't post the same issue over and over in multiple places. This is the 3rd or 4th time I am seeing this issue reported. I can appreciate the urgency you might have in solving it, but this is a community run volunteer effort and if no one replied it is because no one has the time. Adding more noise is only going to make the reply slower.

I am starting a new process for reporting issues which will require submitting a fully working demo showing the problem. This is a complex module with a lot of moving pieces and we need to be able to easily reproduce issues reported. Please fork https://github.com/hueniverse/react-native-video-test and change it to recreate your issue, then provide me with the fork location so that we can look further into it. You can change the code as much as needed to recreate the problem.
