### ISSUE TITLE
Android not works

### ISSUE THREAD

**Issue by expeerd** [TheWidlarzGroup/react-native-video#264]
Video don't play on android (api 19 and 23) with RN 0.29. White screen without any errors. onEnd fires before onLoad.
`<Video rate={1} onEnd={console.log('onEnd)} resizeMode='contain' source={{uri:'http://192.168.1.102:88/videos/1468196289-7205687.mp4'}} onLoad={console.log('onLoad')}/>`

UPD
Magically after posting issue (maybe after restarting simulator) I get error `: { error: { extra: -2147483648, what: 1 } }`

**Comment by arilitan** [comment]
I'm having a similar issue, onLoad and onEnd are being called simultaneously - no video is loading into the player

**Comment by kvnvelasco** [comment]
did you add the package to mainApplicaition?
I had this problem earlier and doing this solved it:

```
  @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new ReactVideoPackage()
      );
    }
```

**Comment by cherniv** [comment]
i also have this error.. did someone solve it?
and i do have the package in my mainApplication

**Comment by sergioribeiro** [comment]
I have the same problem and I also have the package in my mainApplication. Please let me know if anyone solved this issue.

**Comment by mattapperson** [comment]
@cherniv @sergioribeiro @arilitan @expeerd has anyone tried @kvnvelasco answer?

**Comment by mattapperson** [comment]
Closing for now. Please post here if the issue persists and we can re-open

**Comment by mwiley** [comment]
@mattapperson I'm having this issue as well. I tried moving the package to the bottom of the list like @kvnvelasco has, and it didn't change anything.

**Comment by mattapperson** [comment]
Using the latest ReactNative version?

**Comment by mwiley** [comment]
@mattapperson I was on 0.31 and I just upgraded to 0.32. I'm having the same issue.

In addition to the error that @expeerd got, I get "{ error: { extra: 0, what: -38 } }" every time the screen sleeps.

**Comment by mattapperson** [comment]
@mwiley @expeerd the error code -2147483648 indicates an unknown error. This could have something to do with the video encoding, or that the file does not exist at all. From experience the first can be the most irritating... a video can play on iOS or in a video player with its own decoder like FFMpeg but then not work in the core video encoder due to the codecs used. I might recommend trying another video.

**Comment by mattapperson** [comment]
@mwiley as for your error when your screen sleeps... is that an HTC device thats having this issue?

**Comment by mwiley** [comment]
@mattapperson It's a Samsung Galaxy S6 edge. Do you have any recommendations for what codec I should be using? I converted the video from .mov to .mp4 with ffmpeg. It works on iOS.

**Comment by mattapperson** [comment]
hmmm ok well there went my theory on that issue... 

As for the video, H.264 AVC is the codec you want

**Comment by mattapperson** [comment]
@mwiley for your issue of that error when the screen sleeps, please open a new ticket

**Comment by mwiley** [comment]
@mattapperson I'm already using h.264. I'll open a new issue.

**Comment by mattapperson** [comment]
h.264 is a file format, make sure your using the right version of the codec. There are hundreds of h.264 codecs

**Comment by mwiley** [comment]
@mattapperson I don't know specifically what it would be using or what the right one would be. I converted an mov file from iMovie with ffmpeg, using this command "ffmpeg -i intro-video.mov -vcodec copy -acodec copy intro-video.mp4". It isn't the format because I uploaded the video instead of playing it locally, and that made it work. It's in my new issue.

**Comment by sergioribeiro** [comment]
It's working for me now, only if I use the local IP of the device, no audio though...

**Comment by shilpan** [comment]
@mattapperson can we re-open this issue? This still seems to be the issue. The same video, when ran on iOS runs just fine. But on Android, it throws the error: `{ error: { extra: -2147483648, what: 1 } }`

The video I have been using was recorded and encoded in Snapchat. It's using H.264 encoder and is about as nominal as it gets.

**Comment by mattapperson** [comment]
@shilpan please see my comment here on what that error means https://github.com/react-native-community/react-native-video/issues/264#issuecomment-243275079

This module uses the devices / OS's native video playing APIs, this means that yes, videos that work on one platform MIGHT NOT work on the other due to format, or encoding (please note that for example, mpeg4 is a standard, and the playback of a mpeg4 video using a particular codec on one platform but another might not).

NOW... all that said I know others are still having odd issues... Android video APIs suck, plain and simple. It is most likely worth considering using a 3rd party video SDK such as ffmepg that would produce a more reliable result on android... but that is better left to it's own ticket, and more then I am able to take on personally at the moment (but would welcome PRs

**Comment by shilpan** [comment]
@mattapperson I think I have the issue figured out. The issue is caused because I dynamically download video and cache it as an external file to not bloat the memory. I believe `react-native-video` does not support  external video resources yet? #125, #124 talk about the same thing and they seem to have not been resolved. Is it possible to support external resource files on Android?

**Comment by mattapperson** [comment]
No, not at this time

**Comment by Noitidart** [comment]
Why is this closed, it still seems this is an issue. I am not able to play the video. I am on Android 6, and using RN 0.47.1

I am getting error with the following shape:

```
{
   error: {
      extra: -2147483648,
      what: 1
   }
}
```

My code:

```
   <View style={styles.videoWrap}>
      <Video source={{ uri }} style={styles.video} resizeMode="contain" onLoad={()=>console.log('video loaded!')} onError={e=>console.log('video load failed!', e)} />
   </View>
```

**Comment by matej-io** [comment]
I have same issue on Android with latest react-native 0.47.2, 
Playing remote (not local) mp4 file encoded with h264.

Any ideas? (It was working properly on earlier version of react native)

I get this log:

```
W/AudioSystem: AudioFlinger server died!
W/IMediaDeathNotifier: media server died
E/MediaPlayer: error (100, 0)
E/MediaPlayer: Error (100,0)
I/ReactNativeJS: onError
D/FA: Event not sent since app measurement is disabled
```
Though 'onProgress' callback is continuously called, just nothing appears on screen. (sometimes messed up image appears on screen, but most of the time nothing/transparent)

In case messed up image appears I get continuously this log (onError is not triggered):
`E/GLConsumer: [SurfaceTexture-0-7158-11] syncForReleaseLocked: error dup'ing native fence fd: 0x3000`

If screen stays transparent onError returns:
`{"error":{"extra":0,"what":100}}`

**Comment by RameshSain** [comment]
same issue with me please help error: {
      extra: -2147483648,
      what: 1
   }

**Comment by Noitidart** [comment]
I resolved this unknown error by moving toe exoplayer which is included in this package. https://github.com/react-native-community/react-native-video/issues/668#issuecomment-312383674

**Comment by baloot-mobile** [comment]
you can solve the problem by using https rather than http
it will work
but the new problem is how to stream and play video by http uri
can anyone help?

**Comment by mittalswastik** [comment]
Facing the same problem. I am playing a video stored in my project folder in android directory under res where we have the app launcher icon. I am testing by tethering my mobile device. Video "successfully" plays till the time my build server is open (So I don't think there would be an issue with the video encoding with my device). But once I remove it and run the installed app video does not play and shows the same error.
{
   error: {
      extra: -2147483648,
      what: 1
   }
}

**Comment by nbennink** [comment]
Having this problem with API 19 and 20. MP4 is working fine, .m3u8 is crashing. I can't convert it to mp4 because it's a stream.

**Comment by Elgon2408** [comment]
Has anyone solved this problem? it is still active on React 0.49

**Comment by Noitidart** [comment]
I couldn't solve it. Using exoplayer was not a solution, even though it worked, it was a workaround.

**Comment by jenskuhrjorgensen** [comment]
@mattapperson Where do I find the explanation for the error codes? I'm having problems playing a video on an old HTC device and an old Nexus simulator. 
I get: `error: {
      extra: -38,
      what: 1
}`

**Comment by thijs-qv** [comment]
Old & closed issue, but is there any recommended fix for this?
```
E/NuPlayerDecoder: failed to flush [OMX.google.h264.decoder] (err=-38)
```
Can only reproduce this on certain Android devices.
