### ISSUE TITLE
Add poster attribute like in HTML 5 video

### ISSUE THREAD

**Issue by masterkrang** [TheWidlarzGroup/react-native-video#268]
http://www.w3schools.com/tags/att_video_poster.asp

**Comment by Roman-K93** [comment]
+1

**Comment by ghost** [comment]
@masterkrang did you see the TODOs in the README? See also http://www.w3fools.com

**Comment by masterkrang** [comment]
@jhabdas yes i saw the todos in the readme, so? thanks for the link but i didn't see anything valuable there.

**Comment by ghost** [comment]
TODO section link to HTML5 component updated to a more authoritative and useful resource. I'm closing this issue as it's covered by what's already stated in the TODOs, and because this repo's issues section is getting a bit out of control. Please feel free to submit a PR with support for  @masterkrang and thanks for opening the issue to raise the idea.

**Comment by afilp** [comment]
+1

**Comment by Roman-K93** [comment]
+1

**Comment by ghost** [comment]
Reopening as this now feels a more targeted need than HTML5 API conformance.

**Comment by linmic** [comment]
@jhabdas I believe this can be closed as there is already a poster attribute implemented in #400. It's not documented yet though.

**Comment by ghost** [comment]
Amen
