### ISSUE TITLE
Video not being played

### ISSUE THREAD

**Issue by cande1gut** [TheWidlarzGroup/react-native-video#279]
I have been trying to play a video but I can't make it work. Everything was installed and linked, I'm able to import the Video package without errors but I'm stuck at a white screen and I really don't know the problem, the debug console doesn't show any errors neither the app creator.

So far this is my code (as you can see is a simple video test):
![image](https://cloud.githubusercontent.com/assets/5407915/17193084/0a69430a-5417-11e6-923c-ab92084a163e.png)
![image](https://cloud.githubusercontent.com/assets/5407915/17193160/56403a18-5417-11e6-8da9-b5ca6de2b56b.png)

And my video (background.mp4) is at the root:
![image](https://cloud.githubusercontent.com/assets/5407915/17193306/09f7dc32-5418-11e6-9489-eb4f28eac26e.png)

**Comment by g0dz1ll4** [comment]
hi cande1gut try to bring the video in the generated project (iOS or Android) for me worked.
In every day use I prefer load a remote file.
Hope this help you

**Comment by cande1gut** [comment]
Hi, @g0dz1ll4, yeah, I was working like that, I'm able to play the video remotely, but I was trying to do it locally since is a best practice. Thank you.

**Comment by cande1gut** [comment]
@g0dz1ll4 I tried what you suggested, to bring the video into the Android generated project but it didn't work. Do I have to change my uri or is it ok like that?

**Comment by g0dz1ll4** [comment]
@cande1gut sorry but actually i'm away .. I've checked on iOS and all run well you have tried to put the file in raw  or assets directory on android studio project?

**Comment by cande1gut** [comment]
Thank you @g0dz1ll4, I'm now able to load local files by a pull someone did to import files like react native does with the default path.

**Comment by g0dz1ll4** [comment]
Great @cande1gut , can you describe the solution that work well for you ? so if some other has the same problem find a detailed solution ? ;)

**Comment by cande1gut** [comment]
Sure, I managed to import local files with the help of this pull: use react native asset resolving #251

**Comment by kvnvelasco** [comment]
So, this didn't work very well for me, but I found that dropping the video into 
`android/app/src/main/res/raw/` works (at least for android)

**Comment by cande1gut** [comment]
hhhmm weird @kvnvelasco, maybe it is where react-native-video module checks for assets by default, but good to know that it works for you :)

**Comment by magicspon** [comment]
I'm also having this issue. I can play remote files but not local ones

**Comment by cande1gut** [comment]
Hey @magicspon have you tried what @kvnvelasco suggests? Therefore, if you still have this issue try to implement this, which is a pull request to be able to use local files like react native does by default: [React Native asset resolving](https://github.com/react-native-community/react-native-video/pull/251/commits/7fc7b3dc1ba20bd0b42e47ffe0bbb3f74d696bac)

**Comment by ghost** [comment]
#251 merged. Please close this issue to help keep repo clean.

**Comment by magicspon** [comment]
@cande1gut I did try but to no success.  I shall take another look tomorrow. Thanks

**Comment by ghost** [comment]
@magicspon make sure to pull version 0.9.0 of the NPM module. Brent released it within the last 12 hours.

**Comment by magicspon** [comment]
@jhabdas, @candle1gut I've pulled in version 0.9.0 via `npm i react-native-video@0.9.0` still no joy.

**Comment by ghost** [comment]
@magicspon It's hard to guess what you're doing, specifically. But the following should help:
1. Documentation updated this morning for new use of the RN asset system available in `0.9.0`: https://github.com/react-native-community/react-native-video#load-files-with-the-rn-asset-system (though the existing approach using `source={{uri: 'foo.png'}}` remains unchanged).
2. Example code using `0.9.0` with local mp4 file: https://github.com/jhabdas/lumpen-radio/blob/5279b00da8428fd2a79af426dec60eb0fee06a26/src/components/BackgroundVideo.js using both asset system (Android) and existing approach (ios). `develop` branch can be pulled and run for example.
3. Due to [a known bug](https://github.com/facebook/react-native/pull/9254) use of the RN asset system for MP4s (i.e. using `require('../assets/video/foo.mp4')` works _only_ for Android.
4. Lastly be sure, if you're adding video assets to iOS and not using the asset system (because it won't be possible to for that platform until at least RN `0.32` due to aforementioned bug), you've included the asset in the copy bundle step in Xcode target settings Build Phases as shown below:

<img width="561" alt="screen shot 2016-08-17 at 8 59 26 am" src="https://cloud.githubusercontent.com/assets/440298/17739588/3d6c7ffc-645b-11e6-91a1-43648437c637.png">

**UPDATE 10 Sep 2016:** MP4 video assets will work properly when served from the packager with `require` as of RN `0.33`. See the [bugfixes in the release notes](https://github.com/facebook/react-native/releases/tag/v0.33.0)

**Comment by magicspon** [comment]
@jhabdas HUZZZAH! It's alive...  I'm only developing for Android so a few points I can ignore.

But using the new require syntax is working.

Thanks for your help, greatly appreciated

**Comment by ghost** [comment]
Oh fo sho

**Comment by quadsurf** [comment]
I did a straight copy and paste, but no luck either. I see the progress bar indicating that the video is indeed advancing frames, but it's all a black/blank video, no matter what mp4 i insert, remote or local.

I am only testing in xCode/iOS simulator.

Here are my dependencies:
    "firebase": "^3.2.1",
    "react": "15.3.1",
    "react-native": "^0.34.1",
    "react-native-elements": "^0.6.0",
    "react-native-material-kit": "^0.3.2",
    "react-native-orientation": "^1.17.0",
    "react-native-vector-icons": "^2.1.0",
    "react-native-video": "^0.9.0"
