### ISSUE TITLE
Question: Is V6 alpha 2 released on npm?

### ISSUE THREAD

**Issue by Kesmek** [TheWidlarzGroup/react-native-video#2807]
### Current behavior
Currently I don't see react-native-video@6.0.0-alpha.2 on npm registry even though there is a [changelog](https://github.com/react-native-video/react-native-video/blob/master/CHANGELOG.md) listed for that version.

### Reproduction steps
Try `yarn add react-native-video@6.0.0-alpha.2` or `npm i react-native-video@6.0.0-alpha.2`.

### Expected behavior
Alpha 2 is fetched and installed using the above commands.

Thank you to all the maintainers for keeping this project afloat amid all the troubles it's gone through!

**Comment by rafamanzo** [comment]
I believe the answer still is the same in https://github.com/react-native-video/react-native-video/issues/2771#issuecomment-1191138627

**Comment by kirgy** [comment]
Are you able to provide any update on this? We're in a position of carrying on using your library or removing it in favour or another due to deadlines, but our preference is to keep using this.

There are some fixes which are vital to us listed in the [change log](https://github.com/react-native-video/react-native-video/blob/master/CHANGELOG.md#version-600-alpha2), namely `subtitle styling` and `callbackChangeRate`.

Appreciate your time folks, you're doing great work!

**Comment by evoactivity** [comment]
@kirgy for now I would recommend installing this from the master branch, update your package.json to `"react-native-video": "react-native-video/react-native-video",`.

**Comment by freeboub** [comment]
You can also use a specific SH1 !
I advise you to create your own fork for now..
As no company give full support on the package, we can only go on with that ...

**Comment by kirgy** [comment]
@evoactivity @freeboub thanks both, I'll use a hash for now - I don't know why I didn't think of this before, it's obvious now you say it 😅
