### ISSUE TITLE
Embedded text tracks not working on tvOS

### ISSUE THREAD

**Issue by jomachh** [TheWidlarzGroup/react-native-video#2910]
# Bug

I'm using an m3u8 video that has embedded text tracks, works perfectly on iOS but tvOS doesn't show the text tracks and the text track list, only show the text track icon but nothing happens when it is pressed. (Using native controls)

## Platform

Which player are you experiencing the problem on:
* tvOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 403.13 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 23, 29, 30, 31, 32
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0
      System Images: android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs ARM EABI v7a, android-23 | Google APIs ARM 64 v8a, android-25 | ARM 64 v8a, android-26 | ARM 64 v8a, android-28 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google TV ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.69.6-0 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.1

## Steps To Reproduce

1. Use a video that has embedded text tracks
2. Use tvOS native controls
3. Try to open the text track list and select one
...

## Video sample
https://youtu.be/Bh6ptcKSvI4

**Comment by jomachh** [comment]
It also happens using a real Apple TV

**Comment by ChristiaanScheermeijer** [comment]
Any updates regarding this issue? We see the same issue on v5.2.1 and v6.0.0-alpha.6.

The native text track button does appear, but pressing it doesn't do anything. However, by using the `selectedTextTrack` the embedded text track does appear.

I did have to disable the following `TARGET_OS_TV` conditionals, though:

https://github.com/react-native-video/react-native-video/blob/ce03223f94771153962285042f28bed8881d633c/ios/Video/RCTVideo.m#L1139-L1153

Controlling the embedded text tracks is currently only possible with custom UI, but this would also mean we will have to re-create the native controls in React Native.

Does anyone know why the native controls text track button doesn't work? Is this because react-native-video overrides this with the `selectedTextTrack` logic?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/3996119/233349718-e695c016-dad5-413c-884b-80b61cd9df30.png">

**Comment by altaywtf** [comment]
having the same issue, might be related to this: https://github.com/react-native-video/react-native-video/issues/2507

there are text tracks for sure (`selectedTextTrack={{ type: 'index', value: 0 }}` works) but something `RCTVideo` does is preventing native player UI to work properly.

**Comment by ChristiaanScheermeijer** [comment]
@altaywtf, I was able to fix it using a hook from the Bitmovin repository: https://github.com/bitmovin/bitmovin-player-react-native/blob/development/example/src/hooks/useTVGestures.ts
