### ISSUE TITLE
All examples app in this repo build fails

### ISSUE THREAD

**Issue by jeremyspritelyco** [TheWidlarzGroup/react-native-video#2931]
# Bug
All examples app in this repo build fails #2931

## Platform

Which player are you experiencing the problem on:
* iOS
* Android

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1. clone this repo
2. run the example app
...

## Expected behaviour

1. it works

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Agree, I know this issue. 
We just need to upgrade react native version is the samples. 
I hear @swemail already did this job ([ here ](https://github.com/react-native-video/react-native-video/pull/2926) :) If you can create a Pull request for this, it would be very great!

@swemail I can  handle android part if you need

**Comment by swemail** [comment]
@freeboub I have added a PR https://github.com/react-native-video/react-native-video/pull/2933 with an update for example/basic for iOS and happy to leave android for you 😂. Since I was only testing out with the basic example I had a fix for that and the same didn't work for `video-caching` and the third was a bit foreign to me. Don't know if they need a total rewrite or could be removed, leave that to you

**Comment by freeboub** [comment]
fix on master branch (tested only android): https://github.com/react-native-video/react-native-video/pull/2960

**Comment by freeboub** [comment]
I fixed the master sample (tested only on android for now)

**Comment by freeboub** [comment]
fixed on master branch (alpha.8 is Ok at least)
