### ISSUE TITLE
^6.0.0-alpha.3 "errorCode": "24001" in some mkv videos

### ISSUE THREAD

**Issue by Arekjaar4** [TheWidlarzGroup/react-native-video#2945]
I get this error on some mkv format videos when I try to play them. The videos are part of an iptv list

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

info Fetching system and libraries information...
(node:18276) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 2.81 GB / 15.89 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 21.3.6528147
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_261
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.5 => 0.69.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by freeboub** [comment]
Not enough information to investigate or give support ...

**Comment by Arekjaar4** [comment]
Hi,

Sorry, what info you need?

**Comment by freeboub** [comment]
**Reproducible sample code**

You should have a look to the logcat to understand the issue

**Comment by Takesizmail** [comment]
Hi get the save code error in version 6.0.0-alpha.5 
I got video from the camera
`
errorCode: "24001"
errorException: "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64000A, -1, null, [1920, 1080, 26.141655], [-1, -1]), format_supported=YES"
errorStackTrace: "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64000A, -1, null, [1920, 1080, 26.141655], [-1, -1]), format_supported=YES↵	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)↵	at android.os.Handler.dispatchMessage(Handler.java:102)↵	at android.os.Looper.loop(Looper.java:237)↵	at android.os.HandlerThread.run(HandlerThread.java:67)↵Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.64000A, -1, null, [1920, 1080, 26.141655], [-1, -1])↵	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)↵	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)↵	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)↵	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)↵	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)↵	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)↵	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)↵	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)↵	... 3 more↵Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4↵	at android.media.MediaCodec.native_configure(Native Method)↵	at android.media.MediaCodec.configure(MediaCodec.java:2127)↵	at android.media.MediaCodec.configure(MediaCodec.java:2043)↵	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)↵	at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:110)↵	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)↵	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)↵	... 10 more↵"
errorString: "ExoPlaybackException: ERROR_CODE_DECODER_INIT_FAILED"
`
