### ISSUE TITLE
backBufferDurationMs prop not working

### ISSUE THREAD

**Issue by ValentineCodes** [TheWidlarzGroup/react-native-video#2977]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android

## Expected behaviour

Should preserve buffers to prevent rebufferring when I seek backward. Without this, video always rebuffers on repeat

**Comment by freeboub** [comment]
It seems this issue can reproduce on sample.
--> configure back buffer duration to 60000 (1 minute)
start playback on sintel
wait 1 minute
disable wifi
seek at the beggining
--> video doesn't resume

**Comment by ValentineCodes** [comment]
I noticed there's also no type declarations for backBufferDurationMs

**Comment by freeboub** [comment]
I review the code, and it is shitty. I will check this issue !

**Comment by freeboub** [comment]
fix will be available in 6.0.0-beta.7

**Comment by phazei** [comment]
I'm using 6.8.1 and am still seeing this issue.

We have a bunch of videos shown on a screen.  Our test videos are 3 - 30sec.  I set the back buffer to 60s, but when moving around the video, it starts downloading from scratch every time.

**Comment by freeboub** [comment]
> I'm using 6.8.1 and am still seeing this issue.
> 
> We have a bunch of videos shown on a screen.  Our test videos are 3 - 30sec.  I set the back buffer to 60s, but when moving around the video, it starts downloading from scratch every time.

For such use case, i would advise to use  caching mechanism!

**Comment by phazei** [comment]
I did set the Video prop: source.bufferConfig.cacheSizeMB to 100, but it didn't seem to make any difference.

We're going to attempt to implement this https://github.com/nguyenvanphituoc/react-native-cache-video which seems to create a proxy that will cache the byte-ranges retrieved which should hopefully handle it.  But I would have expected that once part of a video has played, to be able to scroll back to that piece and just have it be there similar to every streaming video player I've seen.

EDIT:
So, I did figure out some issues in our code and got the built in caching to sort of work, there seems to be a bug where it decides to ditch the cache and redownload if going to the very very beginning, but otherwise the buffering and caching was working good.  Ironically, I figured that out while debugging `react-native-cache-video`, which I also got working, and works so well.

One thing I noticed about the `react-native-video` cache is it seems to only cache while playing the video.  If I close the video, then open it again, it doesn't have the cache anymore.  For our purposes that wasn't useful at all, I thought once it was cached, it would just keep it until the cache ran out and eventually replace it with something else.  But the `react-native-cache-video` handles that swimmingly!
