### ISSUE TITLE
96 issues & 11 PRs – how can we continue development?

### ISSUE THREAD

**Issue by jaredscheib** [TheWidlarzGroup/react-native-video#301]
I've got a project that requires video via React Native, and I'd love to use this one, but I'm concerned about all of the outstanding issues and PRs.

Purely out of a desire for continued improvement, thankful for what's been done so far, and acknowledging the PRs and interest (with so many Issues), I'm wondering what can we do to keep development on this repo & project going consistently? Or otherwise is there a solid fork and is development continuing elsewhere?

Many thanks~

**Comment by brentvatne** [comment]
Hi @jaredscheib! I started this project right when React Native came out and I no longer use it so I have since given collaborator status to some hard working folks. @grabbou has recently mentioned that he would like to help out and @jhabdas has done a lot of work recently. @sjchmiela  has put a lot of work into it and so has @isair. I transferred the repo to react-native-community to make it clear that this project belongs to the community. If you would like to join in as a maintainer, feel free to reach out to me at brentvatne at gmail dot com.

**Comment by ghost** [comment]
@jaredscheib I  recently did an audit of the last 20-ish issues and it's clear there are a lot of newcomers to the space. My goal is to help reduce the number of open issues, and if there's anything I can do to help please let me know.

**Comment by jaredscheib** [comment]
Thank you for the quick and kind responses, @brentvatne and @jhabdas -- I may reach out to serve as a maintainer in the near future after diving into the project a bit more, now that I know it's being overseen by a handful of folks. Looking forward to this continuing to grow. Thanks again!

**Comment by mattapperson** [comment]
Closing this for now 😊 but thank you too for your concern @jaredscheib. We are working hard to clean up this project and would love your assistance too once you dig in!
