### ISSUE TITLE
React Native Video Rendering Issue on iOS and Android Platforms

### ISSUE THREAD

**Issue by IgorAugustoexe** [TheWidlarzGroup/react-native-video#3101]
Hello.

I am Igor Augusto, a React Native mobile developer based in Brazil, and I am currently facing an issue with the react-native-video module in my application. I would like to share more information about the problem so that we can discuss it in depth.

When trying to render multiple videos in my application using the react-native-video module, I have noticed that the module behaves differently on iOS and Android platforms. On iOS, the first ten videos are sequentially prepared, and subsequent videos are prepared as they are played. However, on Android, the first ten videos are prepared twice, and subsequent videos are prepared in a disorderly manner. This has led to problems with ERROR_CODE_DECODING_FAILED on Android devices, as well as inconsistencies in the overall performance of the application.

In light of this problem, I am seeking possible solutions to resolve it. I have already checked if the react-native-video module is up-to-date on both platforms, as well as whether the application is properly managing memory and correctly releasing resources when videos are paused or finished playing. Additionally, I am looking for specific module configurations that may help to solve the problem, as well as other specialized video rendering libraries such as ExoPlayer for Android.

I would like to ask for help and suggestions for additional solutions to this problem. Thank you in advance for your attention and collaboration.

**Comment by freeboub** [comment]
Hello,
To be clear, The error: CODE_DECODING_FAILED is linked to too many Video View initialised in the same time.
I think this discussion is interesting: https://github.com/react-native-video/react-native-video/issues/2984
Technically it is not possible to allocating 100 video decoders on android. That is the root cause.
There is no easy workaround to do in react native video.
I will close the ticket, Let me know if you need more advices.
