### ISSUE TITLE
IOS nil string parameter.

### ISSUE THREAD

**Issue by gviligvili** [TheWidlarzGroup/react-native-video#316]
Before posting I tried to follow the git instructions 3 times.

Details : RN 0.32, 

I didn't add anything to xcode/ios/android environment (the only thing I did is put the video file in my root directory, and 'react-native link'  ( I checked and for android everything needed was added to MainApplication.java)

I tried this way When file smoke.mp4 is in the root:

```
<Video
                source={{uri: "smoke"}}
                rate={1.0}
                volume={1.0}
                muted={false}
                paused={false}
                resizeMode="stretch"
                repeat={true}
                playInBackground={false}
                playWhenInactive={false}
                style={styles.backgroundVideo}
            />

```

It caused this in xcode : 

> 2016-09-02 19:16:51.574 puffClient[35456:7558213] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSURL initFileURLWithPath:]: nil string parameter'
> **\* First throw call stack:

Then I tried the following, I've read issues and saw it doesn't work for ios, but the documentation stated it might so I tried : 

```
<Video
               ##  source={require('../../../smoke.mp4' )}
                rate={1.0}
                volume={1.0}
                muted={false}
                paused={false}
                resizeMode="stretch"
                repeat={true}
                playInBackground={false}
                playWhenInactive={false}
                style={styles.backgroundVideo}
            />
```

It doesn't give me any compilation errors, or xcode errors at all, but it does Black screen to the app.

Thanks for you attention, have a great day.

**Comment by fossage** [comment]
+1

**Comment by fossage** [comment]
I was having a similar issue, and after seeing @gviligvili's question, I tried using the `source={require('../foo.mp4')}` syntax as opposed to the `source={{uri: "foo"}}` syntax.  

It didn't work for me at first, and I had a similar result where the error message would go away but all I would see was a black screen, however after a number of reloads, it suddenly started working.  I reloaded again after making some small changes, and once I did it went back to the black screen.  I then reverted the changes expecting that the video would start playing again, however it did not.  After a long while of trying numerous things to get it to work again, it suddenly did when I changed where the file lived in the directory structure. Then, after another reload with no changes, I was back to the black screen.

I am completely lost when it comes to Objective C so I wish I could be of more help, but it seems like there may be some timing discrepancy between when the file is loaded and when the component gets instantiated.  

**Update: It seems to be working consistently now as long as I use the `source={require('../foo.mp4')}` and am running the application on an actual device.  As far as the intermittent failures I was seeing yesterday, I am still not sure but I suspect it may have something to do with the way the packager was caching the bundle.  That's my best guess so far at least, because after simply disconnecting my phone and shutting down the packager, when I came back to it after a few hours of sleep it suddenly seemed to work without issue.

**Comment by RafalWilinski** [comment]
I also have following issue. Running `react-native log-ios` gives me this:

```
Sep  3 15:40:15 MBP-Rafal FameStats[4002] <Notice>: (Error) MC: MobileContainerManager gave us a path we weren't expecting; file a radar against them
        Expected: /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
        Actual: /Users/Rafal/Library/Developer/CoreSimulator/Devices/F9E21B77-7325-45A7-B952-8C55DD32E68C/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
        Overriding MCM with the one true path
Sep  3 15:40:15 MBP-Rafal FameStats[4002] <Warning>: Sending `websocketFailed` with no listeners registered.
Sep  3 15:40:15 MBP-Rafal FameStats[4002] <Notice>: Running application "FameStats" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Sep  3 15:40:15 MBP-Rafal FameStats[4002] <Error>: nw_interface_create_with_index refusing to create an interface with index 4294967295 too high (>=2147483647)
--- last message repeated 3 times ---
```

Update: Seems that it works fine on real device, following bug appears only in simulator. It also does not work when running on real device but taking assets from local server, shame. It works only when running straight from Xcode and using offline bundle.

**Comment by mattapperson** [comment]
@RafalWilinski That issue seems to be unrelated to this issue. Please create a new issue to track the problem you are seeing.

**Comment by nazrdogan** [comment]
I m facing this issue with React Native 0.32 . I tried example app to run . its give me same result

**Comment by aaroncrawford** [comment]
+1 - same - on .32.1

**Comment by mattapperson** [comment]
My MacBook is at the Apple Store for repair for the past few days. As soon as I get it back tonight I'll try and replicate/fix this issue

**Comment by quadsurf** [comment]
@gviligvili 
I get the same issue on RN 0.32
when using
source={require('../../../smoke.mp4' )}
the black screen should go away if you update to RN 0.33, as per this repo's ReadMe
I'm going to upgrade to RN 0.33 and see if that fixes it.

If I need to revert back to RN 0.32 , @mattapperson have you had any luck replicating/fixing this issue?

**Comment by gviligvili** [comment]
Checked again after a while - Don't know what I did, it work's for me now.
Probably updated Xcode and RN to 33.
Good day :)

**Comment by andresn** [comment]
I was seeing the same issue (using `source={{uri: 'metal_drop', type: 'mp3'}}`), gave my computer a hard restart, and all is well.

**Comment by andresn** [comment]
... also, I'm having to add my assets to "Copy Bundle Resources" in XCode under Targets > My App > Build Phases. 

![image](https://cloud.githubusercontent.com/assets/69597/24576079/0900976e-166a-11e7-99b7-d76d938b64bc.png)

Should this be in the ReadMe for newcomers?

$ npm ls react-native react-native-video
├── react-native@0.42.3 
└── react-native-video@1.0.0

**Comment by dgurns** [comment]
I was also seeing this issue on iOS until I added the type, like so:

`source={{ uri: 'fileName', type: 'mp4' }}`

**Comment by fiznool** [comment]
FWIW I was having a similar issue. I was looking to store the video file inside the native iOS/Android resources system, instead of using the React Native asset loader, to prevent the file being sent over the bridge whenever it needed to play.

For posterity, this is what I did to get it all working.

**Files**

- Make sure your video filename begins with a letter (Android will barf on anything else) and has the correct extension (e.g. `.mp4`).
- Put your video files in an `assets/videos/` folder in the root of your filesystem. Keep them all in the same folder, i.e no subdirectories.

For the rest of the below, I'll assume we have a video file `example.mp4` in this folder.

**iOS**

- Open the `assets/videos` folder in Finder
- Open the `.xcodeproj` file in Xcode, click on the Project navigator icon to show the project files in the left hand pane
- Select the video files you want in Finder, drag them over to Xcode, inside the 'Resources' folder
- In the pop-up box, check the `Copy items if needed` checkbox, and check the first two targets (`YourAppName` and `YourAppNameTests`)

Note that this will create a reference to the actual files, which will remain in `assets/videos/`.

**Android**

- Create the folder `android/app/src/main/res/raw` (if it doesn't already exist)
- Copy your video files into this folder (keep them in the root of `raw`, i.e. no subfolders, otherwise Android won't find them at runtime)

**React**

- Render your video using the syntax `<Video source={{ uri: 'example', type: 'mp4' }} />` - note that the `uri` is the filename minus the extension, and the `type` is the extension.

And hey presto, hopefully your video will load with no sending over the bridge!

**Comment by Shahrukh0396** [comment]
what can we do for remote urls??

**Comment by Jayvish100** [comment]
@Shahrukh0396 

You should check the url. It should not have any spaces.

in my case a there were a couple spaces in the URL from the API which caused this issue in IOS only not on android.

I hope this helps you.
