### ISSUE TITLE
Sometimes m3u8 video playing as blank screen

### ISSUE THREAD

**Issue by Robiullah2244** [TheWidlarzGroup/react-native-video#3164]
# Bug

This is the flow of callbacks
1) onLoadStart calling
2) onLoad calling
3) **_onReadyForDisplay not calling (but running the video as a blank screen I assume)_**
4) onProgress calling.
5) onEnd calling after the video duration

Sample video link: https://content.jwplatform.com/manifests/FPFxxg3T.m3u8
 
## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
 System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 58.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/mdrobiullah/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps To Reproduce

1. Sometime this issue is happening. For the same video, most of the time playing perfectly.
```
<Video
  ref={player}
  style={styles.player}
  source={{uri: videoUrl}}
  paused={isPaused}
  onLoadStart={() => {
    console.log(videoUrl+" onLoadStart");
    setIsPreLoading(true)
  }}
  onError={(e)=>{
    console.log(videoUrl+" onError",e);
  }}
  onReadyForDisplay={() => {
    console.log(videoUrl+" onReadyForDisplay");
    setIsPreLoading(false);
  }}
  onLoad={() => {
    console.log(videoUrl+" onLoad");
  }}
  onEnd={()=>{
    console.log(videoUrl+" onEnd");
    onIdle()
  }}
  resizeMode="cover"
/>
```

## Expected behaviour

1. Must play the video always or call onError if any error happens

## Video sample
https://github.com/react-native-video/react-native-video/assets/33126665/2c6b9335-5755-4b57-8f47-7c7d1fbe58ee

**Comment by freeboub** [comment]
Your manifest contain a playlist without video, I think is the root cause.
In case of poor bandwidth, AVplayer can choose this stream

#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=510000,RESOLUTION=480x270,CODECS="mp4a.40.2,avc1.42c015",FRAME-RATE=24.0,CLOSED-CAPTIONS=NONE
https://videos-cloudfront-usp.jwpsrv.com/64aa61f7_461014c3410acc272ff808353b9c7113b21b8fde/site/e6ZhdG2f/media/FPFxxg3T/version/FPFxxg3T/manifest.ism/manifest-audio_eng=112000-video_eng=394264.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3250000,RESOLUTION=1920x1080,CODECS="mp4a.40.2,avc1.640028",FRAME-RATE=24.0,CLOSED-CAPTIONS=NONE
https://videos-cloudfront-usp.jwpsrv.com/64aa61f7_461014c3410acc272ff808353b9c7113b21b8fde/site/e6ZhdG2f/media/FPFxxg3T/version/FPFxxg3T/manifest.ism/manifest-audio_eng=112000-video_eng=3130960.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1500000,RESOLUTION=1280x720,CODECS="mp4a.40.2,avc1.4d401f",FRAME-RATE=24.0,CLOSED-CAPTIONS=NONE
https://videos-cloudfront-usp.jwpsrv.com/64aa61f7_461014c3410acc272ff808353b9c7113b21b8fde/site/e6ZhdG2f/media/FPFxxg3T/version/FPFxxg3T/manifest.ism/manifest-audio_eng=112000-video_eng=1386872.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=680000,RESOLUTION=720x406,CODECS="mp4a.40.2,avc1.4d401e",FRAME-RATE=24.0,CLOSED-CAPTIONS=NONE
https://videos-cloudfront-usp.jwpsrv.com/64aa61f7_461014c3410acc272ff808353b9c7113b21b8fde/site/e6ZhdG2f/media/FPFxxg3T/version/FPFxxg3T/manifest.ism/manifest-audio_eng=112000-video_eng=563944.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=310000,RESOLUTION=320x180,CODECS="mp4a.40.2,avc1.42c00d",FRAME-RATE=24.0,CLOSED-CAPTIONS=NONE
https://videos-cloudfront-usp.jwpsrv.com/64aa61f7_461014c3410acc272ff808353b9c7113b21b8fde/site/e6ZhdG2f/media/FPFxxg3T/version/FPFxxg3T/manifest.ism/manifest-audio_eng=112000-video_eng=190816.m3u8
**#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=120000,CODECS="mp4a.40.2"
https://videos-cloudfront-usp.jwpsrv.com/64aa61f7_461014c3410acc272ff808353b9c7113b21b8fde/site/e6ZhdG2f/media/FPFxxg3T/version/FPFxxg3T/manifest.ism/manifest-audio_eng=112000.m3u8**

**Comment by freeboub** [comment]
I close the ticket, let me know if it is not the root cause

**Comment by Robiullah2244** [comment]
Hi @freeboub, the reply "Your manifest contains a playlist without video, I think is the root cause" suggests that the provided m3u8 manifest file includes a playlist entry that does not have an associated video. However, in the case of the provided link (https://content.jwplatform.com/manifests/FPFxxg3T.m3u8), it is actually a direct link to a video, not a playlist.

**Comment by freeboub** [comment]
Hi @Robiullah2244 , please download the file and open it with a text editor. You will see different qualities of video available. The last one is audio only !

**Comment by Robiullah2244** [comment]
Hi @freeboub, thank you so much.
