### ISSUE TITLE
AdEventListener is defined multiple times.

### ISSUE THREAD

**Issue by subhechhu** [TheWidlarzGroup/react-native-video#3191]
Type com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener is defined multiple times.

Can see the AdEventListener interface in google ads library as well on react-native-video.
 
```
package com.google.ads.interactivemedia.v3.api;
import androidx.annotation.InspectableProperty;

public abstract class AdEvent {
    public abstract InspectableProperty getType();

    public interface AdEventListener {
        public void onAdEvent(AdEvent adEvent);
    }
}
```

google ads: 
/Users/foolish/.gradle/caches/transforms-3/48958b293b3dc79594bf867ed7e1a7b5/transformed/jetified-interactivemedia-3.24.0.jar:com/google/ads/interactivemedia/v3/api/AdEvent$AdEventListener.class

react-native-video
/Users/foolish/.gradle/caches/transforms-3/48958b293b3dc79594bf867ed7e1a7b5/transformed/jetified-interactivemedia-3.24.0.jar:com/google/ads/interactivemedia/v3/api/AdEvent$AdEventListener.class

It is creating issue on release build with minify enabled. How to handle it?

**Comment by freeboub** [comment]
Did you try a gradlew clean ?

**Comment by subhechhu** [comment]
Yep. No luck.

**Comment by freeboub** [comment]
Do you enable ads ? Did you try rm -rf node_modules ?

**Comment by subhechhu** [comment]
We have enabled ads using another library which utilities the following SDK,    
implementation 'com.google.ads.interactivemedia.v3:interactivemedia:3.24.0'
and ads aren't enabled from react-native-video

Also yes we have cleared the node modules and tried building.

**Comment by freeboub** [comment]
@subhechhu As conditional compilation is not 'natural' in java, There is a stub defined in react native video to allow using ima sdk or not. If you enable ads insertion, the stub but be build instead of ima sdk.
So you have 2 choices I think:
- either enable ads insertion in react native video (it will not be used if ou don't specify adsTagUrl)
- do a patch to remove the stub (see files in : android/src/main/java/com/ )
