### ISSUE TITLE
Streaming MP4 video is not working in android

### ISSUE THREAD

**Issue by chandni-solanki** [TheWidlarzGroup/react-native-video#3403]
# Bug

I am trying to play video through my url, but it is not playing.
This file is working fine in native android player as well as in browser but it is not working in react native video.

But if I try to play this sample url - https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4, its working fine. My question is, why my video is not working even though it is in mp4.

The error I am getting while playing it is- the format is not supported. 
I have tried this - https://github.com/react-native-video/react-native-video/issues/2359 and this - https://github.com/react-native-video/react-native-video/issues/1032 also, but hard luck.

The code is:

```
<Video
            // Can be a URL or a local file.
            source={{ uri: "my url", type: "mp4" }}
            // Store reference  
            ref={(ref: any) => {
                videoRef = ref
            }}
            paused={pause}
            controls={true}
            resizeMode={"contain"}
            fullscreen={true}
            fullscreenAutorotate={true}
            fullscreenOrientation="landscape"
            onBuffer={() => {
                console.log("Buffering");
            }}
            onLoadStart={() => {
                console.log("Loading video...", Date());
            }}
            onLoad={() => {
                console.log("onload complete", Date());
            }}
            onError={(error: any) => {
                console.log("Video error => ", error);
            }}
            style={{
                flex: 1
            }}
            onEnd={navigateToScreen}
        /> 
```

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 5.2.1
React Native version: 0.67
Device:  Android

**Comment by freeboub** [comment]
Hello, first, can you try on V6 version ?
The format issue can be linked to your device... Did you try to analyze the logcat ?

**Comment by chandni-solanki** [comment]
hi @freeboub , I can't use V6 version as per documentation, V6 is for React Native version >= 0.68.2. Mine is 0.67.

The error that I am facing with expo player is -
```
Video error => ', { error: 
                                  { errorException: 'd.e.a.c.p0: Source error',
                                   errorString: 'Unrecognized media format' } }
```

And with android player -
```
{ error: { extra: -2147483648, what: 1 } }
```

In all android devices I am facing this issue.

**Comment by freeboub** [comment]
@chandni-solanki I think you have a ssl certificate issue on your server:

When I play with V6, I have following exception in logcat:

12-06 07:33:10.757 16657 16726 E ExoPlayerImplInternal:   Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: java.io.IOException: java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

when I try to download the file with wget:

olivier@oliviers-Air react-native-video_official % wget https://academy.tesvolt.com/sites/default/files/h5p/content/918/videos/files-6442368bf3787.mp4
--2023-12-07 22:22:14--  https://academy.tesvolt.com/sites/default/files/h5p/content/918/videos/files-6442368bf3787.mp4
Resolving academy.tesvolt.com (academy.tesvolt.com)... 52.166.187.201
Connecting to academy.tesvolt.com (academy.tesvolt.com)|52.166.187.201|:443... connected.
ERROR: cannot verify academy.tesvolt.com's certificate, issued by ‘CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O=GoDaddy.com\\, Inc.,L=Scottsdale,ST=Arizona,C=US’:
  Unable to locally verify the issuer's authority.
To connect to academy.tesvolt.com insecurely, use `--no-check-certificate'.

If I try with http, I have following error: Unable to resolve host \"academy.tesvolt.comsites\": No address associated with hostname\


If I try to download it:
olivier@oliviers-Air lib % git echo | openssl s_client -servername academy.tesvolt.com -connect academy.tesvolt.com:443 |\ 
  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > certificate.crt
git: 'echo' is not a git command. See 'git --help'.

The most similar command is
	fetch
depth=0 CN = *.tesvolt.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.tesvolt.com
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = *.tesvolt.com
verify return:1

**Comment by freeboub** [comment]
SSL certificate issue, let's close this issue, ping me if i need to reopen it.
Notice that your react native version should be support, you can try V6.0.O

**Comment by chandni-solanki** [comment]
But @freeboub  if you try to play the video via browser or even in device's browser, it is working fine without any error. I am not getting why the react native video facing SSL certificate related error?

**Comment by freeboub** [comment]
First did you check you have the same error I saw ?
Here is a workaround explained https://stackoverflow.com/questions/52618113/exoplayer-how-to-validate-server-certificate

I would really recommend to fix ssl certificate instead of introducing workaround!
