### ISSUE TITLE
[Android] video restarts when change orientation by react-native-orientation-locker

### ISSUE THREAD

**Issue by hasan642** [TheWidlarzGroup/react-native-video#3439]

**Comment by nicolaosm** [comment]
This bug is actually happening! Can you please confirm @KrzysztofMoch on your end too?

**Comment by nicolaosm** [comment]
# Bug



## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: V6 Beta 3
Device: Several Android Emulators
Using react-native-orientation-locker library.

## Steps To Reproduce

1. Play video
2. Rotate between portrait and landscape.
3. It will restart the video

## Expected behaviour

1. Video continues to play even when we rotate between portrait and landscape. Should not restart the video

**Comment by aliatore** [comment]
Same here in version

 react-native-orientation-locker -> 1.6.0
 react-native-video -> 6.0.0-beta.0

**Comment by freeboub** [comment]
can you please retest on last last V6.2.0 release ?
if reproduced, a sample would be very usefull !
