### ISSUE TITLE
`RNVUseExoplayerIMA = false` - includes non-FOSS `androidx.media3 » media3-exoplayer-ima` lib

### ISSUE THREAD

**Issue by licaon-kter** [TheWidlarzGroup/react-native-video#3500]
## Platform
Which player are you experiencing the problem on:
* Android

## Environment info
Library version: 6.0.0-beta.3 and 6.0.0-alpha.7 

## Steps To Reproduce
* set `RNVUseExoplayerIMA = false`
* build an app

## Expected behaviour
* there are no proprietary ads related libs included in the app

## Reproducible sample code
* ref: https://github.com/podverse/podverse-rn/issues/2133
* ref: https://github.com/Infomaniak/android-infomaniak-meet/issues/1 ( via https://github.com/jitsi/jitsi-meet/blob/android-sdk-8.6.0/package.json#L105 )

**Comment by freeboub** [comment]
I think this is a false positive ...
In order to enable or disable IMA at build time, we add some stub classes when we disable it.
These stub classes have the same package name than IMA package.
If you want to triple check the difference, you can try to enable IMA and see the report (I expect it will be bigger).
I thought implementing this conditional compilation with reflexivity, but it is a bit painful...
You can find some of the stub here: https://github.com/react-native-video/react-native-video/tree/master/android/src/main/java/com/google/ads/interactivemedia/v3/api

If you have a better proposal for this "conditional build", we can take it in considerable of course !

**Comment by KrzysztofMoch** [comment]
@freeboub I think it's issue with our check in gradle. If you change code to this
![CleanShot 2024-01-26 at 22 41 17](https://github.com/react-native-video/react-native-video/assets/83216158/5833a70e-a20e-4578-bcd6-bac966af5cee)
It will exclude this code in fact and app will not compile...

**Comment by freeboub** [comment]
You are right, but the detected classes are the stub files, not the proprietary google libraries, what's why I think this is a false positive report !

**Comment by licaon-kter** [comment]
Indeed looking at deps they are not pulled.

Thanks
