### ISSUE TITLE
The screen turns off in fullscreen mode

### ISSUE THREAD

**Issue by mezalejandro** [TheWidlarzGroup/react-native-video#3552]
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

When you put it in full screen mode the screen turns off

### Reproduction

Step to reproduce this bug are: 
Using the native controls of the player, when you put it in full screen mode the phone screen turns off

**Comment by mezalejandro** [comment]
I tried with FLAG_KEEP_SCREEN_ON  but it's not working
https://developer.android.com/develop/background-work/background-tasks/scheduling/wakelock

**Comment by gkueny** [comment]
Hello @mezalejandro 

thanks for the report.
I setup a reproduction repo here: https://github.com/gkueny/FullScreenModeTurnOffAndroidReproduction

I think I have a guess & a potential fix. I will check tomorrow

**Comment by mezalejandro** [comment]
Thanks @gkueny !

**Comment by mezalejandro** [comment]
This issue was fixed, please apply this PR.
Thank you
And thanks @gkueny

**Comment by freeboub** [comment]
I spotted a regression, it will be merged soon !

**Comment by freeboub** [comment]
Fix will be available in 6.0.0-beta.7

**Comment by douzal34** [comment]
Hi @freeboub and @gkueny !

As a reminder I'm the owner of SoSkills App (video sharing app in gaming) and the issue mentionned above is still here on the 6.0.0-beta-8.

Use case:  Go in fullscreen mode on rotation, screen is off most of the time (rarely i see video displayed but it can occur) and when i comeback on portrait screen is off but player is still playing (onProgress still fired, sound is working but content not displayed)

Issue is here since the beginning of the beta version with the introduction of media 3 player.

**Comment by freeboub** [comment]
@douzal34 but this is a different issue I think... Can you follow up on another ticket please ? Providing a sample or reproducing it with the demo app would be useful!
