### ISSUE TITLE
Complex names causes video not to load

### ISSUE THREAD

**Issue by ospfranco** [TheWidlarzGroup/react-native-video#362]
I used react-native-fetch-blob to download a video to the device documents folder before reproducing it:
- I used a partial url to identify the video, ex:

`video/jo81389j1238.mp4`

this worked on iOS simulator, but not on android simulator, because it did not find the `video` folder
- I replaced the `/` with `_`

`video_m8j9283423.mp4`

this worked on both iOS and Android simulators, but when I tried running on device on iOS video did not load
- After trying several things, I ended up removing all foreign characters and ended with a alphanumeric only identifier, and that is the only way I got the library working.

`videomoiasd82n932.mp4`

This works everywhere.

**Comment by framosgo** [comment]
@ospfranco How could you add the video source in the component? Because it don't find my video in the internal documents. I'm working in IOS simulator and I'm using react-fetch-blob as well.

I downloaded a video and this is its url: 
`const localURL = '/book/content/myvideo.mp4';`

This is how I tried to assign the video with and without ".mp4"
(1) `const source = RNFetchBlob.fs.dirs.DocumentDir + localURL;`
(2) `const source = localURL;`
`<Video  source={{uri: source}} ... />`

And I got this:
```
<Warning>: Possible Unhandled Promise Rejection (id: 0):
	file not exists
	createErrorFromErrorData@http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7458:20
```

I also tried to remove all the subfolders which I created before, so I moved the video directly to `RNFetchBlob.fs.dirs.DocumentDir`, because its url is simpler as you recommend:
`const localURL = 'myvideo.mp4';`

Then I repeated the same steps as before and this isn't still working. Same warning and don't load the video.

**Comment by ospfranco** [comment]
Please review the fetch-blob documentation carefully, I remember I used something like this:

```
let dirs = RNFetchBlob.fs.dirs
RNFetchBlob
.config({
  // response data will be saved to this path if it has access right.
  path : dirs.DocumentDir + '/path-to-file.anything'
})
.fetch('GET', 'http://www.example.com/file/example.zip', {
  //some headers ..
})
.then((res) => {
  // the path should be dirs.DocumentDir + 'path-to-file.anything'
  console.log('The file saved to ', res.path())
})
```

There is some warnings about urls not being constant or something like that, but I remember that worked for me

**Comment by framosgo** [comment]
@ospfranco Thanks. I've already solved my problem of reproduce the video. I just needed add some height and width to see in my component. And regarding the complex names, I used `/` and `_` in my video on IOS simulator and it worked.

But I don't know why it still shows me the same warning of file not exists even when I see that the video is reproducing.

**Comment by ospfranco** [comment]
@jeimxx As I said, complex names work... sometimes on simulator, sometimes on device, be sure to test in all possible simulator/devices and you may see different results across the board.

Good luck
