### ISSUE TITLE
How to use this.player.presentFullscreenPlayer() correctly.

### ISSUE THREAD

**Issue by ronak301** [TheWidlarzGroup/react-native-video#392]
I have list of of photos and videos.
On clicking video i want to play full screen video.

**Comment by duhseekoh** [comment]
I have been putting items in a list (could be a photo, text, whatever you want) and when you press on that, render a video, then call `this.player.presentFullscreenPlayer();` I also set the video style to have a 0 width/height so the video is never displayed inline.

Something like...

```
render() {
 return (
  <TouchableHighlight onPress={this._onPressPlay}><Text>Play me</Text></TouchableHighlight>
  {this.state.isVideoVisible && <Video ref='player' ...></Video>}
 )
}

_onPressPlay() {
 this.setState({isVideoVisible, true}, () => {
  this.player.presentFullscreenPlayer();
 }
}
```

**Comment by ronak301** [comment]
is this also working on android ?

**Comment by avkvak** [comment]
Same question.. All works good on iOS, but nothing happens on android

**Comment by duhseekoh** [comment]
@ronak301 @avkvak - It's not mentioned in the readme, but presentFullscreenPlayer has no effect on android... unfortunately. A workaround is running a method based on platform and 

- iOS: use presentFullscreenPlayer
- Android: add styling to make it look full screen + add some type of controls

**Comment by davingreen** [comment]
Can anyone point to an example of full screen usage with Android? Especially on supporting landscape full screen, I'm having issues with playback using transform rotation. Here's an example of the approach:
`androidVideo: {
    backgroundColor: '#000',
    width: screenwidth,
    height: screenheight
  },`
 
`<View style={{transform: [{rotate: '90deg'}]}}><VIDEO></View>`

With the above approach, the video does not actually present in "full screen" because of Android Statusbar and any controls I add over the video (such as using the react-native-video-player wrapper) cease to work when presented this way. 

Thanks for any help!
