### ISSUE TITLE
[BUG]: How to Not Display the Controller When Using the PresentFullscreenPlayer Method for Full Screen Video

### ISSUE THREAD

**Issue by Wgga** [TheWidlarzGroup/react-native-video#3944]
### Version

6.3.0

### What platforms are you having the problem on?

Android

### System Version

Android 9

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

Do not want to display the default controller

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: When using the presentFullscreenPlayer method for full screen video

**Comment by seyedmostafahasani** [comment]
@Wgga, I don't think it's possible yet.

**Comment by Wgga** [comment]
> ，我认为这还是不可能的。

How to use custom controllers correctly

Displaying the default controller when the video is full screen causes the custom controller to fail to display

**Comment by seyedmostafahasani** [comment]
@Wgga, you cannot show custom controller in full-screen mode. You can only display them in normal mode because the layout for full-screen mode is handled on the native side.

**Comment by seyedmostafahasani** [comment]
@Wgga I have a suggestion for implementing a custom controller layout in full-screen mode. Instead of using the `setFullScreen` or other methods when the user presses the full-screen button, you can handle full-screen on the JS side. Specifically, you can create a new screen, and upon pressing the full-screen button, you can navigate to this new screen. This way, you can have your custom controller in full-screen mode.

**Comment by seyedmostafahasani** [comment]
@KrzysztofMoch 
I think we can close this issue.

**Comment by seyedmostafahasani** [comment]
@freeboub 
I think we can close this issue.
