### ISSUE TITLE
[BUG]: Android navigation bar stays hidden after video using fullscreen no longer mounted

### ISSUE THREAD

**Issue by sntg-p** [TheWidlarzGroup/react-native-video#4047]
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

Android 13

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

After playing the video or closing the screen with the video using `fullscreen={true}`, the status bar reappears but the navigation bar doesn't.

Maybe it is related to [this issue](https://github.com/TheWidlarzGroup/react-native-video/pull/3978).

### Reproduction

Step to reproduce this bug are:
- Show a screen with Video component with `fullscreen={true}`
- Close the screen

**Comment by seyedmostafahasani** [comment]
@sntg-p I think it must be fixed if you use the [setFullScreen](https://thewidlarzgroup.github.io/react-native-video/component/methods#setfullscreen) method when you want to close a screen with video by setting `fullscreen={true}`  as shown below.
`ref.current?.setFullScreen(false)`
Please use the `setFullscreen` method to handle the full-screen status instead of the `fullscreen` prop.

**Comment by seyedmostafahasani** [comment]
@sntg-p 
Did you test the above approach? When you want to call `goBack` function you can call this method: `setFullScreen(false)`.
Would you please share your code with me if it's possible or sample of your code?
