### ISSUE TITLE
[BUG]: DRM Video not Playing on Android

### ISSUE THREAD

**Issue by ShaimaaSabry** [TheWidlarzGroup/react-native-video#4119]
### Version

6.4.5

### What platforms are you having the problem on?

Android

### System Version

Pixel 8

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

I added the player to my code. Playing a plain mp4 file works fine. Playing a Dash DRM file displays a black screen, the player starts progressing for a second then it crashes and starts from the beginning and freezes. I tested the Dash video on an online player and it works fine. 

My code:
`
<Video 
            source={{
                uri: "https://dvfjyetbqjf38.cloudfront.net/test-output-1/BigBuckBunny.mpd",
            }}
            drm={{
                type: 'widevine',
                licenseServer:'https://drm-widevine-licensing.axprod.net/AcquireLicense',
                headers: {
                    'X-AxDRM-Messaige':'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJzaW9uIjoxLCJiZWdpbl9kYXRlIjoiMjAwMC0wMS0wMVQxMzo0NjoyMiswMzowMCIsImV4cGlyYXRpb25fZGF0ZSI6IjIwMjUtMTItMzFUMjM6NTk6NDArMDM6MDAiLCJjb21fa2V5X2lkIjoiZTljODZjMzctZmJkMi00NjhjLWIxNjMtYjFkODAwZWU2NDFlIiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsInZlcnNpb24iOjIsImxpY2Vuc2UiOnsiZHVyYXRpb24iOjM2MDB9LCJjb250ZW50X2tleXNfc291cmNlIjp7ImlubGluZSI6W3siaWQiOiI0YTg3ZDgxMy0wYTYxLTRkODktOWQ5OS0wOWUwYmEzN2ExYTIifV19fX0.BC_roJdYijF2-GGQh6wra5R_ap6lKgdoHnDzlxdtjJc',
                    'Content-Type': 'application/octet-stream'
                }
            }}
            style={styles.video}
        />
`

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment]
your DRM server report an error 400:

08-29 14:14:08.623 18391 18391 E RNVExoplayer: playerFailed [eventTime=7.48, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DRM_LICENSE_ACQUISITION_FAILED
08-29 14:14:08.623 18391 18391 E RNVExoplayer:   androidx.media3.exoplayer.ExoPlaybackException: Source error
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:717)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:671)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at android.os.Handler.dispatchMessage(Handler.java:102)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at android.os.Looper.loop(Looper.java:223)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at android.os.HandlerThread.run(HandlerThread.java:67)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:   Caused by: androidx.media3.exoplayer.drm.DrmSession$DrmSessionException: androidx.media3.exoplayer.drm.MediaDrmCallbackException: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 400
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at androidx.media3.exoplayer.drm.DefaultDrmSession.onError(DefaultDrmSession.java:569)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at androidx.media3.exoplayer.drm.DefaultDrmSession.onKeysError(DefaultDrmSession.java:556)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at androidx.media3.exoplayer.drm.DefaultDrmSession.onKeyResponse(DefaultDrmSession.java:515)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at androidx.media3.exoplayer.drm.DefaultDrmSession.access$100(DefaultDrmSession.java:61)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at androidx.media3.exoplayer.drm.DefaultDrmSession$ResponseHandler.handleMessage(DefaultDrmSession.java:631)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       at android.os.Handler.dispatchMessage(Handler.java:106)
08-29 14:14:08.623 18391 18391 E RNVExoplayer:       ... 2 more

please use charles proxy to understand the issue and reproduce with postman

**Comment by ShaimaaSabry** [comment]
@freeboub Thank you. Can you please explain to me how did you get this error message so that I follow in your steps and debug this issue?

**Comment by freeboub** [comment]
It is the extract of "adb logcat" in a shell.
Regarding how to debug, you should review this page in detail : https://thewidlarzgroup.github.io/react-native-video/other/debug

**Comment by ShaimaaSabry** [comment]
@freeboub Thank you. Fixed the issue.
