### ISSUE TITLE
Android video plays on load regardless of paused flag (device/release only)

### ISSUE THREAD

**Issue by briancalvium** [TheWidlarzGroup/react-native-video#494]
using `1.0.0`
I have the following in JS:

```
<RNVideo
  ...
  paused={true}
/>
```

in debug, this works as expected - user sees first frame of video, and video is paused. In release (on a Samsung S6), the video plays. 

I added a log statement to ReactVideoView:
```
if (mPaused) {
            if (mMediaPlayer.isPlaying()) {
                pause();
            } else {
                Log.d("VIDEO", "Attempted to pause when not playing!");
            }
        } else ...
```

and am seeing that message in LogCat.

**Comment by sarmadka** [comment]
I confirm this. Having the same issue. For me the video is playing even in debug mode in the simulator.

**Comment by DevAlien** [comment]
I found out the same issue, Videos play regardless of paused and of rate={0}

**Comment by pepavesely** [comment]
Same problem.

**Comment by davidjeffries** [comment]
Same issue as: #484 

Workaround, change the state on video load:
```
this.state = {paused: false};
```
Component:
```
paused={this.state.paused}
onLoad={() => {
  this.setState({
    paused: true
  });
}}
```

**Comment by ghost** [comment]
**ROOT CAUSE**
I think I found the possible root cause. In ReactVideoView, the onHostResume is called soon after the player is initialized and launched. What I believe is an unintended consequence is that whatever value was assigned to mPaused gets overwritten by the value of mActiveStatePauseStatus (which is always false when the class is initialized). This happens in the onHostResume when the setPausedModifier method is called.

**SOLUTION**
In the ReactVideoView class, you need to initialize mActiveStatePauseStatusInitialized not to false but to the value of the paused property that comes down from React Native. To achieve that:

1) add this in the constructor:
       private boolean mActiveStatePauseStatusInitialized = false;
2) add this in the setPausedModifier method, after the first line of code:
       if   (  !mActiveStatePauseStatusInitialized  ) {
               mActiveStatePauseStatus = mPaused;
               mActiveStatePauseStatusInitialized = true;
       }

**Comment by gorjanz** [comment]
I can confirm that @devmaster72 solution works. Is there a pull-request already, or should I create one?

Thank you!

**Comment by xavieramoros** [comment]
I have the same issue as well, solved using @davidjeffries solution to avoid initial paused flag problem. 

But I have a similar problem when my app goes to background and then becomes active again, the video plays despite being paused previously (with the paused prop being true based on state). My state doesn't change. Looks like it's related but not sure.

**Comment by ghost** [comment]
@xavieramoros, I tested that scenario in my app. Setting the paused prop in the onLoad does not address the root cause of the problem and leaves you exposed to the issue when you background the app and then foreground it. The issue is the one that I was referring in my previous post above. If you use what @gorjanz has committed yesterday all the issues will go away (make sure you remove the setting of the paused prop in the onLoad. Just set the paused prop of the video component to whatever you want it to be)

**Comment by xavieramoros** [comment]
Thanks @devmaster72 , I tested @gorjanz fix (https://github.com/react-native-community/react-native-video/commit/9ce1f4b5f41c1d9901f25ab180692a93d478c8df), both cases (background/foreground and initial props) work as expected.

My problem now is that I'm using android-exoplayer to avoid the issue of blocking UI while video is loading: #451, which is even worse. Not sure how to have both problem fixed.

**Comment by duhseekoh** [comment]
@xavieramoros - Are you saying this fix doesn't work when using exoplayer?

**Comment by xavieramoros** [comment]
Sorry for the misunderstanding and late reply @duhseekoh, I was just mentioning that there was still another issue, related to the UI being blocked while loading the video  #451.

ExoPlayer probably doesn't need this fix.

**Comment by waheedakhtar694** [comment]
Can anyone please tell me, Is this solution will work on exo-player too?
I am having same issue on exo-player
