### ISSUE TITLE
error when trying to remove <video> component from view

### ISSUE THREAD

**Issue by ArcadeRenegade** [TheWidlarzGroup/react-native-video#604]
I have some videos in a scrollview.
I just implemented pull down to refresh in the scrollview.
When I pull down to refresh, my scrollview gets removed and is replaced by a loading spinner.
I get an error at this point because react is trying to remove the <video> component from the view and it fails.

Is there a proper way to remove the video component?

![2384722112965611236-account_id 1](https://cloud.githubusercontent.com/assets/13874898/25795980/96704ec0-338c-11e7-8e7c-edc9b3896147.png)

**Comment by ArcadeRenegade** [comment]
I removed my custom loading spinner and tried it with the regular RefreshControl spinner instead.
This way the ScrollView does not get removed. Now it works and does not error. 

I'm okay with this method but not sure if this behavior is intentional or not so I'll leave this open.
Feel free to close if you want.

**Comment by yqbk** [comment]
I have the same issue with removing background video from the screen while changing current view. 

In my case when I changed version of _react-native-video_ lib from 1.0.0 to current from git, I don't get error message anymore. However it still doesn't solve the issue since app get frozen after performing screen change while video component is still running.

On iPhone both versions, 1.0.0 and current from git, work without any problems. Issue is connected with Android devices only.

**Comment by jksyrek** [comment]
In my case setting 
```
style={{ zIndex: 1 }} 
```
property was the origin of that problem. When I deleted that line I haven't got any errors more.
