### ISSUE TITLE
exo-player documentation

### ISSUE THREAD

**Issue by shirbr510** [TheWidlarzGroup/react-native-video#609]
there is no documentation on how to use exo-player instead of the regular android player

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by shirbr510** [comment]
Any comment from maintainers?

**Comment by shirbr510** [comment]
@brentvatne I'd love to use this component so hopefully if one of the collaborators could answer that would be lovely 👍

**Comment by frankiewiczkamil** [comment]
>  I'd love to use this component so hopefully if one of the collaborators could answer that would be lovely

@shirbr510  I added link to solution in #668

**Comment by shirbr510** [comment]
@frankiewiczsatlan thanks :)
Totally Appriciate your efforts!
(Even though the maintainers don't seem to answer issues that often here)

**Comment by poberwong** [comment]
You can find solution [here](https://www.bountysource.com/issues/40364073-exoplayer). Indeed, it could be the simplest way to remove directory named "android" and rename file named "android-exoplayer" to "android". Good luck～

**Comment by RameshSain** [comment]
Use android-exoplayer instead of android player:-

You need to change your configuration like that  ..

1. Go to **Settings.gradle**

**_DO THIS_** 

+ include ':app',

+        ':react-native-video-exoplayer'

- project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')
+ project(':react-native-video-exoplayer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

2.now go to app/build.gradle 

**_DO THIS_**  

+ compile project(':react-native-video-exoplayer')

**`If still you are facing issue in build then follow this`** 

https://github.com/iamronsuez/rn-video/pull/1

Thanks ,
Hope it will help.
