### ISSUE TITLE
Volume buttons not working [Android]

### ISSUE THREAD

**Issue by ghost** [TheWidlarzGroup/react-native-video#632]
Hello,

When I try to change the volume by using the physical buttons, there is no effect. It is changing a new bar that has no effect.

![img_7299](https://cloud.githubusercontent.com/assets/16573898/26354076/698ed438-3fc3-11e7-87df-53775fd2225a.JPG)

How can I solve that ?

Thanks !

**Comment by lekenny** [comment]
Do you use this to play web video successfully on Android?

**Comment by ghost** [comment]
@lekenny Yes I'm playing videos from a server.

**Comment by lehoi2195** [comment]
I have the same problem like you. Do you have a solution? 
Thanks !

**Comment by hisham** [comment]
I'm also getting this -when hardware button is used to adjust volume the device changes ringtone volume not media volume. In Java, this is what needs to be done "setVolumeControlStream(AudioManager.STREAM_MUSIC);
". 

Does react-native-video do this?

**Comment by cobarx** [comment]
For @Deevent it appears that he is changing the Chromecast audio rather than the video audio.

@hisham I'm pretty sure the Android MediaPlayer and ExoPlayer both let the device know that they are a media player and should adjust the music volume. If that's not happening it's likely because your video doesn't have sound or something like that.
