### ISSUE TITLE
Remove dependency on `react-native-windows`

### ISSUE THREAD

**Issue by bd** [TheWidlarzGroup/react-native-video#640]
`react-native-windows` is causing major headaches for me and my team due in the form of [this issue](https://github.com/facebook/react-native/issues/13925). While the ultimate error may be in the packager,  the windows dependency is unnecessary for a project not targeting windows at all. It is the proximate cause of our problems in that it has a naming conflict. It also adds to package bloat.

I'd be glad to help factor out the windows dependency to a separate package if need be.

**Comment by manask88** [comment]
https://github.com/react-native-community/react-native-video/issues/567 is related to this.
the react-native-windows dependency is causing naming collisions. This is okay in iOS but for Android, it's making my app crash. I think it would make sense to remove react-native-windows as a dependency since package.json doesn't even have react-native as a dependency or peerDependency. I'll be happy to help as well if the authors think this is the right approach
