### ISSUE TITLE
Play in reverse for infinite?

### ISSUE THREAD

**Issue by Noitidart** [TheWidlarzGroup/react-native-video#657]
Hi there,

I have a background of underwater, and if i play it forwards then reverse it is an infinite loop and seamless. If I do a repeat from start everytime, there is a noticeable jerk. Is it possible to play in reverse?

**Comment by JPWallhorn** [comment]
@Noitidart  We had the same issue but this is not a video player issue actually. A lot of times the audio track that's within the video file is slightly longer than the video itself. Therefore, there is a little lag.

You can either remove the audio track completely and make sure it's the same exact length. This is a tool that makes it both the same length: https://github.com/fluthaus/NHBAVAssetTrimming

Because even using the native Looper didn't work. Once we fixed the audio track, our loop was perfect.

**Comment by Noitidart** [comment]
Thank you @JPWallhorn that is very interesting! I really appreciate you sharing that with me, as it adds ideas here. My video was actually audio-less :(

**Comment by JPWallhorn** [comment]
Just because there is no sound, doesn't mean there is no soundtrack. By default, it comes with one. Try this tool and let me know if you see a difference. http://www.audioremover.com/

**Comment by Noitidart** [comment]
Oh wow this is super interesting, thank you for taking the time to share this!
