### ISSUE TITLE
fullscreen is not supported in android?

### ISSUE THREAD

**Issue by zhenliliu** [TheWidlarzGroup/react-native-video#684]

**Comment by rezaindrag** [comment]
I used react-native-orientation to solve this..

**Comment by dinatazy** [comment]
@rezaindrag  can you provide us with more details?

**Comment by rezaindrag** [comment]
@dinatazy But the screen is not 100% full, I just change the orientation to LANDSCAPE

`import Orientation from 'react-native-orientation';`

inside render method:

```
// LANDSCAPE
if (this.state.orientation === 'LANDSCAPE') {
      <Video source={{ uri: VIDEO_SOURCE }}
            // set height/width 100%
            style={{ height: '100%`, width: '100%' }}
      />
}

// PORTRAIT
// normal height/width
```

I hope this will help you

**Comment by xyklex** [comment]
@rezaindrag thanks for you comment, I'm facing this issue but I can't solve it using you approach.

My use case, I have a screen with a news video half above a description of it half below, the user can play the video and if he wants it can tap the fullscreen icon, and continue watching the video fullscreen in the position it was.

I tried two things, one was the dimensions thing, when tapping the fullscreen icon setting a new style, height and width with the size of the screen, of course this doesn't works because I found that absolute positioning is relative to the parent, and the screen is not the parent of my video view.

the second try was to use a Modal and include the same Video component inside it, this almost works, the Modal was launched, the video insert it, a little minor issue with the statusbar, but the Video instead of continuing in the same position it was, it's starting again, like a new instance, when I'm actually using the same.

Do anyone have knowledge about why this is happening? I read the code of the library for android and found that it's using this library [ScalableVideoView](https://github.com/yqritc/Android-ScalableVideoView/blob/master/library/src/main/java/com/yqritc/scalablevideoview/ScalableVideoView.java) and that library is using [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) and [TextureView](https://developer.android.com/reference/android/view/TextureView.html), this last library allow the video stream to render in the same view without creating a new one.

I could help write a solution for this, but I'm just starting reading about android development and react native, so if someone could help would be appreciated. @dinatazy

**Comment by ashwinprasadme** [comment]
@xyklex any update from your side?

**Comment by dengue8830** [comment]
in my case, using 

`componentDidMount -> video.presentFullscreenPlayer()`
or
`fullscreen={true}`

gives a random result, sometimes it hides the android bottom bar and sometimes don't (it makes a flash like hide->show android bottom bar)

**Comment by IbrahimSulai** [comment]
Opened a PR (#1730) for full-screen support in Android Exoplayer.
