### ISSUE TITLE
Video delay on Android

### ISSUE THREAD

**Issue by shukerullah** [TheWidlarzGroup/react-native-video#823]
Video works fine iOS but on Android video took 1-2 seconds to play. Is there anything that I am missing?

**Comment by xuananpham93** [comment]
+1

**Comment by linxiaoru** [comment]
same here!

**Comment by hoorsa** [comment]
+1
RN 49.5
Android 6.0
react-native-video 2.0.0 exoplayer

**Comment by hoorsa** [comment]
hi (sorry for my English).

this is buffering delay because just happened on remote files:
in my case:
1. onLoadStart called.
2. onBuffering called with isBuffering = true.
3. 1-2 second delay and then onBuffering called with isBuffering = false.
4. onLoad called and ...

this is normal on first play of a remote file, but why buffering took 1-2 seconds on playing this remote file again? does react-native-video cache remote videos or no?

**Comment by shukerullah** [comment]
Video is also not working on lower android devices.

**Comment by hoorsa** [comment]
switch to ExoPlayer

**Comment by pgpankajbigstep** [comment]
> Buffering performance on ExoPlayer is significantly better than Android MediaPlayer, you should switch to it.

I switched from MediaPlayer to ExoPlayer but still it show 1 sec delay for every video while swipping.
