### ISSUE TITLE
under react native 0.48     Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by AntsWang** [TheWidlarzGroup/react-native-video#840]

**Comment by jeremydanner** [comment]
I'm using right now `"react-native": "0.48.4"` and I am testing `"react-native-video": "^2.0.0"` for an app I'm building. Is this error fixed in the newest version of React native? Or is there an old version of `react-native-video` that is stable enough for `"react-native": "0.48.4"`? @AntsWang 

I also have the problem `Cannot read property 'Constants' of undefined`

**Comment by aronmoles** [comment]
I have same issue. Can you help? please

**Comment by jeremydanner** [comment]
@aronmoles downgrading to version `"react-native-video": "1.2.0"` fixed the problem.

**Comment by SaidTayebi** [comment]
what version of React-Native are you using ?

**Comment by jeremydanner** [comment]
``` 
"react-native": "0.48.4",
"react-native-video": "1.2.0",
```
