### ISSUE TITLE
Using seek function to skip further in the video than video has loaded

### ISSUE THREAD

**Issue by Waltari10** [TheWidlarzGroup/react-native-video#843]
I am calling the seek function after the video has loaded. I do this in order to skip the intro part of a video that has already been watched.

However this does not result in expected behaviour. Instead of skipping to the part of the video specified it does nothing. I think this is because the video hasnt loaded that far. Why cant we skip further than the video has loaded?

```
<Video
  ref={ref => (this.video = ref)}
  source={{uri: url}}
  onLoad={async () => {
    this.video.seek(10) // Does not work
    await new Promise(resolve => setTimeout(resolve, 1000))
    this.player.seek(10) // works
  }}
/>
```

**Comment by Waltari10** [comment]
Very occasionally it seems to work, but mostly not.

**Comment by Waltari10** [comment]
Maybe its breaking because its trying to seek further than the video has actually loaded?

**Comment by Waltari10** [comment]
I also tried calling the seek function in onBuffer and only when isBuffering is false. Still it did not work 100% of time.

**Comment by Winglonelion** [comment]
same problem.

**Comment by treemore** [comment]
this only happen in ios .but not android exoplayer

**Comment by callmejm** [comment]
same issue here with version 2.0.0

**Comment by ryndshn** [comment]
i'm experiencing odd behavior that i think might be related to this. i am attempting to seek to a desired part of the video. instead of playing from the seeked location, it starts playing from an earlier location. for example, if i seek to 400 seconds, it starts playing from 394 seconds. i think this occurs because when i attempt to seek it has only loaded up to 394 seconds, but not to 400 seconds, so it starts playing from an earlier location. 

i'm not 100% sure this is related, but i thought i'd mention it.

**Comment by anukuljha** [comment]
hey @Waltari10 did you find any solution or any work around?

**Comment by johnyoonh** [comment]
> this only happen in ios .but not android exoplayer

For us, it's the opposite, it doesn't happen on iOS, but on Android

**Comment by nayanLr** [comment]
Thank you, @Waltari10 for solving my problem.
