### ISSUE TITLE
Black screen on fullscreen swipe

### ISSUE THREAD

**Issue by kay-is** [TheWidlarzGroup/react-native-video#861]
When I start a video I set it to fullscreen, when I swipe in this mode, the screen goes black and the audio (probably also the video) stops.

I can't get out of the fullscreen mode and need to close the app.

**Comment by kay-is** [comment]
It seems like a swipe in fullscreen mode triggers `onFullscreenPlayerWillDismiss` even tho the fullscreen doesn't dismiss, the video seems to get dragged a bit with the swipe, but moves to the original position again.

**Comment by kay-is** [comment]
Found a few undocumented callbacks in the source, that fixed my problem.

**Comment by Ahmed-Emad** [comment]
I think this is a bug that is present only in iOS 11. As in iOS 11, Apple added a feature to close the Video Player via a swipe gesture. When not swiping completely the video player does not dismiss neither continue playing the video. The app stocks in a black screen.

I made a pull request to fix this issue by dismissing the video in that case https://github.com/react-native-community/react-native-video/pull/1042

**Comment by cobarx** [comment]
@Ahmed-Emad Thanks for the PR! The ideal behavior would be to make it work exactly like on a native app where a partial swipe doesn't interrupt the video but the full swipe. Any idea if there is any way we could make that happen?

I've run into this on my own app and it's super annoying since it's so easy to accidentally trigger dismissing the video. It's so bad that I'd rather completely disable the gesture than deal have someone close their video by tapping on the screen too much.

**Comment by Ahmed-Emad** [comment]
@cobarx Thank you for the response. After some investigation I got to the expected behavior (partial swipe does nothing and only full swipe dismisses the player).

I made a new pull request with it https://github.com/react-native-community/react-native-video/pull/1048
