### ISSUE TITLE
Auto Rotate

### ISSUE THREAD

**Issue by callmejm** [TheWidlarzGroup/react-native-video#864]
I have a screens with width 1080 and height 1920, ratio 9:16 and android version is 4.2.2.  Player automatically rotate it self, any idea ?

**Comment by LaloHao** [comment]
Listen for orientation change and change the layout according to it

http://www.dotnetsurfers.com/blog/2017/05/08/detecting-device-orientation-change-with-react-native

**Comment by mousikosk** [comment]
Indeed still experiencing this on two Android 4.4.2 devices. Devices with Android 5 and above work fine, but on KitKat portrait videos are rotated 90 degrees clockwise. Also it seems to be an issue on all emulators (irrespective of version number). It is not a matter of orientation change as our app is fixed in portrait mode.
