### ISSUE TITLE
this.player.presentFullscreenPlayer() auto landscape 

### ISSUE THREAD

**Issue by callmejm** [TheWidlarzGroup/react-native-video#902]
In iOS how can call `this.player.presentFullscreenPlayer()` and directly rotate to landscape . I have try to use `react-native-orientation` to `Orientation.lockToLandscape();` together when call `this.player.presentFullscreenPlayer()` , seem not work. There is a function call `setFullscreen` in `RTCVideo.m` , does anyone know how to modified so that when trigger `this.player.presentFullscreenPlayer()` it start from landscape , Thanks you.

**Comment by mrarronz** [comment]
Hi, here is my solution: [https://github.com/mrarronz/react-native-blog-examples/tree/master/Chapter7-VideoPlayer/VideoExample](https://github.com/mrarronz/react-native-blog-examples/tree/master/Chapter7-VideoPlayer/VideoExample).

also use react-native-orientation to force rotate screen, I implement full screen mode myself, because `presentFullscreenPlayer()` does not work on android.
