### ISSUE TITLE
Video still playing while navigate to another screen

### ISSUE THREAD

**Issue by KrGyan** [TheWidlarzGroup/react-native-video#916]
Video is still playing in backgroung , while the app has navigated to another screen.

Please suggest.

**Comment by KlimczakM** [comment]
I have the same issue on iOS, have anyone found any solution to this?

It occurs both on iOS10 and iOS11, on Android it works fine. I'm using 2.0.0 version added with yarn.

**Comment by VrajSolanki** [comment]
I have implemented 2 video component in consecutive screens. The video does not stop because when you navigate from a screen the previous screen does not unmount and so the video player also.
for eg:  if you are using stack-navigation of react-native-navigation then the current screen does not unmount on navigating to the next screen, and so the video continues to play.
Solution:
1. you can use https://github.com/pmachowski/react-navigation-is-focused-hoc which helps you to know whether the particular screen is mounted or not and depending upon that you can unmount the video player.
2. you can save your routeName in the redux and pass this to each screen which then checks for the same, whether mounted or not and then unmount the videoPlayer.
 to unmount the player: this.prop.isInFocus ? <VideoPlayer /> : null

**Comment by tmpfs** [comment]
I have the same issue and the current solutions suggested above seem far from ideal. There should be a programmatic way for me to `stop()` the video, then I can just use the `willBlur` listener in `react-navigation`.

**Comment by tmpfs** [comment]
Spoke too soon. I am using `react-native-video-controls` and if you have a reference to the controls wrapper (`player`) then this seems to work ok:

```javascript
componentWillMount () {
  this.blurSubscription =
    this.props.navigation.addListener(
      'willBlur',
      () => {
        if (!this.player.state.paused) {
          this.player.methods.togglePlayPause()
        }
      }
    )
}

componentWillUnmount () {
  this.blurSubscription.remove()
}
```

I don't like the idea of using an HOC or redux as I have many views that do not have a video player so doing this in a generic fashion seems inappropriate.

**Comment by Q8hma** [comment]
Hello

any one got to fix this  ??

thnx

**Comment by cobarx** [comment]
This needs to be handled via your navigation library as @tmpfs suggests. The video is still there and mounted when you go to the next screen, so there's no way for it to know it should pause except if you capture the event and tell it.

**Comment by niralievasoya** [comment]
Hello
I am using 'react-native-router-flux' for navigation, so when moving from one screen to another screen that also contain video component, so previous video is still playing.
can anyone help me to solve it out?

**Comment by otaro808** [comment]
Please review this comment for solution:
[https://github.com/react-native-community/react-native-video/issues/1223](https://github.com/react-native-community/react-native-video/issues/1223)

**Comment by robleds** [comment]
@tmpfs solution works like a charm for me! Thanks dude.

**Comment by linux08** [comment]
@robleds could you please share a snippet or create a gist?
I'm also facing the bug.

**Comment by robleds** [comment]
Yes for sure. Let me back to computer to share it with you. Sorry for late reply.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nagad814** [comment]
currently working in my app

`  componentWillMount () {
    this.blurSubscription =
      this.props.navigation.addListener(
        'willBlur',
        () => {
          if (this.player && !this.player.state.paused) {
            console.log(this.player);
            this.player.onPlayPress();
          }
        }
      )
  }
  
  componentWillUnmount () {
    this.blurSubscription.remove()
  }`

**Comment by CyxouD** [comment]
described solution for different issue: after unmounting video still played https://github.com/react-native-community/react-native-video/issues/1223#issuecomment-547379209
