### ISSUE TITLE
Is there a limit to number of video components?

### ISSUE THREAD

**Issue by Tsiniloiv** [TheWidlarzGroup/react-native-video#932]
I've got a horizontal paging FlatList that needs to display both images and videos, but I'm running into an issue where only about four videos are being displayed at all.

It's got me wondering - is there a limit to the number of video components that can be rendered?

**Comment by arminsal1** [comment]
Are you using iOS and using a physical device? Because if so, Apple restricts the number of video elements that can play in an app simultaneously that varies depending on the device.

My workaround for my FlatList implementation was to use the `onViewableItemsChanged` FlatList prop to keep track of which items are visible and then only rendering the `<Video/>` component on visible items

**Comment by Tsiniloiv** [comment]
Using Android and a physical device. It seems to be related to how many video components are mounted at the same time. Things work as intended if I manage to control things so that only one video mounts at a time, but the moment it gets to be more than one everything goes pear-shaped.

Like, whether or not the videos were being rendered didn't matter - I tried a workaround through onViewableItemsChanged and still had the same problem.

I've since switched to react-native-swiper, and it makes things work. Anything not on the screen is unmounted, everything on the screen is mounted.
