### ISSUE TITLE
Controls float over other views when scrolling, showing a modal, changing to another page, and more

### ISSUE THREAD

**Issue by aike19115** [TheWidlarzGroup/react-native-video#953]
**Versions:**
React: **16.2.0**
React-Native: **0.52.0**
React-Native-Video: **2.0.0**

**I'm submitting a**
Bug report.

**Current behavior:**
The video controls seem to be fixed on a single position. This causes problems with many user interactions. For example:
- Scrolling
- Showing a modal
- Changing to another page (with [React-Navigation](https://github.com/react-navigation/react-navigation))
- Showing a spinner

**Expected behavior:**
The video controls should be contained in the Video component. Example: when a user scrolls inside a ScrollView the controls should scroll accordingly.

**Similar issues:**
#349 

**Steps to reproduce:**
create-react-native-app video-test-app;
cd video-test-app;
yarn run eject;
yarn add react-native-video;
react-native link;
*edit code*
react-native run-android;

**Other information:**
See this YouTube video for an example: https://youtu.be/oT0aOd62CvU

**The code:**

```

import React from 'react';
import { StyleSheet, Text, View, ScrollView } from 'react-native';
import Video from 'react-native-video';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <ScrollView contentContainerStyle={styles.scrollView}>
          <View style={styles.view} />
          <Video
            style={styles.video}
            source={{ uri: 'http://media.dumpert.nl/tablet/1009c3ea_a3KqvdN_460sv.mp4.mp4.mp4' }}
            controls={true}
            resizeMode="cover"
          />
          <View style={styles.view} />
        </ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  scrollView: {
    alignItems: 'center',
  },
  video: {
    width: 320,
    height: 180,
  },
  view: {
    width: '100%',
    height: 400,
    backgroundColor: '#aaa',
  },
});

```

**Comment by DiegoDevBittencourt** [comment]
Same here, someone can give a help please?

**Comment by elizond0** [comment]
Same issue

**Comment by fangasvsass** [comment]
only mediaplayer have the problem, on  react-native-video 4.4.2

**Comment by CHaNGeTe** [comment]
> only mediaplayer have the problem, on react-native-video 4.4.2

You mean exoplayer and ios do not have this problem?

**Comment by fangasvsass** [comment]
> > only mediaplayer have the problem, on react-native-video 4.4.2
> 
> You mean exoplayer and ios do not have this problem?

that's right

**Comment by mlazari** [comment]
I can confirm that ExoPlayer does not have this issue. If you use autolinking you can opt to use ExoPlayer by adding a `react-native.config.json` file to the root of your project with this content:
```
module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};
```
I found this here: https://github.com/react-native-community/react-native-video/issues/1747#issuecomment-572512595 The only difference is that I had to use `../node_modules` instead of `./node_modules`.

**Comment by dipankurXT** [comment]
> I can confirm that ExoPlayer does not have this issue. If you use autolinking you can opt to use ExoPlayer by adding a `react-native.config.json` file to the root of your project with this content:
> 
> ```
> module.exports = {
>   dependencies: {
>     'react-native-video': {
>       platforms: {
>         android: {
>           sourceDir: '../node_modules/react-native-video/android-exoplayer',
>         },
>       },
>     },
>   },
> };
> ```
> 
> I found this here: [#1747 (comment)](https://github.com/react-native-video/react-native-video/issues/1747#issuecomment-572512595) The only difference is that I had to use `../node_modules` instead of `./node_modules`.


i am unable to create a release build after using this fix. 
"react-native": "0.64.2",
"react-native-video": "^5.2.0",

![Screenshot 2022-04-06 at 4 04 52 PM](https://user-images.githubusercontent.com/101088781/161956503-4518b030-7f00-4998-8ea6-99f100f886a2.png)

**Comment by aman-g202** [comment]
@dipankurXT You are unable to run app because you must be getting error related to com.google.android.exoplayer:exoplayer:2.13.2 not found, this is because 2.13.2 is not available under maven artifact [see here](https://mvnrepository.com/artifact/com.google.android.exoplayer/exoplayer). So quick fix will be to modify build.gradle file located in this location

`node_modules/react-native-video/android-exoplayer/build.gradle`

**Make these two changes**

**Replace this line** implementation('com.google.android.exoplayer:exoplayer:2.13.2’) { —>  **by** implementation('com.google.android.exoplayer:exoplayer:2.13.3') {

**Replace this line** implementation('com.google.android.exoplayer:extension-okhttp:2.13.2’) { —>  **by** implementation('com.google.android.exoplayer:extension-okhttp:2.13.3') 

Now build it, hopefully, it should work.

[You can refer here for more detail related to fix](https://github.com/react-native-video/react-native-video/issues/2611)
