### ISSUE TITLE
No way to stop video from preloading.

### ISSUE THREAD

**Issue by jwan3453** [TheWidlarzGroup/react-native-video#962]
I'm trying to create a list of video previews  before playing a specific video.  So I can get the preview showing for all videos, but seems they are all preloaded. How can I prevent video from preloading. So is there other way to create a preview for video.

**Comment by VrajSolanki** [comment]
You can use exoPlayer for android and for iOS, the player by default supports HLS. 
So by using hls you can stream the videos.

One additional settings that I am using is making a thumbImg for the video so that in the list I display the thumb with play button. This does not load all the videos for me, only the one user clicks to play is loaded.
